[project]
name = "quincyfadez-api"
version = "0.1.0"
requires-python = ">=3.12,<3.13"
dependencies = [
  "fastapi==0.110.1",
  "python-dotenv>=1.0.1",
  "motor==3.3.1",
  "pymongo==4.6.3",
  "pydantic>=2.6.4,<3",
  "email-validator>=2.2.0",
  "stripe>=15.4.0,<16",
  "requests>=2.31.0",
  "tzdata>=2024.2",
]

[tool.vercel]
entrypoint = "runtime:app"
