import React, { useEffect, useState } from "react";
import { Pressable, SafeAreaView, ScrollView, StatusBar, StyleSheet, Text, TextInput, View } from "react-native";
import AsyncStorage from "@react-native-async-storage/async-storage";

const BG="#050505",GOLD="#C99B4A",GOLD_LIGHT="#E7C77A",BORDER="#242424",MUTED="#929292";
const PROFILE_STORAGE="quincyfadez.bookingProfile",SESSION_STORAGE="quincyfadez.clientSession";

export default function AuthScreen({onClient,onAdmin}){
  const [mode,setMode]=useState("login"),[name,setName]=useState(""),[email,setEmail]=useState(""),[phone,setPhone]=useState(""),[error,setError]=useState("");
  useEffect(()=>{AsyncStorage.getItem(SESSION_STORAGE).then(v=>{if(v==="active")onClient()}).catch(()=>{})},[onClient]);
  const submit=async()=>{
    setError("");
    if(mode==="signup"){
      if(name.trim().length<2||phone.trim().length<7||!email.includes("@")){setError("Add your name, mobile number and email to create your account.");return;}
      await AsyncStorage.setItem(PROFILE_STORAGE,JSON.stringify({name:name.trim(),phone:phone.trim(),email:email.trim().toLowerCase()}));
      await AsyncStorage.setItem(SESSION_STORAGE,"active"); onClient(); return;
    }
    const saved=await AsyncStorage.getItem(PROFILE_STORAGE);
    if(!saved){setError("No client account is saved on this phone yet. Choose Sign Up first.");return;}
    const profile=JSON.parse(saved),entered=email.trim().toLowerCase();
    if(!entered||entered!==String(profile.email||"").toLowerCase()){setError("That email does not match the client account saved on this phone.");return;}
    await AsyncStorage.setItem(SESSION_STORAGE,"active"); onClient();
  };
  return <SafeAreaView style={s.safe}><StatusBar barStyle="light-content" backgroundColor={BG}/><ScrollView contentContainerStyle={s.content} keyboardShouldPersistTaps="handled"><View style={s.logo}><Text style={s.logoText}>QF</Text></View><Text style={s.eyebrow}>QUINCYFADEZ</Text><Text style={s.title}>Your Cut. Your Account.</Text><Text style={s.copy}>Clients sign in here to book and manage appointments. Owner access opens a completely separate admin workspace.</Text><View style={s.tabs}><Pressable onPress={()=>{setMode("login");setError("")}} style={[s.tab,mode==="login"&&s.tabActive]}><Text style={[s.tabText,mode==="login"&&s.tabTextActive]}>LOG IN</Text></Pressable><Pressable onPress={()=>{setMode("signup");setError("")}} style={[s.tab,mode==="signup"&&s.tabActive]}><Text style={[s.tabText,mode==="signup"&&s.tabTextActive]}>SIGN UP</Text></Pressable></View><View style={s.card}>{mode==="signup"?<><Text style={s.label}>NAME</Text><TextInput value={name} onChangeText={setName} placeholder="Your name" placeholderTextColor="#555" autoCapitalize="words" style={s.input}/><Text style={s.label}>MOBILE</Text><TextInput value={phone} onChangeText={setPhone} placeholder="07..." placeholderTextColor="#555" keyboardType="phone-pad" style={s.input}/></>:null}<Text style={s.label}>EMAIL</Text><TextInput value={email} onChangeText={setEmail} placeholder="you@example.com" placeholderTextColor="#555" keyboardType="email-address" autoCapitalize="none" style={s.input}/>{error?<Text style={s.error}>{error}</Text>:null}<Pressable onPress={submit} style={s.primary}><Text style={s.primaryText}>{mode==="signup"?"CREATE CLIENT ACCOUNT":"OPEN CLIENT ACCOUNT"}</Text><Text style={s.arrow}>›</Text></Pressable></View><Pressable onPress={onAdmin} style={s.admin}><View><Text style={s.adminEyebrow}>OWNER ACCESS</Text><Text style={s.adminTitle}>QuincyFadez Admin</Text><Text style={s.adminText}>Insights · Bookings · Clients · Schedule · Settings</Text></View><Text style={s.adminArrow}>›</Text></Pressable></ScrollView></SafeAreaView>;
}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:BG},content:{flexGrow:1,paddingHorizontal:22,paddingTop:52,paddingBottom:36},logo:{width:70,height:70,borderRadius:35,borderWidth:1,borderColor:"#5A4521",backgroundColor:"#120F08",alignItems:"center",justifyContent:"center"},logoText:{color:GOLD_LIGHT,fontSize:23,fontWeight:"900"},eyebrow:{color:GOLD,fontSize:8,letterSpacing:2.2,fontWeight:"900",marginTop:24},title:{color:"#F5F5F5",fontSize:31,lineHeight:36,fontWeight:"750",marginTop:8},copy:{color:MUTED,fontSize:12,lineHeight:19,marginTop:10},tabs:{flexDirection:"row",backgroundColor:"#090909",borderWidth:1,borderColor:BORDER,borderRadius:15,padding:4,marginTop:26},tab:{flex:1,minHeight:42,borderRadius:11,alignItems:"center",justifyContent:"center"},tabActive:{backgroundColor:"#181207",borderWidth:1,borderColor:"#4E3C20"},tabText:{color:"#666",fontSize:8,fontWeight:"900",letterSpacing:1.2},tabTextActive:{color:GOLD_LIGHT},card:{marginTop:12,borderRadius:20,borderWidth:1,borderColor:"#29251D",backgroundColor:"#0A0907",padding:16},label:{color:"#A98A54",fontSize:7.5,letterSpacing:1.3,fontWeight:"900",marginTop:10,marginBottom:6},input:{minHeight:50,borderRadius:14,borderWidth:1,borderColor:"#292929",backgroundColor:"#0E0E0E",color:"#F3F3F3",paddingHorizontal:14,fontSize:12},error:{color:"#E4A29A",fontSize:9.5,lineHeight:15,marginTop:12},primary:{minHeight:58,borderRadius:15,backgroundColor:GOLD,marginTop:16,paddingHorizontal:17,flexDirection:"row",alignItems:"center",justifyContent:"space-between"},primaryText:{color:"#090909",fontSize:9.5,letterSpacing:1,fontWeight:"900"},arrow:{color:"#090909",fontSize:28},admin:{marginTop:14,minHeight:82,borderRadius:18,borderWidth:1,borderColor:"#242424",backgroundColor:"#0D0D0D",paddingHorizontal:16,flexDirection:"row",alignItems:"center",justifyContent:"space-between"},adminEyebrow:{color:"#777",fontSize:6.5,letterSpacing:1.2,fontWeight:"900"},adminTitle:{color:"#F1F1F1",fontSize:14,fontWeight:"750",marginTop:4},adminText:{color:"#777",fontSize:8.5,marginTop:4},adminArrow:{color:GOLD_LIGHT,fontSize:28}});