import React,{useEffect,useState} from "react";
import {Pressable,SafeAreaView,ScrollView,StatusBar,StyleSheet,Text,View} from "react-native";
import AsyncStorage from "@react-native-async-storage/async-storage";
import {BrandLogo,M,Marble,Surface} from "./QFTheme";
import {ClientHeader} from "./ClientLuxuryUI";
import QFIcon from "./QFIcons";

const API=(process.env.EXPO_PUBLIC_API_URL||"").replace(/\/$/,"");
const PREFS="quincyfadez.clientPrefs",SESSION="quincyfadez.clientSession";
const defaults={confirmations:true,reminders:true,reschedule:true,waitlist:true,reviews:true};
const read=r=>r.json().catch(()=>({}));
function Toggle({value,onPress,disabled}){return <Pressable disabled={disabled} onPress={onPress} style={[s.toggle,value&&s.toggleOn,disabled&&{opacity:.55}]}><View style={[s.knob,value&&s.knobOn]}/></Pressable>}
function Row({icon,title,sub,value,onPress,last=false,disabled=false}){return <View style={[s.row,!last&&s.line]}><View style={s.icon}><QFIcon name={icon} size={24}/></View><View style={{flex:1}}><Text style={s.rowTitle}>{title}</Text><Text style={s.rowSub}>{sub}</Text></View><Toggle value={value} onPress={onPress} disabled={disabled}/></View>}

export default function ClientNotificationsScreen({onBack}){
  const[prefs,setPrefs]=useState(defaults),[saved,setSaved]=useState(false),[saving,setSaving]=useState(false),[error,setError]=useState("");
  useEffect(()=>{let alive=true;(async()=>{try{const[local,raw]=await Promise.all([AsyncStorage.getItem(PREFS),AsyncStorage.getItem(SESSION)]);if(local)try{if(alive)setPrefs({...defaults,...JSON.parse(local)})}catch(_){}const session=raw?JSON.parse(raw):null;if(API&&session?.token){const r=await fetch(`${API}/api/notifications/preferences`,{headers:{Authorization:`Bearer ${session.token}`}}),d=await read(r);if(r.ok&&d.preferences){const live={...defaults,...d.preferences};if(alive)setPrefs(live);await AsyncStorage.setItem(PREFS,JSON.stringify(live))}}}catch(_){}return()=>{alive=false}})()},[]);
  const toggle=async k=>{if(saving)return;const before=prefs,next={...prefs,[k]:!prefs[k]};setPrefs(next);setSaving(true);setSaved(false);setError("");try{await AsyncStorage.setItem(PREFS,JSON.stringify(next));const raw=await AsyncStorage.getItem(SESSION),session=raw?JSON.parse(raw):null;if(!session?.token)throw new Error("Your login session has expired. Please log in again.");if(!API)throw new Error("Notification preferences are unavailable in this build.");const r=await fetch(`${API}/api/notifications/preferences`,{method:"PUT",headers:{"Content-Type":"application/json",Authorization:`Bearer ${session.token}`},body:JSON.stringify(next)}),d=await read(r);if(!r.ok||!d.preferences)throw new Error(typeof d.detail==="string"?d.detail:"Your notification preferences could not be saved.");const live={...defaults,...d.preferences};setPrefs(live);await AsyncStorage.setItem(PREFS,JSON.stringify(live));setSaved(true);setTimeout(()=>setSaved(false),1300)}catch(e){setPrefs(before);await AsyncStorage.setItem(PREFS,JSON.stringify(before)).catch(()=>{});setError(e.message||"Your notification preferences could not be saved.")}finally{setSaving(false)}};
  return <Marble><SafeAreaView style={s.safe}><StatusBar barStyle="light-content"/><ScrollView contentContainerStyle={s.content} showsVerticalScrollIndicator={false}>
    <ClientHeader title="Notifications" subtitle="Choose which appointment updates and useful reminders you want to receive." onBack={onBack}/>
    {saved?<View style={s.saved}><QFIcon name="check" size={17} color={M.green}/><Text style={s.savedText}>Saved to your account</Text></View>:null}
    {error?<View style={s.error}><Text style={s.errorText}>{error}</Text></View>:null}
    <Surface style={s.card}><Row icon="check" title="Booking confirmations" sub="Confirmations and important booking-status updates." value={prefs.confirmations} onPress={()=>toggle("confirmations")} disabled={saving}/><Row icon="clock" title="Appointment reminders" sub="Upcoming appointment and useful rebooking reminders." value={prefs.reminders} onPress={()=>toggle("reminders")} disabled={saving}/><Row icon="repeat" title="Reschedule updates" sub="Be alerted if an appointment time changes." value={prefs.reschedule} onPress={()=>toggle("reschedule")} disabled={saving}/><Row icon="bell" title="Waitlist alerts" sub="Hear quickly when a suitable cancellation opens up." value={prefs.waitlist} onPress={()=>toggle("waitlist")} disabled={saving}/><Row icon="star" title="Review reminders" sub="A light reminder after a completed visit." value={prefs.reviews} onPress={()=>toggle("reviews")} disabled={saving} last/></Surface>
    <Surface style={s.note}><BrandLogo size={46}/><View style={{flex:1}}><Text style={s.noteTitle}>Your choices are respected</Text><Text style={s.noteText}>These settings now control the push notifications sent to your QuincyFadez account, not just this phone.</Text></View></Surface>
  </ScrollView></SafeAreaView></Marble>;
}

const s=StyleSheet.create({safe:{flex:1},content:{paddingHorizontal:18,paddingTop:4,paddingBottom:86},saved:{alignSelf:"flex-end",height:36,borderRadius:18,borderWidth:1,borderColor:"rgba(85,216,117,.22)",backgroundColor:M.greenBg,paddingHorizontal:12,alignItems:"center",justifyContent:"center",marginTop:5,marginBottom:8,flexDirection:"row",gap:7},savedText:{color:M.green,fontSize:11.5,fontWeight:"700"},error:{borderRadius:14,borderWidth:1,borderColor:"rgba(240,125,115,.24)",backgroundColor:M.redBg,padding:14,marginTop:5,marginBottom:9},errorText:{color:M.red,fontSize:12.5,lineHeight:18},card:{overflow:"hidden",marginTop:9,backgroundColor:M.panel2,borderColor:M.warmBorderSoft},row:{minHeight:94,paddingHorizontal:15,paddingVertical:15,flexDirection:"row",alignItems:"center",gap:14},line:{borderBottomWidth:1,borderBottomColor:"rgba(255,255,255,.08)"},icon:{width:48,height:48,borderRadius:15,backgroundColor:M.panel3,borderWidth:1,borderColor:M.border,alignItems:"center",justifyContent:"center"},rowTitle:{color:M.text,fontSize:15.5,fontWeight:"700"},rowSub:{color:M.muted,fontSize:12.5,lineHeight:17,marginTop:5,paddingRight:8},toggle:{width:55,height:32,borderRadius:16,borderWidth:1,borderColor:M.border,backgroundColor:M.panel4,padding:3,justifyContent:"center"},toggleOn:{backgroundColor:M.accent,borderColor:M.accentBright},knob:{width:24,height:24,borderRadius:12,backgroundColor:M.muted},knobOn:{alignSelf:"flex-end",backgroundColor:M.bg},note:{padding:18,marginTop:16,flexDirection:"row",gap:13,alignItems:"center",backgroundColor:M.panel2,borderColor:M.warmBorderSoft},noteTitle:{color:M.text,fontSize:15.5,fontWeight:"700"},noteText:{color:M.muted,fontSize:12.5,lineHeight:18,marginTop:5}});
