import React,{useEffect,useState}from"react";
import{Image,Linking,Pressable,SafeAreaView,ScrollView,Share,StatusBar,StyleSheet,Text,View}from"react-native";
import AsyncStorage from"@react-native-async-storage/async-storage";
import AuthScreen from"./AuthScreen";
import BookingScreen from"./BookingScreen";
import GalleryScreen from"./GalleryScreen";
import ReviewsScreen from"./ReviewsScreen";
import AccountScreen from"./AccountScreen";
import AdminNotificationsShell from"./AdminNotificationsShell";
import ClientBookingsLuxury from"./ClientBookingsLuxury";
import{QF,qfCardShadow,qfShadow}from"./QuincyTheme";

const PROFILE="quincyfadez.bookingProfile";
const links={whatsapp:"https://wa.me/447490194682",directions:"https://www.google.com/maps/dir/?api=1&destination=51.7402247,-1.2202434",website:"https://quincyfadez.com",reviews:"https://g.page/r/CbQwl91s8_vqEBM/review"};
const services=[{name:"Haircut",price:"£20",duration:"45 Minutes",description:"Skin fades, tapers, scissor work and clean finishes."},{name:"Haircut & Beard",price:"£25",duration:"60 Minutes",description:"A full haircut with a sharp, shaped and lined beard finish."},{name:"Shape Up",price:"£10",duration:"15 Minutes",description:"A quick refresh for crisp edges between full cuts."},{name:"Beard Trim",price:"£10",duration:"15 Minutes",description:"Beard groomed, shaped and lined for a clean result."}];
const open=url=>Linking.openURL(url).catch(()=>{});

function Logo({small=false}){return <View style={[s.logo,small&&s.logoSmall]}><Image source={require("../assets/icon.png")} style={[s.logoImg,small&&s.logoImgSmall]}/></View>}
function NavGlyph({type,active}){const c=active?QF.goldSoft:QF.muted2;if(type==="home")return <View style={[s.gHome,{borderColor:c}]}><View style={[s.gHomeDot,{backgroundColor:c}]}/></View>;if(type==="bookings")return <View style={[s.gCal,{borderColor:c}]}><View style={[s.gCalTop,{backgroundColor:c}]}/></View>;if(type==="gallery")return <View style={[s.gGallery,{borderColor:c}]}><View style={[s.gGalleryDot,{backgroundColor:c}]}/><View style={[s.gGalleryLine,{backgroundColor:c}]}/></View>;if(type==="reviews")return <Text style={[s.gStar,{color:c}]}>★</Text>;return <View style={s.gMore}><View style={[s.gMoreLine,{backgroundColor:c}]}/><View style={[s.gMoreLine,{backgroundColor:c}]}/><View style={[s.gMoreLine,{backgroundColor:c}]}/></View>}
function BottomNav({screen,setScreen}){const items=[["home","Home"],["bookings","Bookings"],["gallery","Gallery"],["reviews","Reviews"],["more","More"]];return <SafeAreaView style={s.navSafe}><View style={s.nav}>{items.map(([key,label])=>{const a=screen===key;return <Pressable key={key} onPress={()=>setScreen(key)} style={[s.navItem,a&&s.navActive]}><NavGlyph type={key} active={a}/><Text style={[s.navText,a&&s.navTextActive]}>{label}</Text></Pressable>})}</View></SafeAreaView>}
function Quick({code,label,onPress}){return <Pressable onPress={onPress} style={s.quick}><View style={s.quickIcon}><Text style={s.quickCode}>{code}</Text></View><Text style={s.quickLabel}>{label}</Text></Pressable>}
function PageHeader({title,onBack}){return <View style={s.pageHeader}><Pressable onPress={onBack} style={s.back}><Text style={s.backText}>‹</Text></Pressable><Text style={s.pageHeaderTitle}>{title}</Text><View style={s.back}/></View>}

function Home({go}){
 const actions=[["BK","Book Now",()=>go("booking")],["GL","Gallery",()=>go("gallery")],["★","Reviews",()=>go("reviews")],["DR","Directions",()=>open(links.directions)],["WA","WhatsApp",()=>open(links.whatsapp)],["SV","Services",()=>go("services")]];
 return <SafeAreaView style={s.safe}><StatusBar barStyle="light-content" backgroundColor={QF.bg}/><ScrollView contentContainerStyle={s.homeContent} showsVerticalScrollIndicator={false}><View style={s.homeTop}><View><Text style={s.brand}>QUINCYFADEZ</Text><Text style={s.brandSub}>PRECISION · STYLE · CONFIDENCE</Text></View><Logo small/></View><View style={s.hero}><Image source={{uri:"https://quincyfadez.com/media/gallery-replacement-01.jpg"}} style={s.heroImage}/><View style={s.heroShade}/><View style={s.heroCopy}><Text style={s.heroKicker}>PREMIUM BARBER · OXFORD</Text><Text style={s.heroTitle}>LOOK GOOD.{"\n"}FEEL CONFIDENT.</Text><Text style={s.heroText}>A clean, relaxed one-to-one appointment built around you.</Text><Pressable onPress={()=>go("booking")} style={s.heroButton}><Text style={s.heroButtonText}>BOOK NOW</Text><Text style={s.heroButtonArrow}>›</Text></Pressable></View></View><View style={s.homeSection}><Text style={s.kicker}>QUICK ACTIONS</Text><Text style={s.sectionTitle}>Everything You Need</Text></View><View style={s.quickGrid}>{actions.map(([c,l,a])=><Quick key={l} code={c} label={l} onPress={a}/>)}</View><View style={s.why}><Text style={s.kicker}>WHY CLIENTS CHOOSE US</Text><View style={s.whyRow}><View style={s.bullet}/><Text style={s.whyText}>Precision cuts with clean detail every time.</Text></View><View style={s.whyRow}><View style={s.bullet}/><Text style={s.whyText}>Premium one-to-one barber experience.</Text></View><View style={s.whyRow}><View style={s.bullet}/><Text style={s.whyText}>Simple booking, clear pricing and easy management.</Text></View></View><View style={s.servicePreview}><View style={s.previewHead}><View><Text style={s.kicker}>POPULAR SERVICES</Text><Text style={s.previewTitle}>Ready When You Are</Text></View><Pressable onPress={()=>go("services")}><Text style={s.viewAll}>VIEW ALL</Text></Pressable></View>{services.slice(0,2).map((x,i)=><Pressable key={x.name} onPress={()=>go("booking",x.name)} style={[s.previewRow,i&&s.previewBorder]}><View><Text style={s.previewName}>{x.name}</Text><Text style={s.previewMeta}>{x.duration}</Text></View><View style={s.previewRight}><Text style={s.previewPrice}>{x.price}</Text><Text style={s.chev}>›</Text></View></Pressable>)}</View></ScrollView></SafeAreaView>
}

function Services({onBack,onBook}){return <SafeAreaView style={s.safe}><StatusBar barStyle="light-content" backgroundColor={QF.bg}/><ScrollView contentContainerStyle={s.pageContent} showsVerticalScrollIndicator={false}><PageHeader title="Services" onBack={onBack}/><Text style={s.kicker}>QUINCYFADEZ SERVICES</Text><Text style={s.pageTitle}>Choose Your Cut</Text><Text style={s.pageSub}>Clear pricing, clear timing and one tap to book.</Text>{services.map(x=><View key={x.name} style={s.serviceCard}><View style={s.serviceTop}><View style={{flex:1}}><Text style={s.serviceName}>{x.name}</Text><Text style={s.serviceDuration}>{x.duration}</Text></View><Text style={s.servicePrice}>{x.price}</Text></View><Text style={s.serviceDesc}>{x.description}</Text><Pressable onPress={()=>onBook(x.name)} style={s.goldButton}><Text style={s.goldButtonText}>BOOK THIS SERVICE</Text><Text style={s.goldButtonArrow}>›</Text></Pressable></View>)}</ScrollView></SafeAreaView>}

function More({onBack,go}){
 const[profile,setProfile]=useState({});useEffect(()=>{AsyncStorage.getItem(PROFILE).then(v=>{if(v)try{setProfile(JSON.parse(v))}catch(_){}})},[]);
 const Row=({title,sub,onPress,last=false})=><Pressable onPress={onPress} style={[s.moreRow,!last&&s.moreBorder]}><View style={{flex:1}}><Text style={s.moreTitle}>{title}</Text>{sub?<Text style={s.moreSub}>{sub}</Text>:null}</View><Text style={s.chev}>›</Text></Pressable>;
 return <SafeAreaView style={s.safe}><StatusBar barStyle="light-content" backgroundColor={QF.bg}/><ScrollView contentContainerStyle={s.pageContent} showsVerticalScrollIndicator={false}><PageHeader title="Profile & More" onBack={onBack}/><View style={s.profileHero}><Logo/><View style={{flex:1}}><Text style={s.profileName}>{profile.name||"QuincyFadez Client"}</Text><Text style={s.profileMeta}>{profile.email||profile.phone||"Your QuincyFadez account"}</Text></View></View><Text style={s.groupLabel}>YOUR ACCOUNT</Text><View style={s.moreCard}><Row title="Account & Payment Methods" sub="Bookings, card protection and account tools" onPress={()=>go("account")}/><Row title="My Bookings" sub="Upcoming and past appointments" onPress={()=>go("bookings")}/><Row last title="Services" sub="Prices and appointment lengths" onPress={()=>go("services")}/></View><Text style={s.groupLabel}>QUICK LINKS</Text><View style={s.moreCard}><Row title="Share Booking Link" onPress={()=>Share.share({message:`Book QuincyFadez: ${links.website}`})}/><Row title="Location & Directions" onPress={()=>open(links.directions)}/><Row title="WhatsApp QuincyFadez" onPress={()=>open(links.whatsapp)}/><Row title="Leave A Google Review" onPress={()=>open(links.reviews)}/><Row last title="QuincyFadez Website" onPress={()=>open(links.website)}/></View></ScrollView></SafeAreaView>
}

export default function ClientLuxuryShell(){
 const[screen,setScreen]=useState("auth"),[service,setService]=useState("Haircut");
 const go=(next,sv)=>{if(sv)setService(sv);setScreen(next)};
 let body;
 if(screen==="auth")body=<AuthScreen onClient={()=>setScreen("home")} onAdmin={()=>setScreen("admin")}/>;
 else if(screen==="home")body=<Home go={go}/>;
 else if(screen==="booking")body=<BookingScreen initialService={service} onBack={()=>setScreen("home")}/>;
 else if(screen==="bookings")body=<ClientBookingsLuxury onBack={()=>setScreen("home")}/>;
 else if(screen==="gallery")body=<GalleryScreen onBack={()=>setScreen("home")} onBook={()=>go("booking","Haircut")}/>;
 else if(screen==="reviews")body=<ReviewsScreen onBack={()=>setScreen("home")}/>;
 else if(screen==="services")body=<Services onBack={()=>setScreen("home")} onBook={sv=>go("booking",sv)}/>;
 else if(screen==="more")body=<More onBack={()=>setScreen("home")} go={go}/>;
 else if(screen==="account")body=<AccountScreen onBack={()=>setScreen("more")}/>;
 else if(screen==="admin")body=<AdminNotificationsShell onExit={()=>setScreen("auth")}/>;
 else body=<Home go={go}/>;
 const nav=["home","booking","bookings","gallery","reviews","more","account"].includes(screen);
 const navScreen=screen==="booking"?"bookings":screen==="account"?"more":screen;
 return <View style={s.shell}><View style={{flex:1}}>{body}</View>{nav?<BottomNav screen={navScreen} setScreen={setScreen}/>:null}</View>
}

const s=StyleSheet.create({
 shell:{flex:1,backgroundColor:QF.bg},safe:{flex:1,backgroundColor:QF.bg},homeContent:{paddingHorizontal:17,paddingTop:8,paddingBottom:30},pageContent:{paddingHorizontal:18,paddingTop:4,paddingBottom:34},
 homeTop:{flexDirection:"row",alignItems:"center",justifyContent:"space-between",marginBottom:14},brand:{color:QF.text,fontSize:20,fontWeight:"900",letterSpacing:3.2},brandSub:{color:QF.gold,fontSize:8.5,fontWeight:"850",letterSpacing:1.3,marginTop:5},logo:{width:68,height:68,borderRadius:34,borderWidth:1.5,borderColor:QF.goldDark,backgroundColor:QF.panel2,overflow:"hidden",alignItems:"center",justifyContent:"center",...qfShadow},logoSmall:{width:50,height:50,borderRadius:25},logoImg:{width:64,height:64,borderRadius:32,resizeMode:"cover"},logoImgSmall:{width:46,height:46,borderRadius:23},
 hero:{height:385,borderRadius:26,overflow:"hidden",borderWidth:1,borderColor:QF.goldDark,backgroundColor:QF.panel,...qfCardShadow},heroImage:{...StyleSheet.absoluteFillObject,width:"100%",height:"100%"},heroShade:{...StyleSheet.absoluteFillObject,backgroundColor:"rgba(0,0,0,.35)"},heroCopy:{position:"absolute",left:15,right:15,bottom:15,borderRadius:20,borderWidth:1,borderColor:"rgba(214,189,122,.35)",backgroundColor:"rgba(5,5,5,.91)",padding:17},heroKicker:{color:QF.gold,fontSize:8.5,fontWeight:"900",letterSpacing:1},heroTitle:{color:QF.text,fontSize:29,lineHeight:31,fontWeight:"900",marginTop:7},heroText:{color:QF.text2,fontSize:12.5,lineHeight:18,marginTop:8,maxWidth:280},heroButton:{height:52,borderRadius:14,backgroundColor:QF.gold,marginTop:14,paddingHorizontal:16,flexDirection:"row",alignItems:"center",justifyContent:"space-between",...qfShadow},heroButtonText:{color:"#090806",fontSize:10.5,fontWeight:"900",letterSpacing:.7},heroButtonArrow:{color:"#090806",fontSize:26},
 kicker:{color:QF.gold,fontSize:9,fontWeight:"900",letterSpacing:1.3},homeSection:{marginTop:25,marginBottom:12},sectionTitle:{color:QF.text,fontSize:24,fontWeight:"850",marginTop:5},quickGrid:{flexDirection:"row",flexWrap:"wrap",gap:9},quick:{width:"31.6%",minHeight:110,borderRadius:18,borderWidth:1,borderColor:QF.borderSoft,backgroundColor:QF.panel,alignItems:"center",justifyContent:"center",...qfCardShadow},quickIcon:{width:45,height:45,borderRadius:23,borderWidth:1,borderColor:QF.goldDark,backgroundColor:QF.panel2,alignItems:"center",justifyContent:"center",marginBottom:8},quickCode:{color:QF.goldSoft,fontSize:12,fontWeight:"900"},quickLabel:{color:QF.text2,fontSize:9.5,fontWeight:"800"},why:{borderRadius:21,borderWidth:1,borderColor:QF.border,backgroundColor:QF.panel,padding:16,marginTop:19},whyRow:{flexDirection:"row",alignItems:"flex-start",gap:9,marginTop:10},bullet:{width:5,height:5,borderRadius:3,backgroundColor:QF.gold,marginTop:6},whyText:{color:QF.text2,fontSize:11.5,lineHeight:17,flex:1},servicePreview:{borderRadius:21,borderWidth:1,borderColor:QF.border,backgroundColor:QF.panel,padding:16,marginTop:18,...qfCardShadow},previewHead:{flexDirection:"row",alignItems:"flex-start",justifyContent:"space-between"},previewTitle:{color:QF.text,fontSize:18,fontWeight:"850",marginTop:5},viewAll:{color:QF.goldSoft,fontSize:8.5,fontWeight:"900"},previewRow:{minHeight:67,flexDirection:"row",alignItems:"center",justifyContent:"space-between"},previewBorder:{borderTopWidth:1,borderTopColor:QF.borderSoft},previewName:{color:QF.text,fontSize:14.5,fontWeight:"850"},previewMeta:{color:QF.muted,fontSize:9.5,marginTop:4},previewRight:{flexDirection:"row",alignItems:"center",gap:9},previewPrice:{color:QF.goldSoft,fontSize:17,fontWeight:"900"},chev:{color:QF.gold,fontSize:23},
 pageHeader:{minHeight:58,flexDirection:"row",alignItems:"center",justifyContent:"space-between"},back:{width:44,height:44,justifyContent:"center"},backText:{color:QF.text,fontSize:35,lineHeight:35},pageHeaderTitle:{color:QF.text,fontSize:16,fontWeight:"850"},pageTitle:{color:QF.text,fontSize:31,fontWeight:"900",marginTop:7},pageSub:{color:QF.muted,fontSize:13,lineHeight:19,marginTop:6,marginBottom:10},serviceCard:{borderRadius:21,borderWidth:1,borderColor:QF.border,backgroundColor:QF.panel,padding:16,marginTop:12,...qfCardShadow},serviceTop:{flexDirection:"row",alignItems:"flex-start",justifyContent:"space-between"},serviceName:{color:QF.text,fontSize:18,fontWeight:"900"},serviceDuration:{color:QF.gold,fontSize:9.5,fontWeight:"800",marginTop:5},servicePrice:{color:QF.goldSoft,fontSize:21,fontWeight:"900"},serviceDesc:{color:QF.muted,fontSize:12,lineHeight:18,marginTop:10},goldButton:{height:54,borderRadius:14,backgroundColor:QF.gold,marginTop:14,paddingHorizontal:15,flexDirection:"row",alignItems:"center",justifyContent:"space-between"},goldButtonText:{color:"#090806",fontSize:9.5,fontWeight:"900"},goldButtonArrow:{color:"#090806",fontSize:25},
 profileHero:{borderRadius:21,borderWidth:1,borderColor:QF.goldDark,backgroundColor:QF.panel2,flexDirection:"row",alignItems:"center",gap:14,padding:16,marginTop:12},profileName:{color:QF.text,fontSize:18,fontWeight:"900"},profileMeta:{color:QF.muted,fontSize:11,marginTop:4},groupLabel:{color:QF.gold,fontSize:9,fontWeight:"900",letterSpacing:1.2,marginTop:22,marginBottom:8},moreCard:{borderRadius:20,borderWidth:1,borderColor:QF.border,backgroundColor:QF.panel,overflow:"hidden",...qfCardShadow},moreRow:{minHeight:65,flexDirection:"row",alignItems:"center",paddingHorizontal:14,paddingVertical:10},moreBorder:{borderBottomWidth:1,borderBottomColor:QF.borderSoft},moreTitle:{color:QF.text,fontSize:13.5,fontWeight:"800"},moreSub:{color:QF.muted,fontSize:9.5,lineHeight:14,marginTop:3},
 navSafe:{backgroundColor:QF.bg,borderTopWidth:1,borderTopColor:QF.borderSoft},nav:{minHeight:72,flexDirection:"row",alignItems:"center",paddingHorizontal:7,paddingTop:6},navItem:{flex:1,minHeight:57,borderRadius:15,alignItems:"center",justifyContent:"center",gap:5},navActive:{backgroundColor:QF.panel2},navText:{color:QF.muted2,fontSize:7.7,fontWeight:"800"},navTextActive:{color:QF.goldSoft},gHome:{width:19,height:17,borderWidth:1.5,borderRadius:4,alignItems:"center",justifyContent:"center"},gHomeDot:{width:5,height:5,borderRadius:3},gCal:{width:20,height:19,borderWidth:1.4,borderRadius:4,paddingTop:5},gCalTop:{position:"absolute",top:3,left:3,right:3,height:2,borderRadius:1},gGallery:{width:20,height:18,borderRadius:4,borderWidth:1.4,overflow:"hidden"},gGalleryDot:{position:"absolute",right:3,top:3,width:4,height:4,borderRadius:2},gGalleryLine:{position:"absolute",left:3,right:3,bottom:4,height:2,transform:[{rotate:"-20deg"}]},gStar:{fontSize:18,lineHeight:19},gMore:{width:21,gap:4},gMoreLine:{width:20,height:2,borderRadius:1}
});
