import React,{useEffect,useMemo,useState}from"react";
import{ActivityIndicator,Pressable,SafeAreaView,ScrollView,StatusBar,StyleSheet,Text,View}from"react-native";
import AsyncStorage from"@react-native-async-storage/async-storage";
import{QF,qfCardShadow}from"./QuincyTheme";

const API=(process.env.EXPO_PUBLIC_API_URL||"").replace(/\/$/,"");
const KEY="quincyfadez.paymentClientKey";
const fmtDate=v=>new Date(v).toLocaleDateString("en-GB",{weekday:"short",day:"2-digit",month:"short",timeZone:"Europe/London"});
const fmtTime=v=>new Date(v).toLocaleTimeString("en-GB",{hour:"numeric",minute:"2-digit",hour12:true,timeZone:"Europe/London"}).replace(":00","");
const status=v=>String(v||"confirmed").replaceAll("_"," ").toUpperCase();
async function read(r){return r.json().catch(()=>({}))}

function Badge({value}){const p=value==="pending",bad=["cancelled","expired","no_show"].includes(value),done=value==="completed";return <View style={[s.badge,p&&s.badgePending,bad&&s.badgeBad,done&&s.badgeDone]}><Text style={[s.badgeText,p&&s.badgeTextPending,bad&&s.badgeTextBad]}>{status(value)}</Text></View>}
function Booking({item,onCancel,busy}){const d=fmtDate(item.start_at).split(" ");return <View style={s.card}><View style={s.dateBox}><Text style={s.dateWeek}>{d[0]}</Text><Text style={s.dateDay}>{d[1]}</Text><Text style={s.dateMonth}>{d[2]}</Text></View><View style={s.copy}><View style={s.top}><View style={{flex:1}}><Text style={s.time}>{fmtTime(item.start_at)}</Text><Text style={s.service}>{item.service}</Text><Text style={s.meta}>{item.duration_minutes} min · £{item.price}</Text></View><Badge value={item.status}/></View>{["pending","confirmed"].includes(item.status)?<Pressable disabled={busy} onPress={()=>onCancel(item.id)} style={s.cancel}><Text style={s.cancelText}>{busy?"CANCELLING…":item.status==="pending"?"CANCEL REQUEST":"CANCEL BOOKING"}</Text></Pressable>:null}</View></View>}

export default function ClientBookingsLuxury({onBack}){
 const[clientKey,setClientKey]=useState(""),[bookings,setBookings]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState(""),[tab,setTab]=useState("upcoming"),[busy,setBusy]=useState("");
 const request=async(path,options={})=>{if(!API)throw new Error("Booking services are unavailable.");const r=await fetch(`${API}${path}`,{...options,headers:{"Content-Type":"application/json",...(options.headers||{})}}),d=await read(r);if(!r.ok)throw new Error(typeof d.detail==="string"?d.detail:"Bookings could not be loaded.");return d};
 const refresh=async key=>{if(!key)return;setLoading(true);setError("");try{const d=await request(`/api/booking/appointments/${encodeURIComponent(key)}`);setBookings(d.bookings||[])}catch(e){setError(e.message)}finally{setLoading(false)}};
 useEffect(()=>{AsyncStorage.getItem(KEY).then(k=>{setClientKey(k||"");return refresh(k||"")}).catch(()=>{setError("Your booking account could not be opened.");setLoading(false)})},[]);
 const cancel=async id=>{if(!clientKey||busy)return;setBusy(id);try{await request(`/api/booking/appointments/${id}/cancel`,{method:"POST",body:JSON.stringify({client_key:clientKey})});await refresh(clientKey)}catch(e){setError(e.message)}finally{setBusy("")}};
 const now=Date.now();
 const upcoming=useMemo(()=>bookings.filter(x=>["pending","confirmed"].includes(x.status)&&new Date(x.start_at).getTime()>=now).sort((a,b)=>String(a.start_at).localeCompare(String(b.start_at))),[bookings]);
 const past=useMemo(()=>bookings.filter(x=>!["pending","confirmed"].includes(x.status)||new Date(x.start_at).getTime()<now).sort((a,b)=>String(b.start_at).localeCompare(String(a.start_at))),[bookings]);
 const shown=tab==="upcoming"?upcoming:past;
 return <SafeAreaView style={s.safe}><StatusBar barStyle="light-content" backgroundColor={QF.bg}/><ScrollView contentContainerStyle={s.content} showsVerticalScrollIndicator={false}><View style={s.header}><Pressable onPress={onBack} style={s.back}><Text style={s.backText}>‹</Text></Pressable><Text style={s.headerTitle}>My Bookings</Text><View style={s.back}/></View><Text style={s.kicker}>YOUR APPOINTMENTS</Text><Text style={s.title}>Bookings</Text><Text style={s.sub}>Everything upcoming and completed, all in one place.</Text><View style={s.tabs}><Pressable onPress={()=>setTab("upcoming")} style={[s.tab,tab==="upcoming"&&s.tabActive]}><Text style={[s.tabText,tab==="upcoming"&&s.tabTextActive]}>UPCOMING</Text></Pressable><Pressable onPress={()=>setTab("past")} style={[s.tab,tab==="past"&&s.tabActive]}><Text style={[s.tabText,tab==="past"&&s.tabTextActive]}>PAST</Text></Pressable></View>{loading?<View style={s.loading}><ActivityIndicator color={QF.gold}/><Text style={s.loadingText}>Loading your bookings…</Text></View>:shown.length?shown.map(x=><Booking key={x.id} item={x} onCancel={cancel} busy={busy===x.id}/>):<View style={s.empty}><Text style={s.emptyTitle}>{tab==="upcoming"?"NO UPCOMING APPOINTMENTS":"NO PAST APPOINTMENTS"}</Text><Text style={s.emptyText}>{tab==="upcoming"?"Your next booking will appear here as soon as it is requested.":"Completed and previous appointments will appear here."}</Text></View>}{error?<View style={s.error}><Text style={s.errorText}>{error}</Text></View>:null}</ScrollView></SafeAreaView>
}

const s=StyleSheet.create({safe:{flex:1,backgroundColor:QF.bg},content:{paddingHorizontal:18,paddingTop:4,paddingBottom:34},header:{minHeight:58,flexDirection:"row",alignItems:"center",justifyContent:"space-between"},back:{width:44,height:44,justifyContent:"center"},backText:{color:QF.text,fontSize:35,lineHeight:35},headerTitle:{color:QF.text,fontSize:16,fontWeight:"850"},kicker:{color:QF.gold,fontSize:9,fontWeight:"900",letterSpacing:1.3,marginTop:13},title:{color:QF.text,fontSize:31,fontWeight:"900",marginTop:6},sub:{color:QF.muted,fontSize:13,lineHeight:19,marginTop:7},tabs:{flexDirection:"row",borderRadius:16,borderWidth:1,borderColor:QF.borderSoft,backgroundColor:QF.panel,padding:4,marginTop:20,marginBottom:10},tab:{flex:1,height:44,borderRadius:12,alignItems:"center",justifyContent:"center"},tabActive:{backgroundColor:QF.panel3,borderWidth:1,borderColor:QF.goldDark},tabText:{color:QF.muted,fontSize:9,fontWeight:"900"},tabTextActive:{color:QF.goldSoft},card:{borderRadius:20,borderWidth:1,borderColor:QF.borderSoft,backgroundColor:QF.panel,marginTop:10,flexDirection:"row",overflow:"hidden",...qfCardShadow},dateBox:{width:72,backgroundColor:QF.panel2,borderRightWidth:1,borderRightColor:QF.border,alignItems:"center",justifyContent:"center",paddingVertical:14},dateWeek:{color:QF.gold,fontSize:8,fontWeight:"900",textTransform:"uppercase"},dateDay:{color:QF.text,fontSize:26,fontWeight:"900",marginTop:2},dateMonth:{color:QF.muted,fontSize:8,fontWeight:"800",textTransform:"uppercase",marginTop:1},copy:{flex:1,padding:13},top:{flexDirection:"row",gap:8},time:{color:QF.text,fontSize:15,fontWeight:"900"},service:{color:QF.text2,fontSize:12.5,fontWeight:"750",marginTop:4},meta:{color:QF.muted,fontSize:9.5,marginTop:4},badge:{borderRadius:9,borderWidth:1,borderColor:"#285A36",backgroundColor:QF.greenBg,paddingHorizontal:7,paddingVertical:5,alignSelf:"flex-start"},badgePending:{borderColor:"#6E5220",backgroundColor:QF.amberBg},badgeBad:{borderColor:"#69352E",backgroundColor:QF.redBg},badgeDone:{borderColor:QF.border,backgroundColor:QF.panel2},badgeText:{color:QF.green,fontSize:6.5,fontWeight:"900"},badgeTextPending:{color:QF.amber},badgeTextBad:{color:QF.red},cancel:{height:37,borderRadius:11,borderWidth:1,borderColor:QF.border,alignItems:"center",justifyContent:"center",marginTop:11},cancelText:{color:QF.muted,fontSize:8,fontWeight:"900"},loading:{borderRadius:18,borderWidth:1,borderColor:QF.borderSoft,backgroundColor:QF.panel,alignItems:"center",padding:22,marginTop:12},loadingText:{color:QF.muted,fontSize:11,marginTop:9},empty:{borderRadius:20,borderWidth:1,borderColor:QF.borderSoft,backgroundColor:QF.panel,padding:20,marginTop:12},emptyTitle:{color:QF.gold,fontSize:9,fontWeight:"900",letterSpacing:1},emptyText:{color:QF.muted,fontSize:12,lineHeight:18,marginTop:7},error:{borderRadius:15,borderWidth:1,borderColor:"#69352E",backgroundColor:QF.redBg,padding:12,marginTop:12},errorText:{color:QF.red,fontSize:11,lineHeight:16}});
