import React,{useEffect,useState}from"react";
import{ActivityIndicator,Image,Linking,Pressable,SafeAreaView,ScrollView,StatusBar,StyleSheet,Text,View}from"react-native";
import{M,Marble,cardShadow}from"./MockupTheme";
import{ClientHeader,ClientSection}from"./ClientLuxuryUI";

const API="https://quincyfadez.com/api/google-reviews",LEAVE="https://g.page/r/CbQwl91s8_vqEBM/review";
const stars=n=>"★".repeat(Math.round(Number(n||0))).padEnd(5,"☆");
const open=u=>u&&Linking.openURL(u).catch(()=>{});

export default function MockupReviewsScreenV2({onBack}){
 const[data,setData]=useState(null),[loading,setLoading]=useState(true),[error,setError]=useState(false);
 const load=async()=>{setLoading(true);setError(false);try{const r=await fetch(API,{cache:"no-store"});if(!r.ok)throw 0;setData(await r.json())}catch{setError(true)}finally{setLoading(false)}};
 useEffect(()=>{load()},[]);
 const list=data?.reviews||[];
 return <Marble><SafeAreaView style={s.safe}><StatusBar barStyle="light-content"/><ScrollView contentContainerStyle={s.content} showsVerticalScrollIndicator={false}>
   <ClientHeader title="Reviews" subtitle="Live Google feedback from QuincyFadez clients." onBack={onBack}/>
   {loading?<View style={s.state}><ActivityIndicator color={M.gold}/><Text style={s.stateText}>Loading Google reviews…</Text></View>:error?<View style={s.state}><Text style={s.stateIcon}>★</Text><Text style={s.stateTitle}>Reviews Temporarily Unavailable</Text><Text style={s.stateText}>The live Google review service could not be reached just now.</Text><Pressable onPress={load} style={s.retry}><Text style={s.retryText}>TRY AGAIN</Text></Pressable></View>:<>
     <View style={s.rating}><View><Text style={s.ratingLabel}>GOOGLE RATING</Text><View style={s.ratingLine}><Text style={s.ratingNumber}>{data?.rating?.toFixed?.(1)||data?.rating||"—"}</Text><Text style={s.ratingStar}>★</Text></View><Text style={s.stars}>{stars(data?.rating)}</Text><Text style={s.count}>{data?.reviewCount||0} Google reviews</Text></View><View style={s.googleBadge}><Text style={s.googleG}>G</Text><Text style={s.googleText}>LIVE</Text></View></View>
     <ClientSection title="CLIENT REVIEWS"/>
     {list.length?list.map(r=><View key={r.id} style={s.card}><View style={s.author}>{r.author?.photoUrl?<Image source={{uri:r.author.photoUrl}} style={s.avatar}/>:<View style={s.avatarFallback}><Text style={s.avatarText}>{r.author?.name?.[0]||"G"}</Text></View>}<View style={{flex:1}}><Text style={s.authorName}>{r.author?.name||"Google reviewer"}</Text><Text style={s.meta}>{r.relativeTime}</Text></View><Text style={s.cardStars}>{stars(r.rating)}</Text></View>{r.text?<Text style={s.review}>{r.text}</Text>:null}{r.sourceUrl?<Pressable onPress={()=>open(r.sourceUrl)}><Text style={s.link}>VIEW ON GOOGLE MAPS ↗</Text></Pressable>:null}</View>):<View style={s.state}><Text style={s.stateTitle}>Live Rating Connected</Text><Text style={s.stateText}>Written review comments will appear here when Google provides them.</Text></View>}
   </>}
   <View style={s.cta}><Text style={s.ctaKicker}>HAD A GREAT CUT?</Text><Text style={s.ctaTitle}>Share Your Experience.</Text><Text style={s.ctaText}>Your feedback helps new clients choose QuincyFadez with confidence.</Text><Pressable onPress={()=>open(LEAVE)} style={s.primary}><Text style={s.primaryText}>LEAVE A GOOGLE REVIEW</Text><Text style={s.primaryArrow}>›</Text></Pressable></View>
 </ScrollView></SafeAreaView></Marble>
}

const s=StyleSheet.create({safe:{flex:1},content:{paddingHorizontal:18,paddingTop:7,paddingBottom:112},state:{borderRadius:15,borderWidth:1,borderColor:M.border,backgroundColor:"rgba(16,16,15,.93)",padding:22,alignItems:"center",...cardShadow},stateIcon:{color:M.gold,fontSize:35},stateTitle:{color:M.text,fontSize:18,fontWeight:"700",textAlign:"center",marginTop:8},stateText:{color:M.muted,fontSize:11.5,lineHeight:17,textAlign:"center",marginTop:7},retry:{height:44,borderRadius:9,borderWidth:1,borderColor:M.goldDeep,paddingHorizontal:18,alignItems:"center",justifyContent:"center",marginTop:13},retryText:{color:M.goldSoft,fontSize:9,fontWeight:"900"},rating:{borderRadius:16,borderWidth:1,borderColor:"rgba(214,189,122,.30)",backgroundColor:"rgba(18,14,8,.94)",padding:18,flexDirection:"row",alignItems:"center",justifyContent:"space-between",...cardShadow},ratingLabel:{color:M.gold,fontSize:9,fontWeight:"900",letterSpacing:1},ratingLine:{flexDirection:"row",alignItems:"center",gap:8,marginTop:5},ratingNumber:{color:M.text,fontSize:42,fontWeight:"700"},ratingStar:{color:M.goldSoft,fontSize:29},stars:{color:M.goldSoft,fontSize:15,letterSpacing:1.5,marginTop:2},count:{color:M.muted,fontSize:10,marginTop:6},googleBadge:{width:66,height:66,borderRadius:18,borderWidth:1,borderColor:M.border,backgroundColor:M.panel,alignItems:"center",justifyContent:"center"},googleG:{color:M.goldSoft,fontSize:26,fontWeight:"900"},googleText:{color:M.muted,fontSize:7.5,fontWeight:"900",letterSpacing:.8,marginTop:2},card:{borderRadius:15,borderWidth:1,borderColor:"rgba(214,189,122,.22)",backgroundColor:"rgba(16,16,15,.93)",padding:15,marginBottom:10,...cardShadow},author:{flexDirection:"row",alignItems:"center",gap:10},avatar:{width:42,height:42,borderRadius:21},avatarFallback:{width:42,height:42,borderRadius:21,borderWidth:1,borderColor:M.goldDark,backgroundColor:M.panel3,alignItems:"center",justifyContent:"center"},avatarText:{color:M.goldSoft,fontWeight:"900"},authorName:{color:M.text,fontSize:12.5,fontWeight:"700"},meta:{color:M.muted,fontSize:9,marginTop:3},cardStars:{color:M.goldSoft,fontSize:9.5,letterSpacing:.5},review:{color:M.text2,fontSize:11.5,lineHeight:17,marginTop:12},link:{color:M.gold,fontSize:8,fontWeight:"900",letterSpacing:.7,marginTop:11},cta:{borderRadius:15,borderWidth:1,borderColor:"rgba(214,189,122,.24)",backgroundColor:"rgba(16,16,15,.93)",padding:16,marginTop:18,...cardShadow},ctaKicker:{color:M.gold,fontSize:9,fontWeight:"900",letterSpacing:1},ctaTitle:{color:M.text,fontSize:22,fontWeight:"700",marginTop:6},ctaText:{color:M.muted,fontSize:11.5,lineHeight:17,marginTop:7},primary:{height:52,borderRadius:10,backgroundColor:M.gold,marginTop:15,paddingHorizontal:15,flexDirection:"row",alignItems:"center",justifyContent:"space-between"},primaryText:{color:"#090704",fontSize:10,fontWeight:"900"},primaryArrow:{color:"#090704",fontSize:23}});