import React,{useCallback,useEffect,useMemo,useState}from"react";
import{ActivityIndicator,Alert,Linking,Modal,Pressable,SafeAreaView,ScrollView,Share,StatusBar,StyleSheet,Text,TextInput,View}from"react-native";
import AsyncStorage from"@react-native-async-storage/async-storage";
import{BrandLogo,GoldButton,LuxuryBackButton,M,Marble,cardShadow,shadow}from"./MockupTheme";

const API=(process.env.EXPO_PUBLIC_API_URL||"").replace(/\/$/,"");
const TOKEN="quincyfadez.adminToken";
const NAV=[["home","Dashboard","⌂"],["schedule","Schedule","▦"],["insights","Insights","▥"],["clients","Clients","◎"],["settings","More","≡"]];
const DAYS=[["0","Monday"],["1","Tuesday"],["2","Wednesday"],["3","Thursday"],["4","Friday"],["5","Saturday"],["6","Sunday"]];
const read=r=>r.json().catch(()=>({}));
const money=v=>`£${Number(v||0).toFixed(Number(v||0)%1?2:0)}`;
const dateKey=v=>String(v||"").slice(0,10);
const sortRows=a=>[...(a||[])].sort((x,y)=>String(x.start_at_utc||x.start_at||"").localeCompare(String(y.start_at_utc||y.start_at||"")));
const fmtTime=v=>v?new Date(v).toLocaleTimeString("en-GB",{hour:"numeric",minute:"2-digit",hour12:true,timeZone:"Europe/London"}).replace(":00",""):"—";
const fmtDate=v=>v?new Date(v).toLocaleDateString("en-GB",{weekday:"short",day:"numeric",month:"short",timeZone:"Europe/London"}):"—";
const greeting=()=>{const h=new Date().getHours();return h<12?"Good morning":h<18?"Good afternoon":"Good evening"};
const statusLabel=v=>String(v||"confirmed").replaceAll("_"," ").toUpperCase();
const minutesLabel=v=>{const n=Number(v||0);return n<60?`${n} Minutes`:n%60?`${Math.floor(n/60)}h ${n%60}m`:`${n/60} Hours`};

function BottomNav({tab,setTab}){
 return <SafeAreaView style={s.navSafe}><View style={s.nav}>{NAV.map(([k,l,i])=>{const active=k===tab;return <Pressable key={k} onPress={()=>setTab(k)} style={s.navItem}><View style={[s.navIconWrap,active&&s.navIconWrapOn]}><Text style={[s.navIcon,active&&s.navActive]}>{i}</Text></View><Text style={[s.navText,active&&s.navActive]}>{l}</Text></Pressable>})}</View></SafeAreaView>;
}
function Header({title,subtitle,onBack,right="☰"}){
 return <><View style={s.header}><View style={s.headerSide}>{onBack?<LuxuryBackButton onPress={onBack}/>:null}</View><Text style={s.headerTitle}>{String(title||"").toUpperCase()}</Text><View style={s.headerSide}><View style={s.headerRight}><Text style={s.headerRightText}>{right}</Text></View></View></View>{subtitle?<Text style={s.headerSub}>{subtitle}</Text>:null}</>;
}
function SectionTitle({children,action,onPress}){return <View style={s.sectionHead}><Text style={s.sectionTitle}>{children}</Text>{action?<Pressable onPress={onPress}><Text style={s.sectionAction}>{action}</Text></Pressable>:null}</View>}
function Empty({title,text}){return <View style={s.empty}><Text style={s.emptyTitle}>{title}</Text><Text style={s.emptyText}>{text}</Text></View>}
function ErrorBox({text}){return <View style={s.error}><Text style={s.errorText}>{text}</Text></View>}

function SummaryCard({label,value,icon,note,tone="neutral"}){
 return <View style={s.summaryCard}><View style={s.summaryTop}><Text style={s.summaryLabel}>{label}</Text><View style={s.summaryIconBox}><Text style={s.summaryIcon}>{icon}</Text></View></View><Text style={s.summaryValue}>{value}</Text>{note?<Text style={[s.summaryNote,tone==="good"&&s.good,tone==="warn"&&s.warn]}>{note}</Text>:null}</View>;
}
function pctNote(v,unit="vs last period"){if(v==null)return{note:"No previous data",tone:"neutral"};const n=Number(v||0);if(n>0)return{note:`+${n}% ${unit}`,tone:"good"};if(n<0)return{note:`${n}% ${unit}`,tone:"warn"};return{note:`No change ${unit}`,tone:"neutral"}}
function noShowNote(delta){const n=Number(delta||0);if(n<0)return{note:`${Math.abs(n)} fewer vs last week`,tone:"good"};if(n>0)return{note:`${n} more vs last week`,tone:"warn"};return{note:"Same as last week",tone:"neutral"}}
function repeatNote(points){if(points==null)return{note:"No previous data",tone:"neutral"};const n=Number(points||0);if(n>0)return{note:`+${n} pts vs last week`,tone:"good"};if(n<0)return{note:`${n} pts vs last week`,tone:"warn"};return{note:"Same as last week",tone:"neutral"}}
function Status({value}){const pending=value==="pending",bad=["cancelled","expired","no_show"].includes(value),done=value==="completed";return <View style={[s.status,pending&&s.statusPending,bad&&s.statusBad,done&&s.statusDone]}><Text style={[s.statusText,pending&&{color:M.amber},bad&&{color:M.red},done&&{color:M.muted}]}>{statusLabel(value)}</Text></View>}
function Appointment({x,onAction,busy,compact=false}){
 return <View style={s.appointment}><View style={s.appRow}><View style={s.timeBox}><Text style={s.time}>{fmtTime(x.start_at)}</Text>{!compact?<Text style={s.duration}>{x.duration_minutes||0} MIN</Text>:null}</View><View style={s.appInfo}><Text style={s.client}>{x.customer_name||"Client"}</Text><Text style={s.service}>{x.service||"Appointment"}</Text>{!compact?<Text style={s.appMeta}>{fmtDate(x.start_at)} · {money(x.price)}</Text>:null}</View><Status value={x.status}/></View>{x.status==="pending"&&onAction?<View style={s.requestActions}><Pressable disabled={busy} onPress={()=>onAction(x,"confirmed")} style={s.approve}><Text style={s.approveText}>APPROVE</Text></Pressable><Pressable disabled={busy} onPress={()=>onAction(x,"cancelled")} style={s.decline}><Text style={s.declineText}>DECLINE</Text></Pressable></View>:null}</View>;
}
function Toggle({value,onChange,disabled}){return <Pressable disabled={disabled} onPress={()=>onChange(!value)} style={[s.toggle,value&&s.toggleOn,disabled&&{opacity:.45}]}><View style={[s.knob,value&&s.knobOn]}/></Pressable>}
function Select({value,onPress}){return <Pressable onPress={onPress} style={s.select}><Text style={s.selectText}>{value}</Text><Text style={s.selectArrow}>⌄</Text></Pressable>}
function SettingSection({title,children}){return <View style={s.settingSection}><Text style={s.settingSectionTitle}>{title}</Text><View style={s.settingCard}>{children}</View></View>}
function SettingRow({title,subtitle,right,onPress,last=false,icon}){const row=<View style={[s.settingRow,!last&&s.settingDivider]}><View style={s.settingLeft}>{icon?<View style={s.settingIconBox}><Text style={s.settingIcon}>{icon}</Text></View>:null}<View style={{flex:1}}><Text style={s.settingTitle}>{title}</Text>{subtitle?<Text style={s.settingSub}>{subtitle}</Text>:null}</View></View>{right||<Text style={s.chev}>›</Text>}</View>;return onPress?<Pressable onPress={onPress}>{row}</Pressable>:row}

function WorkingHours({hours,saving,onSave}){
 const[draft,setDraft]=useState(hours||{});useEffect(()=>setDraft(hours||{}),[hours]);
 const toggle=k=>setDraft(d=>({...d,[k]:(d[k]||[]).length?[]:[["09:00","18:00"]]}));
 const change=(k,i,j,v)=>setDraft(d=>{const rows=[...(d[k]||[])],row=[...(rows[i]||["09:00","18:00"])];row[j]=v;rows[i]=row;return{...d,[k]:rows}});
 const add=k=>setDraft(d=>({...d,[k]:[...(d[k]||[]),["18:00","20:00"]]}));
 const remove=(k,i)=>setDraft(d=>({...d,[k]:(d[k]||[]).filter((_,x)=>x!==i)}));
 return <SettingSection title="WORKING HOURS">{DAYS.map(([k,name],di)=>{const rows=draft[k]||[],open=rows.length>0;return <View key={k} style={[s.hoursDay,di<DAYS.length-1&&s.settingDivider]}><View style={s.hoursTop}><View><Text style={s.settingTitle}>{name}</Text><Text style={s.hoursState}>{open?"OPEN":"CLOSED"}</Text></View><Toggle value={open} onChange={()=>toggle(k)} disabled={saving}/></View>{rows.map((r,i)=><View key={`${k}-${i}`} style={s.shift}><TextInput value={r[0]} onChangeText={v=>change(k,i,0,v)} maxLength={5} keyboardType="numbers-and-punctuation" style={s.timeInput}/><Text style={s.dash}>—</Text><TextInput value={r[1]} onChangeText={v=>change(k,i,1,v)} maxLength={5} keyboardType="numbers-and-punctuation" style={s.timeInput}/>{rows.length>1?<Pressable onPress={()=>remove(k,i)} style={s.removeShift}><Text style={s.removeShiftText}>×</Text></Pressable>:null}</View>)}{open?<Pressable onPress={()=>add(k)}><Text style={s.addShift}>+ ADD SPLIT SHIFT</Text></Pressable>:null}</View>})}<View style={s.hoursSave}><GoldButton title={saving?"SAVING…":"SAVE WORKING HOURS"} onPress={()=>onSave(draft)} disabled={saving}/></View></SettingSection>;
}

function BusinessModal({type,settings,services,saving,onClose,onSave}){
 const profile=settings?.business_profile||{},[draft,setDraft]=useState({});
 useEffect(()=>{if(type==="profile")setDraft({business_name:profile.business_name||"QuincyFadez",owner_name:profile.owner_name||"",phone:profile.phone||"",email:profile.email||""});if(type==="location")setDraft({address:profile.address||"",city:profile.city||"Oxford",postcode:profile.postcode||"",maps_url:profile.maps_url||""})},[type]);
 if(!type)return null;
 const Field=({label,k,keyboardType})=><View style={s.modalField}><Text style={s.modalLabel}>{label}</Text><TextInput value={draft[k]||""} onChangeText={v=>setDraft(d=>({...d,[k]:v}))} keyboardType={keyboardType} placeholderTextColor={M.muted2} style={s.modalInput}/></View>;
 const save=async()=>{await onSave({business_profile:{...profile,...draft}});onClose()};
 return <Modal visible animationType="slide" onRequestClose={onClose}><Marble><SafeAreaView style={s.safe}><StatusBar barStyle="light-content"/><View style={s.modalHeader}><Header title={type==="profile"?"Profile":type==="location"?"Location":"Services"} onBack={onClose}/></View><ScrollView contentContainerStyle={s.modalContent}>{type==="profile"?<><Field label="BUSINESS NAME" k="business_name"/><Field label="OWNER NAME" k="owner_name"/><Field label="PHONE" k="phone" keyboardType="phone-pad"/><Field label="EMAIL" k="email" keyboardType="email-address"/><GoldButton title={saving?"SAVING…":"SAVE PROFILE"} onPress={save} disabled={saving} style={{marginTop:18}}/></>:null}{type==="location"?<><Field label="ADDRESS" k="address"/><Field label="CITY" k="city"/><Field label="POSTCODE" k="postcode"/><Field label="GOOGLE MAPS URL" k="maps_url"/><GoldButton title={saving?"SAVING…":"SAVE LOCATION"} onPress={save} disabled={saving} style={{marginTop:18}}/>{profile.maps_url?<Pressable onPress={()=>Linking.openURL(profile.maps_url).catch(()=>{})} style={s.outline}><Text style={s.outlineText}>OPEN DIRECTIONS</Text></Pressable>:null}</>:null}{type==="services"?<><Text style={s.modalIntro}>These are the live services available to clients.</Text>{(services||[]).map(x=><View key={x.name} style={s.serviceModal}><BrandLogo size={42} compact/><View style={{flex:1,marginLeft:11}}><Text style={s.serviceModalName}>{x.name}</Text><Text style={s.serviceModalMeta}>{x.duration_minutes||x.duration||"—"} min</Text></View><Text style={s.serviceModalPrice}>{money(x.price)}</Text></View>)}</>:null}</ScrollView></SafeAreaView></Marble></Modal>;
}

export default function MockupAdminScreenV5({onExit}){
 const[token,setToken]=useState(""),[checking,setChecking]=useState(true),[tab,setTab]=useState("home"),[overview,setOverview]=useState(null),[requests,setRequests]=useState([]),[bookings,setBookings]=useState([]),[settings,setSettings]=useState(null),[services,setServices]=useState([]),[week,setWeek]=useState(null),[month,setMonth]=useState(null),[clients,setClients]=useState([]),[search,setSearch]=useState(""),[selectedDate,setSelectedDate]=useState(""),[loading,setLoading]=useState(false),[saving,setSaving]=useState(false),[busy,setBusy]=useState(""),[error,setError]=useState(""),[picker,setPicker]=useState(null),[detail,setDetail]=useState("");
 useEffect(()=>{AsyncStorage.getItem(TOKEN).then(v=>{setToken(v||"");setChecking(false)}).catch(()=>setChecking(false))},[]);
 const request=useCallback(async(path,opt={})=>{if(!token||!API)throw new Error("Admin connection is unavailable.");const r=await fetch(`${API}${path}`,{...opt,headers:{"Content-Type":"application/json",Authorization:`Bearer ${token}`,...(opt.headers||{})}}),d=await read(r);if(r.status===401){await AsyncStorage.removeItem(TOKEN);setToken("");onExit?.();throw new Error("Your owner session expired.")}if(!r.ok)throw new Error(typeof d.detail==="string"?d.detail:"That action could not be completed.");return d},[token,onExit]);
 const loadHome=useCallback(async()=>{const[o,r]=await Promise.all([request("/api/admin/overview"),request("/api/admin/booking-requests")]);o.appointments=sortRows(o.appointments||[]);setOverview(o);setRequests(sortRows(r.bookings||[]))},[request]);
 const loadSchedule=useCallback(async()=>{const[b,st]=await Promise.all([request("/api/admin/bookings?days=31"),request("/api/admin/settings")]);const list=sortRows(b.bookings||[]);setBookings(list);setSettings(st.settings||null);setServices(st.services||[]);setSelectedDate(v=>v||dateKey(list[0]?.start_at)||new Date().toISOString().slice(0,10))},[request]);
 const loadInsights=useCallback(async()=>{const[w,m]=await Promise.all([request("/api/admin/insights-v2?period=week"),request("/api/admin/insights-v2?period=month")]);setWeek(w);setMonth(m)},[request]);
 const loadSettings=useCallback(async()=>{const d=await request("/api/admin/settings");setSettings(d.settings||null);setServices(d.services||[])},[request]);
 const load=useCallback(async()=>{if(!token)return;setLoading(true);setError("");try{if(tab==="home")await loadHome();else if(tab==="schedule")await loadSchedule();else if(tab==="insights")await loadInsights();else if(tab==="clients")setClients((await request("/api/admin/clients")).clients||[]);else await loadSettings()}catch(e){setError(e.message)}finally{setLoading(false)}},[token,tab,loadHome,loadSchedule,loadInsights,loadSettings,request]);
 useEffect(()=>{load()},[load]);
 const saveSettings=useCallback(async patch=>{if(saving)return false;setSaving(true);setError("");try{const d=await request("/api/admin/settings",{method:"PUT",body:JSON.stringify(patch)});setSettings(d.settings||settings);return true}catch(e){setError(e.message);return false}finally{setSaving(false)}},[saving,request,settings]);
 const automation=(key,enabled)=>saveSettings({automations:{[key]:{...(settings?.automations?.[key]||{}),enabled}}});
 const updateStatus=async(x,next)=>{if(busy)return;const run=async()=>{setBusy(x.id);try{await request(`/api/admin/bookings/${x.id}/status`,{method:"PATCH",body:JSON.stringify({status:next})});await(tab==="home"?loadHome():loadSchedule())}catch(e){setError(e.message)}finally{setBusy("")}};if(next==="cancelled")return Alert.alert("Decline booking?","This releases the appointment slot.",[{text:"Keep",style:"cancel"},{text:"Decline",style:"destructive",onPress:run}]);await run()};
 const choose=(title,value,options,key)=>setPicker({title,value,options,key});
 const chooseValue=v=>{if(!picker)return;saveSettings({[picker.key]:v});setPicker(null)};
 const logout=async()=>{try{await fetch(`${API}/api/admin/logout`,{method:"POST",headers:{Authorization:`Bearer ${token}`}})}catch(_){}await AsyncStorage.removeItem(TOKEN);onExit?.()};
 const grouped=useMemo(()=>{const g={};bookings.forEach(x=>{const k=dateKey(x.start_at);(g[k]||(g[k]=[])).push(x)});return Object.entries(g).sort(([a],[b])=>a.localeCompare(b))},[bookings]);
 const dates=grouped.slice(0,7).map(([k])=>k),shown=bookings.filter(x=>dateKey(x.start_at)===selectedDate);
 const filtered=useMemo(()=>{const q=search.trim().toLowerCase();return q?clients.filter(c=>[c.name,c.phone,c.email].some(v=>String(v||"").toLowerCase().includes(q))):clients},[clients,search]);
 if(checking)return <Marble><View style={s.center}><ActivityIndicator color={M.gold}/></View></Marble>;
 if(!token)return null;
 let page;
 if(tab==="home")page=<ScrollView contentContainerStyle={s.content} showsVerticalScrollIndicator={false}><View style={s.dashboardTop}><Pressable onPress={()=>setTab("settings")} style={s.dashSide}><Text style={s.dashGlyph}>☰</Text></Pressable><View style={s.brandWrap}><BrandLogo size={70} compact/><Text style={s.brand}>QUINCYFADEZ</Text></View><Pressable onPress={()=>requests.length&&setTab("home")} style={s.dashSide}><Text style={s.dashGlyph}>◉</Text>{requests.length?<View style={s.badge}><Text style={s.badgeText}>{Math.min(requests.length,9)}</Text></View>:null}</Pressable></View><Text style={s.greeting}>{greeting()}, Quincy</Text><Text style={s.greetingSub}>Here’s what’s happening today.</Text><View style={s.grid}><SummaryCard label="TODAY’S BOOKINGS" value={overview?.today_bookings??0} icon="▦" note="Live schedule"/><SummaryCard label="TODAY’S REVENUE" value={money(overview?.today_revenue)} icon="£" note="Completed value"/><SummaryCard label="PENDING REQUESTS" value={requests.length} icon="◷" note={requests.length?"Ready to review":"All caught up"}/><SummaryCard label="UTILISATION" value={overview?.utilisation_percent==null?"—":`${overview.utilisation_percent}%`} icon="↗" note="Today’s capacity"/></View><SectionTitle action="View all" onPress={()=>setTab("schedule")}>UPCOMING APPOINTMENTS</SectionTitle>{(overview?.appointments||[]).length?overview.appointments.slice(0,6).map(x=><Appointment key={x.id} x={x} compact/>):<Empty title="NO BOOKINGS TODAY" text="Today’s appointments will appear here in time order."/>}{requests.length?<><SectionTitle>BOOKING REQUESTS</SectionTitle>{requests.slice(0,4).map(x=><Appointment key={x.id} x={x} onAction={updateStatus} busy={busy===x.id}/>)}</>:null}{error?<ErrorBox text={error}/>:null}</ScrollView>;
 else if(tab==="schedule")page=<ScrollView contentContainerStyle={s.content} showsVerticalScrollIndicator={false}><Header title="Schedule" subtitle="Daily schedule at a glance. Clear, chronological and easy." onBack={()=>setTab("home")}/><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.dateStrip}>{dates.length?dates.map(k=>{const d=new Date(`${k}T12:00:00`),active=k===selectedDate;return <Pressable key={k} onPress={()=>setSelectedDate(k)} style={[s.dateChip,active&&s.dateChipOn]}><Text style={[s.dateWeek,active&&s.dateOnText]}>{d.toLocaleDateString("en-GB",{weekday:"short"})}</Text><Text style={[s.dateNum,active&&s.dateOnText]}>{d.getDate()}</Text></Pressable>}):<Text style={s.muted}>No appointments yet.</Text>}</ScrollView><Text style={s.dateHeading}>{selectedDate?new Date(`${selectedDate}T12:00:00`).toLocaleDateString("en-GB",{weekday:"long",day:"numeric",month:"long",year:"numeric"}).toUpperCase():"SCHEDULE"}</Text>{shown.length?shown.map(x=><Appointment key={x.id} x={x}/>):<Empty title="NO APPOINTMENTS" text="There are no bookings on this date."/>}{error?<ErrorBox text={error}/>:null}</ScrollView>;
 else if(tab==="insights"){const rc=pctNote(week?.changes?.revenue_percent,"vs last week"),bc=pctNote(week?.changes?.bookings_percent,"vs last week"),rr=repeatNote(week?.changes?.repeat_clients_percent_points),ns=noShowNote(week?.changes?.no_shows_delta),nc=pctNote(month?.changes?.new_clients_percent,"vs last month"),av=pctNote(month?.changes?.average_booking_value_percent,"vs last month"),top=(week?.service_breakdown||[]).slice(0,3),peaks=(week?.peak_hours||[]).slice(0,3),maxPeak=Math.max(1,...peaks.map(x=>Number(x.bookings||0)));page=<ScrollView contentContainerStyle={s.content} showsVerticalScrollIndicator={false}><Header title="Insights" subtitle="Business performance at a glance." onBack={()=>setTab("home")}/><View style={s.grid}><SummaryCard label="THIS WEEK’S REVENUE" value={money(week?.revenue)} icon="£" note={rc.note} tone={rc.tone}/><SummaryCard label="BOOKINGS THIS WEEK" value={week?.bookings??0} icon="▦" note={bc.note} tone={bc.tone}/><SummaryCard label="REPEAT CLIENTS" value={`${week?.repeat_clients_percent??0}%`} icon="⟳" note={rr.note} tone={rr.tone}/><SummaryCard label="NO-SHOWS" value={week?.no_shows??0} icon="⊗" note={ns.note} tone={ns.tone}/></View><SectionTitle>TOP SERVICES</SectionTitle><View style={s.listCard}>{top.length?top.map((x,i)=><View key={x.name} style={[s.serviceRank,i<top.length-1&&s.listDivider]}><View style={s.rank}><Text style={s.rankText}>{i+1}</Text></View><View style={{flex:1}}><Text style={s.rankName}>{x.name}</Text><Text style={s.rankMeta}>{x.bookings} booking{x.bookings===1?"":"s"}</Text></View><Text style={s.rankRevenue}>{money(x.revenue)}</Text><Text style={s.goldChev}>›</Text></View>):<Empty title="NO SERVICE DATA YET" text="Complete appointments to build your service rankings."/>}</View><SectionTitle>PEAK HOURS</SectionTitle><View style={s.listCard}>{peaks.length?peaks.map((x,i)=>{const bars=Math.max(1,Math.round((Number(x.bookings||0)/maxPeak)*8));return <View key={x.label} style={[s.peakRow,i<peaks.length-1&&s.listDivider]}><Text style={s.clock}>◷</Text><Text style={s.peakLabel}>{x.label}</Text><View style={s.bars}>{Array.from({length:8}).map((_,b)=><View key={b} style={[s.bar,b<bars&&s.barOn]}/>)}</View><Text style={s.peakCount}>{x.bookings} bookings</Text></View>}):<Empty title="NO PEAK HOURS YET" text="Bookings will build your busiest-time insights automatically."/>}</View><SectionTitle>CLIENT INSIGHTS</SectionTitle><View style={s.gridNoTop}><SummaryCard label="NEW CLIENTS THIS MONTH" value={month?.new_clients??0} icon="+" note={nc.note} tone={nc.tone}/><SummaryCard label="AVERAGE SPEND" value={money(month?.average_booking_value)} icon="↗" note={av.note} tone={av.tone}/></View>{error?<ErrorBox text={error}/>:null}</ScrollView>}
 else if(tab==="clients")page=<ScrollView contentContainerStyle={s.content} showsVerticalScrollIndicator={false} keyboardShouldPersistTaps="handled"><Header title="Clients" subtitle="Your client book, organised and easy to manage." onBack={()=>setTab("home")}/><View style={s.searchWrap}><Text style={s.searchIcon}>⌕</Text><TextInput value={search} onChangeText={setSearch} placeholder="Search clients" placeholderTextColor={M.muted2} style={s.search}/></View><SectionTitle>{filtered.length} CLIENT{filtered.length===1?"":"S"}</SectionTitle>{filtered.length?filtered.map(c=><View key={c.client_key||c.email||c.phone} style={s.clientCard}><BrandLogo size={46} compact/><View style={{flex:1}}><Text style={s.clientName}>{c.name||"Client"}</Text><Text style={s.clientMeta}>{c.phone||c.email||"No contact detail"}</Text><Text style={s.clientMeta}>{c.completed_count||0} visits · {money(c.total_spend)} spend</Text></View>{c.regular?<View style={s.regular}><Text style={s.regularText}>REGULAR</Text></View>:<Text style={s.goldChev}>›</Text>}</View>):<Empty title="NO CLIENTS YET" text="Client profiles build automatically from real bookings."/>}{error?<ErrorBox text={error}/>:null}</ScrollView>;
 else page=<ScrollView contentContainerStyle={s.content} showsVerticalScrollIndicator={false}><Header title="Settings" subtitle="Powerful settings. Simple controls, total control." onBack={()=>setTab("home")}/><SettingSection title="BOOKING OPTIONS"><SettingRow title="Minimum Notice" right={<Select value={minutesLabel(settings?.minimum_notice_minutes||120)} onPress={()=>choose("Minimum Notice",settings?.minimum_notice_minutes||120,[0,60,120,240,720,1440],"minimum_notice_minutes")}/>}/><SettingRow title="Slot Frequency" right={<Select value={`${settings?.slot_interval_minutes||15} Minutes`} onPress={()=>choose("Slot Frequency",settings?.slot_interval_minutes||15,[10,15,20,30,45,60],"slot_interval_minutes")}/>}/><SettingRow title="Cancellation Notice" right={<Select value={`${settings?.cancellation_notice_hours||24} Hours`} onPress={()=>choose("Cancellation Notice",settings?.cancellation_notice_hours||24,[0,2,6,12,24,48,72],"cancellation_notice_hours")}/>}/><SettingRow title="Booking Reminder" right={<Toggle value={!!settings?.automations?.booking_reminder?.enabled} onChange={v=>automation("booking_reminder",v)}/>}/><SettingRow title="Booking Confirmed" right={<Toggle value={!!settings?.automations?.booking_confirmed?.enabled} onChange={v=>automation("booking_confirmed",v)}/>}/><SettingRow title="Rescheduled" right={<Toggle value={!!settings?.automations?.rescheduled_booking?.enabled} onChange={v=>automation("rescheduled_booking",v)}/>}/><SettingRow title="Leave A Review" right={<Toggle value={!!settings?.automations?.leave_a_review?.enabled} onChange={v=>automation("leave_a_review",v)}/>}/><SettingRow title="Waitlist Alerts" last right={<Toggle value={!!settings?.automations?.waiting_list_alert?.enabled} onChange={v=>automation("waiting_list_alert",v)}/>} /></SettingSection><SettingSection title="SHARE & MANAGE"><SettingRow title="Share Booking Link" subtitle="Send the QuincyFadez booking page" icon="↗" last onPress={()=>Share.share({message:"Book QuincyFadez: https://quincyfadez.com"})}/></SettingSection><SettingSection title="BUSINESS"><SettingRow title="Profile" subtitle="Business and owner details" icon="◎" onPress={()=>setDetail("profile")}/><SettingRow title="Services" subtitle="Live client services and pricing" icon="✂" onPress={()=>setDetail("services")}/><SettingRow title="Location" subtitle="Address and Google Maps link" icon="⌖" last onPress={()=>setDetail("location")}/></SettingSection><WorkingHours hours={settings?.weekly_hours||{}} saving={saving} onSave={v=>saveSettings({weekly_hours:v})}/><Pressable onPress={logout} style={s.logout}><Text style={s.logoutText}>LOG OUT</Text></Pressable>{saving?<Text style={s.saving}>Saving changes…</Text>:null}{error?<ErrorBox text={error}/>:null}</ScrollView>;
 return <Marble><View style={s.shell}><SafeAreaView style={s.safe}><StatusBar barStyle="light-content"/><View style={{flex:1}}>{loading&&!overview&&!settings&&!week&&!bookings.length?<View style={s.center}><ActivityIndicator color={M.gold}/></View>:page}</View><BottomNav tab={tab} setTab={setTab}/></SafeAreaView>{picker?<Modal transparent visible animationType="fade" onRequestClose={()=>setPicker(null)}><Pressable onPress={()=>setPicker(null)} style={s.backdrop}><Pressable onPress={()=>{}} style={s.sheet}><View style={s.handle}/><Text style={s.sheetKicker}>CHOOSE A VALUE</Text><Text style={s.sheetTitle}>{picker.title}</Text>{picker.options.map(v=>{const active=String(v)===String(picker.value),label=picker.key.includes("minutes")?minutesLabel(v):picker.key.includes("hours")?`${v} Hours`:String(v);return <Pressable key={String(v)} onPress={()=>chooseValue(v)} style={[s.option,active&&s.optionOn]}><Text style={[s.optionText,active&&s.optionTextOn]}>{label}</Text>{active?<Text style={s.check}>✓</Text>:null}</Pressable>})}</Pressable></Pressable></Modal>:null}<BusinessModal type={detail} settings={settings} services={services} saving={saving} onClose={()=>setDetail("")} onSave={saveSettings}/></View></Marble>;
}

const s=StyleSheet.create({
 shell:{flex:1},safe:{flex:1},center:{flex:1,alignItems:"center",justifyContent:"center"},content:{paddingHorizontal:18,paddingTop:8,paddingBottom:112},
 header:{height:74,flexDirection:"row",alignItems:"center",justifyContent:"space-between"},headerSide:{width:50,height:50,alignItems:"center",justifyContent:"center"},headerRight:{width:42,height:42,borderRadius:13,borderWidth:1,borderColor:"rgba(214,189,122,.16)",backgroundColor:"rgba(11,11,10,.72)",alignItems:"center",justifyContent:"center"},headerRightText:{color:M.goldSoft,fontSize:17},headerTitle:{flex:1,color:M.text,fontSize:20,fontWeight:"700",letterSpacing:2.05,textAlign:"center"},headerSub:{color:M.muted,textAlign:"center",fontSize:12,lineHeight:18,marginTop:-2,marginBottom:18,paddingHorizontal:24},
 dashboardTop:{minHeight:100,flexDirection:"row",alignItems:"center",justifyContent:"space-between"},dashSide:{width:42,height:42,borderRadius:13,borderWidth:1,borderColor:"rgba(214,189,122,.16)",backgroundColor:"rgba(11,11,10,.72)",alignItems:"center",justifyContent:"center"},dashGlyph:{color:M.goldSoft,fontSize:18},brandWrap:{alignItems:"center"},brand:{color:M.goldSoft,fontSize:8.5,fontWeight:"800",letterSpacing:2.5,marginTop:5},badge:{position:"absolute",top:-4,right:-4,minWidth:18,height:18,borderRadius:9,backgroundColor:M.gold,borderWidth:1,borderColor:M.goldBright,alignItems:"center",justifyContent:"center"},badgeText:{color:"#090704",fontSize:8,fontWeight:"900"},greeting:{color:M.text,fontSize:26,fontWeight:"700",marginTop:10},greetingSub:{color:M.muted,fontSize:12.5,lineHeight:18,marginTop:5},
 grid:{flexDirection:"row",flexWrap:"wrap",gap:10,marginTop:22},gridNoTop:{flexDirection:"row",flexWrap:"wrap",gap:10},summaryCard:{width:"48.5%",minHeight:138,borderRadius:16,borderWidth:1,borderColor:"rgba(214,189,122,.13)",backgroundColor:"rgba(11,11,10,.90)",padding:14,...cardShadow},summaryTop:{flexDirection:"row",alignItems:"flex-start",justifyContent:"space-between",gap:8},summaryLabel:{flex:1,color:M.text2,fontSize:8.5,fontWeight:"800",letterSpacing:.65,lineHeight:12},summaryIconBox:{width:34,height:34,borderRadius:10,borderWidth:1,borderColor:"rgba(214,189,122,.14)",backgroundColor:"rgba(18,16,12,.60)",alignItems:"center",justifyContent:"center"},summaryIcon:{color:M.goldSoft,fontSize:16,fontWeight:"700"},summaryValue:{color:M.text,fontSize:28,fontWeight:"650",marginTop:13},summaryNote:{color:M.muted,fontSize:9.5,marginTop:8},good:{color:M.green},warn:{color:M.amber},
 sectionHead:{flexDirection:"row",alignItems:"center",justifyContent:"space-between",marginTop:27,marginBottom:10},sectionTitle:{color:M.text2,fontSize:11.5,fontWeight:"800",letterSpacing:1.15},sectionAction:{color:M.goldSoft,fontSize:10.5,fontWeight:"700"},
 appointment:{borderRadius:16,borderWidth:1,borderColor:"rgba(214,189,122,.13)",backgroundColor:"rgba(11,11,10,.90)",marginBottom:10,overflow:"hidden",...cardShadow},appRow:{minHeight:86,flexDirection:"row",alignItems:"center"},timeBox:{width:88,alignSelf:"stretch",alignItems:"center",justifyContent:"center",borderRightWidth:1,borderRightColor:"rgba(255,255,255,.052)"},time:{color:M.goldSoft,fontSize:16,fontWeight:"700"},duration:{color:M.muted,fontSize:8,marginTop:4},appInfo:{flex:1,paddingHorizontal:13},client:{color:M.text,fontSize:13.5,fontWeight:"700"},service:{color:M.text2,fontSize:10.5,marginTop:4},appMeta:{color:M.muted,fontSize:8.8,marginTop:4},status:{marginRight:10,borderRadius:8,borderWidth:1,borderColor:"rgba(104,201,135,.28)",backgroundColor:M.greenBg,paddingHorizontal:7,paddingVertical:5},statusText:{color:M.green,fontSize:6.8,fontWeight:"900",letterSpacing:.35},statusPending:{borderColor:"rgba(213,181,109,.30)",backgroundColor:M.amberBg},statusBad:{borderColor:"rgba(217,139,130,.28)",backgroundColor:M.redBg},statusDone:{borderColor:"rgba(214,189,122,.10)",backgroundColor:M.panel2},requestActions:{flexDirection:"row",gap:8,padding:10,borderTopWidth:1,borderTopColor:"rgba(255,255,255,.052)"},approve:{flex:1,minHeight:40,borderRadius:10,backgroundColor:M.gold,borderWidth:1,borderColor:"rgba(241,221,162,.62)",alignItems:"center",justifyContent:"center"},approveText:{color:"#090704",fontSize:8.5,fontWeight:"900",letterSpacing:.7},decline:{flex:1,minHeight:40,borderRadius:10,borderWidth:1,borderColor:"rgba(217,139,130,.20)",backgroundColor:"rgba(10,10,9,.22)",alignItems:"center",justifyContent:"center"},declineText:{color:M.red,fontSize:8.5,fontWeight:"900",letterSpacing:.7},
 dateStrip:{gap:8,paddingVertical:4,paddingRight:20},dateChip:{width:60,height:70,borderRadius:12,borderWidth:1,borderColor:"rgba(214,189,122,.12)",backgroundColor:"rgba(12,12,11,.88)",alignItems:"center",justifyContent:"center"},dateChipOn:{backgroundColor:M.gold,borderColor:"rgba(241,221,162,.64)",...shadow},dateWeek:{color:M.muted,fontSize:9,fontWeight:"800",textTransform:"uppercase"},dateNum:{color:M.text,fontSize:19,fontWeight:"700",marginTop:4},dateOnText:{color:"#090704"},dateHeading:{color:M.text2,fontSize:11,fontWeight:"800",letterSpacing:.8,marginTop:23,marginBottom:11},muted:{color:M.muted},
 listCard:{borderRadius:16,borderWidth:1,borderColor:"rgba(214,189,122,.13)",backgroundColor:"rgba(11,11,10,.90)",overflow:"hidden",...cardShadow},listDivider:{borderBottomWidth:1,borderBottomColor:"rgba(255,255,255,.052)"},serviceRank:{minHeight:76,paddingHorizontal:13,flexDirection:"row",alignItems:"center",gap:11},rank:{width:34,height:34,borderRadius:11,borderWidth:1,borderColor:"rgba(214,189,122,.18)",backgroundColor:"rgba(18,16,12,.62)",alignItems:"center",justifyContent:"center"},rankText:{color:M.goldSoft,fontSize:12,fontWeight:"800"},rankName:{color:M.text,fontSize:13.5,fontWeight:"700"},rankMeta:{color:M.muted,fontSize:9.5,marginTop:3},rankRevenue:{color:M.goldSoft,fontSize:14,fontWeight:"700"},goldChev:{color:M.goldSoft,fontSize:22},peakRow:{minHeight:62,paddingHorizontal:13,flexDirection:"row",alignItems:"center",gap:9},clock:{color:M.goldSoft,fontSize:17},peakLabel:{color:M.text2,fontSize:10.5,width:82},bars:{flex:1,flexDirection:"row",gap:3,alignItems:"center"},bar:{width:5,height:18,borderRadius:2,backgroundColor:"rgba(214,189,122,.08)"},barOn:{backgroundColor:M.gold},peakCount:{color:M.muted,fontSize:8.8,width:58,textAlign:"right"},
 searchWrap:{height:54,borderRadius:12,borderWidth:1,borderColor:"rgba(214,189,122,.13)",backgroundColor:"rgba(11,11,10,.90)",flexDirection:"row",alignItems:"center",paddingHorizontal:13,...cardShadow},searchIcon:{color:M.goldSoft,fontSize:17,width:28},search:{flex:1,color:M.text,fontSize:13},clientCard:{minHeight:82,borderRadius:16,borderWidth:1,borderColor:"rgba(214,189,122,.13)",backgroundColor:"rgba(11,11,10,.90)",padding:12,flexDirection:"row",alignItems:"center",gap:12,marginBottom:9,...cardShadow},clientName:{color:M.text,fontSize:13.5,fontWeight:"700"},clientMeta:{color:M.muted,fontSize:9.2,marginTop:3},regular:{borderRadius:8,borderWidth:1,borderColor:"rgba(104,201,135,.26)",backgroundColor:M.greenBg,paddingHorizontal:7,paddingVertical:5},regularText:{color:M.green,fontSize:7,fontWeight:"900"},
 settingSection:{marginTop:22},settingSectionTitle:{color:M.goldSoft,fontSize:9,fontWeight:"900",letterSpacing:1.2,marginBottom:9},settingCard:{borderRadius:17,borderWidth:1,borderColor:"rgba(214,189,122,.13)",backgroundColor:"rgba(11,11,10,.90)",overflow:"hidden",...cardShadow},settingRow:{minHeight:72,paddingHorizontal:14,flexDirection:"row",alignItems:"center",justifyContent:"space-between"},settingDivider:{borderBottomWidth:1,borderBottomColor:"rgba(255,255,255,.052)"},settingLeft:{flex:1,flexDirection:"row",alignItems:"center",gap:11},settingIconBox:{width:40,height:40,borderRadius:12,borderWidth:1,borderColor:"rgba(214,189,122,.15)",backgroundColor:"rgba(18,16,12,.60)",alignItems:"center",justifyContent:"center"},settingIcon:{color:M.goldSoft,fontSize:16},settingTitle:{color:M.text,fontSize:13,fontWeight:"700"},settingSub:{color:M.muted,fontSize:9.2,lineHeight:13,marginTop:3},chev:{color:M.goldSoft,fontSize:22},select:{minWidth:116,height:40,borderRadius:10,borderWidth:1,borderColor:"rgba(214,189,122,.14)",backgroundColor:"rgba(5,5,5,.62)",paddingHorizontal:10,flexDirection:"row",alignItems:"center",justifyContent:"space-between",gap:8},selectText:{color:M.text2,fontSize:10.5,fontWeight:"600"},selectArrow:{color:M.goldSoft,fontSize:15},toggle:{width:50,height:28,borderRadius:14,borderWidth:1,borderColor:"rgba(214,189,122,.10)",backgroundColor:"#24221E",padding:3,justifyContent:"center"},toggleOn:{backgroundColor:M.gold,borderColor:"rgba(241,221,162,.54)"},knob:{width:20,height:20,borderRadius:10,backgroundColor:"#8C8981"},knobOn:{alignSelf:"flex-end",backgroundColor:"#F7F5EF"},
 hoursDay:{padding:14},hoursTop:{flexDirection:"row",alignItems:"center",justifyContent:"space-between"},hoursState:{color:M.goldSoft,fontSize:7.5,fontWeight:"900",letterSpacing:.6,marginTop:4},shift:{flexDirection:"row",alignItems:"center",gap:8,marginTop:11},timeInput:{flex:1,height:44,borderRadius:10,borderWidth:1,borderColor:"rgba(214,189,122,.12)",backgroundColor:"rgba(5,5,5,.66)",color:M.text,textAlign:"center",fontSize:11},dash:{color:M.muted},removeShift:{width:35,height:44,borderRadius:10,borderWidth:1,borderColor:"rgba(217,139,130,.22)",alignItems:"center",justifyContent:"center"},removeShiftText:{color:M.red,fontSize:18},addShift:{color:M.goldSoft,fontSize:8,fontWeight:"900",letterSpacing:.6,marginTop:10},hoursSave:{padding:13,borderTopWidth:1,borderTopColor:"rgba(255,255,255,.052)"},logout:{height:54,borderRadius:12,borderWidth:1,borderColor:"rgba(217,139,130,.22)",backgroundColor:"rgba(37,17,15,.30)",alignItems:"center",justifyContent:"center",marginTop:24},logoutText:{color:M.red,fontSize:9.5,fontWeight:"900",letterSpacing:1},saving:{color:M.goldSoft,fontSize:8.5,textAlign:"center",marginTop:9},
 empty:{borderRadius:16,borderWidth:1,borderColor:"rgba(214,189,122,.12)",backgroundColor:"rgba(11,11,10,.88)",padding:19,...cardShadow},emptyTitle:{color:M.goldSoft,fontSize:9,fontWeight:"900",letterSpacing:.7},emptyText:{color:M.muted,fontSize:10.5,lineHeight:16,marginTop:6},error:{borderRadius:10,borderWidth:1,borderColor:"rgba(217,139,130,.26)",backgroundColor:M.redBg,padding:11,marginTop:12},errorText:{color:M.red,fontSize:10.5},
 navSafe:{backgroundColor:"rgba(5,5,5,.985)",borderTopWidth:1,borderTopColor:"rgba(214,189,122,.10)"},nav:{minHeight:74,flexDirection:"row",alignItems:"center",paddingHorizontal:7,paddingTop:5},navItem:{flex:1,minHeight:58,alignItems:"center",justifyContent:"center"},navIconWrap:{width:36,height:28,borderRadius:10,alignItems:"center",justifyContent:"center"},navIconWrapOn:{backgroundColor:"rgba(214,189,122,.075)",borderWidth:1,borderColor:"rgba(214,189,122,.12)"},navIcon:{color:M.muted,fontSize:18},navText:{color:M.muted,fontSize:8.5,fontWeight:"600",marginTop:4},navActive:{color:M.goldSoft,fontWeight:"700"},
 backdrop:{flex:1,backgroundColor:"rgba(0,0,0,.78)",justifyContent:"flex-end"},sheet:{backgroundColor:M.bg2,borderTopLeftRadius:24,borderTopRightRadius:24,borderWidth:1,borderColor:"rgba(214,189,122,.14)",padding:18,paddingBottom:34},handle:{width:42,height:4,borderRadius:2,backgroundColor:"rgba(214,189,122,.16)",alignSelf:"center",marginBottom:16},sheetKicker:{color:M.goldSoft,fontSize:8,fontWeight:"900",letterSpacing:1.2},sheetTitle:{color:M.text,fontSize:21,fontWeight:"700",marginTop:5,marginBottom:10},option:{height:52,borderRadius:11,borderWidth:1,borderColor:"rgba(214,189,122,.10)",backgroundColor:"rgba(11,11,10,.90)",marginTop:7,paddingHorizontal:13,flexDirection:"row",alignItems:"center",justifyContent:"space-between"},optionOn:{borderColor:"rgba(214,189,122,.28)",backgroundColor:"rgba(18,16,12,.74)"},optionText:{color:M.text2,fontSize:11},optionTextOn:{color:M.goldSoft,fontWeight:"800"},check:{color:M.goldSoft,fontSize:16},
 modalHeader:{paddingHorizontal:18},modalContent:{paddingHorizontal:20,paddingBottom:40},modalField:{marginTop:14},modalLabel:{color:M.goldSoft,fontSize:8.5,fontWeight:"900",letterSpacing:1,marginBottom:7},modalInput:{height:54,borderRadius:12,borderWidth:1,borderColor:"rgba(214,189,122,.13)",backgroundColor:"rgba(11,11,10,.88)",color:M.text,paddingHorizontal:13,fontSize:13},modalIntro:{color:M.muted,fontSize:10.5,lineHeight:16,marginTop:8},serviceModal:{minHeight:74,borderRadius:14,borderWidth:1,borderColor:"rgba(214,189,122,.12)",backgroundColor:"rgba(11,11,10,.88)",padding:13,flexDirection:"row",alignItems:"center",marginTop:9,...cardShadow},serviceModalName:{color:M.text,fontSize:13,fontWeight:"700"},serviceModalMeta:{color:M.muted,fontSize:9.2,marginTop:4},serviceModalPrice:{color:M.goldSoft,fontSize:16,fontWeight:"800"},outline:{height:50,borderRadius:11,borderWidth:1,borderColor:"rgba(214,189,122,.22)",backgroundColor:"rgba(10,10,9,.24)",alignItems:"center",justifyContent:"center",marginTop:10},outlineText:{color:M.goldSoft,fontSize:8.5,fontWeight:"900",letterSpacing:.8}
});
