import React,{useEffect,useMemo,useState}from"react";
import{ImageBackground,Linking,Pressable,SafeAreaView,ScrollView,StatusBar,StyleSheet,Text,View}from"react-native";
import AsyncStorage from"@react-native-async-storage/async-storage";
import{BrandLogo,GoldButton,M,Marble,cardShadow}from"./MockupTheme";

const PROFILE="quincyfadez.bookingProfile";
const links={whatsapp:"https://wa.me/447490194682",directions:"https://www.google.com/maps/dir/?api=1&destination=51.7402247,-1.2202434",reviews:"https://g.page/r/CbQwl91s8_vqEBM/review"};
const services=[{name:"Haircut",price:"£20",duration:"45 min"},{name:"Haircut & Beard",price:"£25",duration:"60 min"}];
const open=u=>Linking.openURL(u).catch(()=>{});
const greet=()=>{const h=new Date().getHours();return h<12?"Good morning":h<18?"Good afternoon":"Good evening"};
function Quick({icon,label,onPress}){return <Pressable onPress={onPress} style={({pressed})=>[s.quick,pressed&&s.pressed]}><View style={s.quickIcon}><Text style={s.quickIconText}>{icon}</Text></View><Text style={s.quickText}>{label}</Text></Pressable>}

export default function MockupClientHome({go}){
 const[profile,setProfile]=useState({});
 useEffect(()=>{AsyncStorage.getItem(PROFILE).then(v=>{if(v)try{setProfile(JSON.parse(v))}catch(_){}})},[]);
 const first=useMemo(()=>String(profile.name||"there").trim().split(/\s+/)[0]||"there",[profile]);
 const actions=[["✦","Book Now",()=>go("booking")],["▧","Gallery",()=>go("gallery")],["★","Reviews",()=>go("reviews")],["⌖","Directions",()=>open(links.directions)],["◉","WhatsApp",()=>open(links.whatsapp)],["✂","Services",()=>go("services")]];
 return <Marble><SafeAreaView style={s.safe}><StatusBar barStyle="light-content"/><ScrollView contentContainerStyle={s.content} showsVerticalScrollIndicator={false}>
  <View style={s.top}><Pressable onPress={()=>go("more")} style={s.circle}><Text style={s.circleText}>☰</Text></Pressable><BrandLogo size={56} compact/><Pressable onPress={()=>go("bookings")} style={s.circle}><Text style={s.circleText}>▦</Text></Pressable></View>
  <Text style={s.greeting}>{greet()}, {first}</Text><Text style={s.sub}>Ready for a fresh cut?</Text>
  <ImageBackground source={{uri:"https://quincyfadez.com/media/gallery-replacement-01.jpg"}} imageStyle={{borderRadius:18}} style={s.hero}>
   <View style={s.shade}/><View style={s.heroCopy}><Text style={s.kicker}>QUINCYFADEZ · OXFORD</Text><Text style={s.heroTitle}>LOOK GOOD.{"\n"}FEEL CONFIDENT.</Text><Text style={s.heroText}>Precision cuts, clean detail and a premium one-to-one experience.</Text><GoldButton title="BOOK NOW" onPress={()=>go("booking")} style={s.heroButton}/></View>
  </ImageBackground>
  <Text style={s.section}>QUICK ACTIONS</Text><View style={s.grid}>{actions.map(([i,l,a])=><Quick key={l} icon={i} label={l} onPress={a}/>)}</View>
  <View style={s.why}><Text style={s.whyTitle}>WHY CLIENTS CHOOSE US</Text>{["Precision cuts every time","Premium one-to-one experience","Clean, comfortable and professional"].map(x=><View key={x} style={s.whyRow}><Text style={s.tick}>✓</Text><Text style={s.whyText}>{x}</Text></View>)}</View>
  <View style={s.services}><View style={s.serviceHead}><View><Text style={[s.section,{marginTop:0,marginBottom:0}]}>POPULAR SERVICES</Text><Text style={s.serviceTitle}>Ready When You Are</Text></View><Pressable onPress={()=>go("services")}><Text style={s.view}>VIEW ALL</Text></Pressable></View>{services.map((x,i)=><Pressable key={x.name} onPress={()=>go("booking",x.name)} style={[s.serviceRow,i&&s.line]}><View><Text style={s.serviceName}>{x.name}</Text><Text style={s.serviceMeta}>{x.duration}</Text></View><View style={s.right}><Text style={s.price}>{x.price}</Text><Text style={s.chev}>›</Text></View></Pressable>)}</View>
 </ScrollView></SafeAreaView></Marble>
}
const s=StyleSheet.create({safe:{flex:1},content:{paddingHorizontal:17,paddingTop:7,paddingBottom:116},pressed:{opacity:.78},top:{height:59,flexDirection:"row",alignItems:"center",justifyContent:"space-between"},circle:{width:40,height:40,borderRadius:20,borderWidth:1,borderColor:M.border,backgroundColor:M.panel,alignItems:"center",justifyContent:"center"},circleText:{color:M.goldSoft,fontSize:16,fontWeight:"800"},greeting:{color:M.text,fontSize:26,fontWeight:"900",marginTop:13},sub:{color:M.muted,fontSize:12,marginTop:3},hero:{height:286,borderRadius:18,overflow:"hidden",borderWidth:1,borderColor:M.goldDark,marginTop:16,justifyContent:"flex-end",...cardShadow},shade:{...StyleSheet.absoluteFillObject,backgroundColor:"rgba(0,0,0,.40)"},heroCopy:{padding:17,backgroundColor:"rgba(5,4,3,.72)"},kicker:{color:M.gold,fontSize:8,fontWeight:"900",letterSpacing:1.2},heroTitle:{color:M.goldSoft,fontSize:29,lineHeight:31,fontWeight:"900",marginTop:5},heroText:{color:M.text2,fontSize:11,lineHeight:16,marginTop:6,maxWidth:300},heroButton:{width:150,minHeight:48,marginTop:12},section:{color:M.gold,fontSize:8.5,fontWeight:"900",letterSpacing:1.25,marginTop:21,marginBottom:9},grid:{flexDirection:"row",flexWrap:"wrap",gap:8},quick:{width:"31.7%",height:94,borderRadius:12,borderWidth:1,borderColor:M.border,backgroundColor:"rgba(12,9,5,.94)",alignItems:"center",justifyContent:"center",...cardShadow},quickIcon:{width:35,height:35,borderRadius:18,borderWidth:1,borderColor:M.goldDark,backgroundColor:M.panel3,alignItems:"center",justifyContent:"center"},quickIconText:{color:M.goldSoft,fontSize:15,fontWeight:"900"},quickText:{color:M.text2,fontSize:8.5,fontWeight:"800",marginTop:7},why:{borderRadius:12,borderWidth:1,borderColor:M.border,backgroundColor:M.panel,padding:14,marginTop:18},whyTitle:{color:M.gold,fontSize:8.5,fontWeight:"900",letterSpacing:1.05},whyRow:{flexDirection:"row",gap:8,alignItems:"center",marginTop:9},tick:{color:M.goldSoft,fontSize:11,fontWeight:"900"},whyText:{color:M.text2,fontSize:10.5},services:{borderRadius:12,borderWidth:1,borderColor:M.border,backgroundColor:M.panel,padding:14,marginTop:16,...cardShadow},serviceHead:{flexDirection:"row",alignItems:"flex-start",justifyContent:"space-between"},serviceTitle:{color:M.text,fontSize:17,fontWeight:"850",marginTop:5},view:{color:M.goldSoft,fontSize:8,fontWeight:"900",marginTop:4},serviceRow:{minHeight:62,flexDirection:"row",alignItems:"center",justifyContent:"space-between"},line:{borderTopWidth:1,borderTopColor:M.borderSoft},serviceName:{color:M.text,fontSize:12,fontWeight:"850"},serviceMeta:{color:M.muted,fontSize:8.5,marginTop:3},right:{flexDirection:"row",alignItems:"center",gap:7},price:{color:M.goldSoft,fontSize:15,fontWeight:"900"},chev:{color:M.gold,fontSize:22}});