import React,{useEffect,useState}from"react";
import{ActivityIndicator,Linking,Modal,Pressable,SafeAreaView,ScrollView,StatusBar,StyleSheet,Text,View}from"react-native";
import AsyncStorage from"@react-native-async-storage/async-storage";
import{CustomerSheet,CustomerSheetError}from"@stripe/stripe-react-native";
import WaitingListScreen from"./WaitingListScreen";
import{BrandLogo,M,Marble,cardShadow}from"./MockupTheme";
import{ClientHeader,ClientSection}from"./ClientLuxuryUI";

const API=(process.env.EXPO_PUBLIC_API_URL||"").replace(/\/$/,""),KEY="quincyfadez.paymentClientKey",PROFILE="quincyfadez.bookingProfile";
const links={whatsapp:"https://wa.me/447490194682",reviews:"https://g.page/r/CbQwl91s8_vqEBM/review"};
const makeKey=()=>`qfz_${Date.now().toString(36)}_${Math.random().toString(36).slice(2)}`;
async function clientKey(){const k=await AsyncStorage.getItem(KEY);if(k)return k;const n=makeKey();await AsyncStorage.setItem(KEY,n);return n}
const read=r=>r.json().catch(()=>({}));

function Row({icon,title,sub,onPress,last}){return <Pressable onPress={onPress} style={[s.row,!last&&s.line]}><View style={s.rowIcon}><Text style={s.rowIconText}>{icon}</Text></View><View style={{flex:1}}><Text style={s.rowTitle}>{title}</Text>{sub?<Text style={s.rowSub}>{sub}</Text>:null}</View><Text style={s.chev}>›</Text></Pressable>}

export default function MockupAccountScreenV2({onBack,onBookings}){
 const[key,setKey]=useState(""),[profile,setProfile]=useState({}),[card,setCard]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState(""),[wait,setWait]=useState(false);
 const request=async(path,opt={})=>{if(!API)throw new Error("Secure account services are unavailable.");const r=await fetch(`${API}${path}`,{...opt,headers:{"Content-Type":"application/json",...(opt.headers||{})}}),d=await read(r);if(!r.ok)throw new Error(typeof d.detail==="string"?d.detail:"Account service unavailable.");return d};
 const verify=async(k,silent=false)=>{try{const d=await request("/api/payments/verify",{method:"POST",body:JSON.stringify({client_key:k})});setCard(d.verified?d.payment_method||{}:null)}catch(e){if(!silent)setError(e.message)}};
 useEffect(()=>{Promise.all([clientKey(),AsyncStorage.getItem(PROFILE)]).then(async([k,p])=>{setKey(k);if(p)try{setProfile(JSON.parse(p))}catch(_){}await verify(k,true)}).catch(()=>setError("Your account could not be opened."))},[]);
 const manage=async()=>{if(!key||busy)return;setBusy(true);setError("");try{const provider={async provideCustomerSessionClientSecret(){const d=await request("/api/payments/customer-session",{method:"POST",body:JSON.stringify({client_key:key})});return{customerId:d.customer,clientSecret:d.customer_session_client_secret}},async provideSetupIntentClientSecret(){return(await request("/api/payments/customer-sheet-setup",{method:"POST",body:JSON.stringify({client_key:key})})).setup_intent_client_secret}};const{error:initError}=await CustomerSheet.initialize({intentConfiguration:{paymentMethodTypes:["card"]},clientSecretProvider:provider,headerTextForSelectionScreen:"Manage your payment method",returnURL:"quincyfadez://stripe-redirect",appearance:{colors:{primary:M.gold,background:M.bg,componentBackground:M.panel,componentBorder:M.border,primaryText:M.text,secondaryText:M.muted,componentText:M.text},shapes:{borderRadius:12,borderWidth:1}}});if(initError)throw new Error(initError.message);const r=await CustomerSheet.present();if(r.error&&r.error.code!==CustomerSheetError.Canceled)throw new Error(r.error.message||"Payment method could not be updated.");await verify(key,true)}catch(e){setError(e.message||"Payment settings could not be opened.")}finally{setBusy(false)}};
 return <Marble><SafeAreaView style={s.safe}><StatusBar barStyle="light-content"/><ScrollView contentContainerStyle={s.content} showsVerticalScrollIndicator={false}>
  <ClientHeader title="My Account" subtitle="Manage your bookings, payment method and QuincyFadez account." onBack={onBack}/>
  <View style={s.profile}><BrandLogo size={82} compact/><View style={{flex:1}}><Text style={s.name}>{profile.name||"QuincyFadez Client"}</Text><Text style={s.meta}>{profile.email||"Your client account"}</Text>{profile.phone?<Text style={s.meta}>{profile.phone}</Text>:null}</View></View>
  <ClientSection title="PAYMENT METHOD"/>
  <View style={s.payment}><View style={s.paymentTop}><View style={s.cardIcon}><Text style={s.cardIconText}>▰</Text></View><View style={{flex:1}}><Text style={s.paymentTitle}>{card?.last4?`${(card.brand||"Card").toUpperCase()} •••• ${card.last4}`:"No Saved Payment Method"}</Text><Text style={s.paymentText}>{card?"Verified securely by Stripe for booking protection.":"Add a card for booking protection. Verification does not charge your service price."}</Text></View><View style={[s.status,card&&s.statusOn]}><Text style={[s.statusText,card&&s.statusTextOn]}>{card?"VERIFIED":"NOT SET"}</Text></View></View>{busy?<View style={s.manageBusy}><ActivityIndicator color="#090704"/></View>:<Pressable onPress={manage} style={s.manage}><Text style={s.manageText}>MANAGE PAYMENT METHODS</Text><Text style={s.manageArrow}>›</Text></Pressable>}</View>
  <ClientSection title="YOUR ACCOUNT"/>
  <View style={s.card}><Row icon="▦" title="My Bookings" sub="Upcoming and past appointments" onPress={onBookings}/><Row icon="☆" title="Waiting List" sub="Join or manage waiting-list requests" onPress={()=>setWait(true)}/><Row icon="◉" title="Contact QuincyFadez" sub="Questions or appointment help" last onPress={()=>Linking.openURL(links.whatsapp).catch(()=>{})}/></View>
  <ClientSection title="QUICK LINKS"/>
  <View style={s.card}><Row icon="◉" title="WhatsApp QuincyFadez" onPress={()=>Linking.openURL(links.whatsapp).catch(()=>{})}/><Row icon="★" title="Leave A Google Review" last onPress={()=>Linking.openURL(links.reviews).catch(()=>{})}/></View>
  {error?<View style={s.error}><Text style={s.errorText}>{error}</Text></View>:null}
 </ScrollView></SafeAreaView><Modal visible={wait} animationType="slide" onRequestClose={()=>setWait(false)}><WaitingListScreen onBack={()=>setWait(false)}/></Modal></Marble>
}

const s=StyleSheet.create({safe:{flex:1},content:{paddingHorizontal:18,paddingTop:7,paddingBottom:112},profile:{borderRadius:16,borderWidth:1,borderColor:"rgba(214,189,122,.26)",backgroundColor:"rgba(16,16,15,.93)",padding:16,flexDirection:"row",alignItems:"center",gap:15,...cardShadow},name:{color:M.text,fontSize:18,fontWeight:"700"},meta:{color:M.muted,fontSize:10.5,marginTop:5},payment:{borderRadius:15,borderWidth:1,borderColor:"rgba(214,189,122,.24)",backgroundColor:"rgba(16,16,15,.93)",padding:15,...cardShadow},paymentTop:{flexDirection:"row",alignItems:"flex-start",gap:11},cardIcon:{width:44,height:44,borderRadius:12,borderWidth:1,borderColor:M.goldDark,backgroundColor:M.panel3,alignItems:"center",justifyContent:"center"},cardIconText:{color:M.goldSoft,fontSize:22},paymentTitle:{color:M.text,fontSize:14,fontWeight:"700"},paymentText:{color:M.muted,fontSize:10,lineHeight:14,marginTop:5},status:{borderRadius:7,borderWidth:1,borderColor:M.border,backgroundColor:M.panel2,paddingHorizontal:7,paddingVertical:5},statusOn:{borderColor:"#225A35",backgroundColor:M.greenBg},statusText:{color:M.muted,fontSize:7,fontWeight:"900"},statusTextOn:{color:M.green},manage:{height:52,borderRadius:10,backgroundColor:M.gold,marginTop:14,paddingHorizontal:15,flexDirection:"row",alignItems:"center",justifyContent:"space-between"},manageBusy:{height:52,borderRadius:10,backgroundColor:M.gold,marginTop:14,alignItems:"center",justifyContent:"center"},manageText:{color:"#090704",fontSize:10,fontWeight:"900"},manageArrow:{color:"#090704",fontSize:23},card:{borderRadius:15,borderWidth:1,borderColor:"rgba(214,189,122,.20)",backgroundColor:"rgba(16,16,15,.93)",overflow:"hidden",...cardShadow},row:{minHeight:72,paddingHorizontal:14,flexDirection:"row",alignItems:"center",gap:11},rowIcon:{width:38,height:38,borderRadius:19,borderWidth:1,borderColor:M.goldDark,backgroundColor:M.panel3,alignItems:"center",justifyContent:"center"},rowIconText:{color:M.goldSoft,fontSize:16},line:{borderBottomWidth:1,borderBottomColor:"rgba(255,255,255,.07)"},rowTitle:{color:M.text,fontSize:13.5,fontWeight:"700"},rowSub:{color:M.muted,fontSize:9.5,marginTop:3},chev:{color:M.gold,fontSize:24},error:{borderRadius:9,borderWidth:1,borderColor:"#63372E",backgroundColor:M.redBg,padding:10,marginTop:12},errorText:{color:M.red,fontSize:10.5}});