import React,{useEffect,useState}from"react";
import{ActivityIndicator,Image,Linking,Pressable,SafeAreaView,ScrollView,StatusBar,StyleSheet,Text,View}from"react-native";
import{BrandLogo,M,Marble,cardShadow,shadow}from"./MockupTheme";
import{ClientHeader,ClientSection}from"./ClientLuxuryUI";

const API="https://quincyfadez.com/api/google-reviews",LEAVE="https://g.page/r/CbQwl91s8_vqEBM/review",VIEW="https://www.google.com/maps/search/?api=1&query=QuincyFadez%20Oxford";
const stars=n=>"★".repeat(Math.round(Number(n||0))).padEnd(5,"☆");
const open=u=>u&&Linking.openURL(u).catch(()=>{});

export default function MockupReviewsScreenV2({onBack}){
 const[data,setData]=useState(null),[loading,setLoading]=useState(true),[error,setError]=useState(false);
 const load=async()=>{setLoading(true);setError(false);try{const r=await fetch(API,{cache:"no-store"});if(!r.ok)throw 0;setData(await r.json())}catch{setError(true)}finally{setLoading(false)}};
 useEffect(()=>{load()},[]);
 const list=data?.reviews||[];
 return <Marble><SafeAreaView style={s.safe}><StatusBar barStyle="light-content"/><ScrollView contentContainerStyle={s.content} showsVerticalScrollIndicator={false}>
   <ClientHeader title="Google Reviews" subtitle="Recent Google feedback from QuincyFadez clients." onBack={onBack}/>
   {loading?<View style={s.state}><ActivityIndicator color={M.gold}/><Text style={s.stateText}>Loading Google reviews…</Text></View>:error?<View style={s.state}><Text style={s.stateIcon}>★</Text><Text style={s.stateTitle}>Reviews Temporarily Unavailable</Text><Text style={s.stateText}>The live Google review service could not be reached just now.</Text><Pressable onPress={load} style={s.retry}><Text style={s.retryText}>TRY AGAIN</Text></Pressable></View>:<>
     <View style={s.rating}><BrandLogo size={58} compact/><View style={s.ratingBody}><Text style={s.ratingLabel}>GOOGLE RATING</Text><View style={s.ratingLine}><Text style={s.ratingNumber}>{data?.rating?.toFixed?.(1)||data?.rating||"—"}</Text><Text style={s.ratingStar}>★</Text></View><Text style={s.stars}>{stars(data?.rating)}</Text><Text style={s.count}>{data?.reviewCount||0} Google reviews</Text></View></View>
     <ClientSection title="RECENT REVIEWS"/>
     {list.length?list.map(r=><View key={r.id} style={s.card}><View style={s.author}>{r.author?.photoUrl?<Image source={{uri:r.author.photoUrl}} style={s.avatar}/>:<View style={s.avatarFallback}><Text style={s.avatarText}>{r.author?.name?.[0]||"G"}</Text></View>}<View style={{flex:1}}><Text style={s.authorName}>{r.author?.name||"Google reviewer"}</Text><Text style={s.meta}>{r.relativeTime}</Text></View><Text style={s.cardStars}>{stars(r.rating)}</Text></View>{r.text?<Text style={s.review}>{r.text}</Text>:null}{r.sourceUrl?<Pressable onPress={()=>open(r.sourceUrl)}><Text style={s.link}>VIEW ON GOOGLE ↗</Text></Pressable>:null}</View>):<View style={s.state}><Text style={s.stateTitle}>Live Rating Connected</Text><Text style={s.stateText}>Written review comments will appear here when Google provides them.</Text></View>}
   </>}
   <Pressable onPress={()=>open(LEAVE)} style={s.primary}><Text style={s.primaryText}>LEAVE A GOOGLE REVIEW</Text><Text style={s.primaryArrow}>›</Text></Pressable>
   <Pressable onPress={()=>open(VIEW)} style={s.secondary}><Text style={s.secondaryText}>VIEW ALL REVIEWS ON GOOGLE</Text></Pressable>
 </ScrollView></SafeAreaView></Marble>;
}

const s=StyleSheet.create({
 safe:{flex:1},content:{paddingHorizontal:20,paddingTop:7,paddingBottom:112},state:{borderRadius:17,borderWidth:1,borderColor:"rgba(214,189,122,.12)",backgroundColor:"rgba(11,11,10,.88)",padding:22,alignItems:"center",...cardShadow},stateIcon:{color:M.goldSoft,fontSize:31},stateTitle:{color:M.text,fontSize:16,fontWeight:"700",textAlign:"center",marginTop:8},stateText:{color:M.muted,fontSize:10.5,lineHeight:16,textAlign:"center",marginTop:7},retry:{height:44,borderRadius:10,borderWidth:1,borderColor:"rgba(214,189,122,.22)",paddingHorizontal:18,alignItems:"center",justifyContent:"center",marginTop:13},retryText:{color:M.goldSoft,fontSize:8.5,fontWeight:"900",letterSpacing:.8},rating:{borderRadius:17,borderWidth:1,borderColor:"rgba(214,189,122,.13)",backgroundColor:"rgba(11,11,10,.90)",padding:16,flexDirection:"row",alignItems:"center",gap:15,...cardShadow},ratingBody:{flex:1},ratingLabel:{color:M.goldSoft,fontSize:8.5,fontWeight:"900",letterSpacing:1.15},ratingLine:{flexDirection:"row",alignItems:"center",gap:7,marginTop:4},ratingNumber:{color:M.text,fontSize:34,fontWeight:"700"},ratingStar:{color:M.goldSoft,fontSize:23},stars:{color:M.goldSoft,fontSize:12,letterSpacing:1.5,marginTop:1},count:{color:M.muted,fontSize:9.5,marginTop:6},card:{borderRadius:16,borderWidth:1,borderColor:"rgba(214,189,122,.12)",backgroundColor:"rgba(11,11,10,.88)",padding:15,marginBottom:10,...cardShadow},author:{flexDirection:"row",alignItems:"center",gap:10},avatar:{width:40,height:40,borderRadius:20},avatarFallback:{width:40,height:40,borderRadius:12,borderWidth:1,borderColor:"rgba(214,189,122,.16)",backgroundColor:"rgba(18,16,12,.62)",alignItems:"center",justifyContent:"center"},avatarText:{color:M.goldSoft,fontWeight:"900"},authorName:{color:M.text,fontSize:12.5,fontWeight:"700"},meta:{color:M.muted,fontSize:9,marginTop:3},cardStars:{color:M.goldSoft,fontSize:9.5,letterSpacing:.5},review:{color:M.text2,fontSize:11,lineHeight:16,marginTop:12},link:{color:M.goldSoft,fontSize:7.8,fontWeight:"900",letterSpacing:.7,marginTop:11},primary:{height:56,borderRadius:12,backgroundColor:M.gold,borderWidth:1,borderColor:"rgba(241,221,162,.68)",marginTop:22,paddingHorizontal:16,flexDirection:"row",alignItems:"center",justifyContent:"space-between",...shadow},primaryText:{color:"#090704",fontSize:9.5,fontWeight:"900",letterSpacing:.9},primaryArrow:{color:"#090704",fontSize:23},secondary:{height:54,borderRadius:12,borderWidth:1,borderColor:"rgba(214,189,122,.24)",backgroundColor:"rgba(10,10,9,.26)",alignItems:"center",justifyContent:"center",marginTop:10},secondaryText:{color:M.goldSoft,fontSize:8.8,fontWeight:"800",letterSpacing:.8}
});
