import React,{useEffect,useMemo,useState}from"react";
import{ActivityIndicator,Pressable,SafeAreaView,ScrollView,StatusBar,StyleSheet,Text,View}from"react-native";
import AsyncStorage from"@react-native-async-storage/async-storage";
import{GoldButton,M,Marble,Pill,cardShadow}from"./MockupTheme";
const API=(process.env.EXPO_PUBLIC_API_URL||"").replace(/\/$/,""),KEY="quincyfadez.paymentClientKey";
const read=r=>r.json().catch(()=>({}));
const parts=v=>{const d=new Date(v);return{week:d.toLocaleDateString("en-GB",{weekday:"short",timeZone:"Europe/London"}).toUpperCase(),day:d.toLocaleDateString("en-GB",{day:"2-digit",timeZone:"Europe/London"}),month:d.toLocaleDateString("en-GB",{month:"short",timeZone:"Europe/London"}).toUpperCase(),time:d.toLocaleTimeString("en-GB",{hour:"numeric",minute:"2-digit",hour12:true,timeZone:"Europe/London"}).replace(":00","")}};
const state=v=>String(v||"confirmed").replaceAll("_"," ").toUpperCase();
function Status({value}){const pending=value==="pending",bad=["cancelled","expired","no_show"].includes(value),done=value==="completed";return <View style={[s.status,pending&&s.statusPending,bad&&s.statusBad,done&&s.statusDone]}><Text style={[s.statusText,pending&&s.statusPendingText,bad&&s.statusBadText,done&&s.statusDoneText]}>{state(value)}</Text></View>}
function Booking({x,onCancel,busy}){const p=parts(x.start_at);return <View style={s.booking}><View style={s.dateBox}><Text style={s.dateWeek}>{p.week}</Text><Text style={s.dateDay}>{p.day}</Text><Text style={s.dateMonth}>{p.month}</Text></View><View style={s.bookingBody}><View style={s.bookingTop}><View style={{flex:1}}><Text style={s.time}>{p.time}</Text><Text style={s.service}>{x.service}</Text><Text style={s.meta}>{x.duration_minutes||0} min · £{x.price}</Text></View><Status value={x.status}/></View>{["pending","confirmed"].includes(x.status)?<Pressable disabled={busy} onPress={()=>onCancel(x.id)} style={s.cancel}><Text style={s.cancelText}>{busy?"CANCELLING…":"CANCEL BOOKING"}</Text></Pressable>:null}</View></View>}
export default function MockupClientBookings({onBack,onBook}){
 const[bookings,setBookings]=useState([]),[key,setKey]=useState(""),[loading,setLoading]=useState(true),[error,setError]=useState(""),[tab,setTab]=useState("upcoming"),[busy,setBusy]=useState("");
 const request=async(path,opt={})=>{const r=await fetch(`${API}${path}`,{...opt,headers:{"Content-Type":"application/json",...(opt.headers||{})}}),d=await read(r);if(!r.ok)throw new Error(typeof d.detail==="string"?d.detail:"Bookings could not be loaded.");return d};
 const refresh=async k=>{if(!k){setLoading(false);return}setLoading(true);setError("");try{setBookings((await request(`/api/booking/appointments/${encodeURIComponent(k)}`)).bookings||[])}catch(e){setError(e.message)}finally{setLoading(false)}};
 useEffect(()=>{AsyncStorage.getItem(KEY).then(k=>{setKey(k||"");return refresh(k||"")}).catch(()=>{setError("Your booking account could not be opened.");setLoading(false)})},[]);
 const cancel=async id=>{if(!key||busy)return;setBusy(id);try{await request(`/api/booking/appointments/${id}/cancel`,{method:"POST",body:JSON.stringify({client_key:key})});await refresh(key)}catch(e){setError(e.message)}finally{setBusy("")}};
 const now=Date.now(),up=useMemo(()=>bookings.filter(x=>["pending","confirmed"].includes(x.status)&&new Date(x.start_at).getTime()>=now).sort((a,b)=>String(a.start_at).localeCompare(String(b.start_at))),[bookings]),past=useMemo(()=>bookings.filter(x=>!["pending","confirmed"].includes(x.status)||new Date(x.start_at).getTime()<now).sort((a,b)=>String(b.start_at).localeCompare(String(a.start_at))),[bookings]);
 const shown=tab==="upcoming"?up:past;
 return <Marble><SafeAreaView style={s.safe}><StatusBar barStyle="light-content"/><ScrollView contentContainerStyle={s.content} showsVerticalScrollIndicator={false}>
  <View style={s.header}><Pressable onPress={onBack} style={s.headerBtn}><Text style={s.back}>‹</Text></Pressable><Text style={s.headerTitle}>My Bookings</Text><View style={s.headerBtn}/></View>
  <Text style={s.subtitle}>View and manage your upcoming and past visits.</Text>
  <View style={s.tabs}><Pressable onPress={()=>setTab("upcoming")} style={[s.tab,tab==="upcoming"&&s.tabOn]}><Text style={[s.tabText,tab==="upcoming"&&s.tabTextOn]}>UPCOMING</Text></Pressable><Pressable onPress={()=>setTab("past")} style={[s.tab,tab==="past"&&s.tabOn]}><Text style={[s.tabText,tab==="past"&&s.tabTextOn]}>PAST</Text></Pressable></View>
  <View style={s.sectionHead}><Text style={s.section}>{tab==="upcoming"?"UPCOMING APPOINTMENTS":"PAST APPOINTMENTS"}</Text><Pill>{shown.length} SHOWN</Pill></View>
  {loading?<View style={s.state}><ActivityIndicator color={M.gold}/><Text style={s.stateText}>Loading your appointments…</Text></View>:shown.length?shown.map(x=><Booking key={x.id} x={x} onCancel={cancel} busy={busy===x.id}/>):<View style={s.state}><Text style={s.emptyTitle}>{tab==="upcoming"?"NO UPCOMING APPOINTMENTS":"NO PAST APPOINTMENTS"}</Text><Text style={s.stateText}>{tab==="upcoming"?"Your next appointment will appear here as soon as you book it.":"Completed and previous visits will appear here."}</Text>{tab==="upcoming"?<GoldButton title="BOOK AN APPOINTMENT" onPress={onBook} style={{marginTop:14,width:"100%"}}/>:null}</View>}
  {error?<View style={s.error}><Text style={s.errorText}>{error}</Text></View>:null}
 </ScrollView></SafeAreaView></Marble>
}
const s=StyleSheet.create({safe:{flex:1},content:{paddingHorizontal:18,paddingTop:4,paddingBottom:115},header:{height:59,flexDirection:"row",alignItems:"center",justifyContent:"space-between"},headerBtn:{width:46,height:46,justifyContent:"center"},back:{color:M.text,fontSize:34,lineHeight:36},headerTitle:{color:M.text,fontSize:20,fontWeight:"850"},subtitle:{color:M.muted,fontSize:12,lineHeight:18,textAlign:"center",marginTop:2},tabs:{height:48,flexDirection:"row",borderRadius:10,borderWidth:1,borderColor:M.border,backgroundColor:M.panel,padding:4,marginTop:17},tab:{flex:1,borderRadius:7,alignItems:"center",justifyContent:"center"},tabOn:{backgroundColor:M.panel3,borderWidth:1,borderColor:M.goldDeep},tabText:{color:M.muted,fontSize:8.5,fontWeight:"900",letterSpacing:1},tabTextOn:{color:M.goldSoft},sectionHead:{flexDirection:"row",alignItems:"center",justifyContent:"space-between",marginTop:18,marginBottom:8},section:{color:M.gold,fontSize:9,fontWeight:"900",letterSpacing:1.25},booking:{borderRadius:12,borderWidth:1,borderColor:M.border,backgroundColor:"rgba(12,9,5,.94)",flexDirection:"row",overflow:"hidden",marginBottom:9,...cardShadow},dateBox:{width:72,backgroundColor:M.panel2,borderRightWidth:1,borderRightColor:M.border,alignItems:"center",justifyContent:"center",paddingVertical:14},dateWeek:{color:M.gold,fontSize:8,fontWeight:"900"},dateDay:{color:M.text,fontSize:25,fontWeight:"900",marginVertical:2},dateMonth:{color:M.muted,fontSize:8,fontWeight:"900"},bookingBody:{flex:1,padding:12},bookingTop:{flexDirection:"row",gap:8},time:{color:M.text,fontSize:15,fontWeight:"900"},service:{color:M.text2,fontSize:12,fontWeight:"800",marginTop:4},meta:{color:M.muted,fontSize:9.5,marginTop:4},status:{borderRadius:7,borderWidth:1,borderColor:"#235A36",backgroundColor:M.greenBg,paddingHorizontal:7,paddingVertical:5,alignSelf:"flex-start"},statusText:{color:M.green,fontSize:6.5,fontWeight:"900"},statusPending:{borderColor:"#73541D",backgroundColor:M.amberBg},statusPendingText:{color:M.amber},statusBad:{borderColor:"#67362E",backgroundColor:M.redBg},statusBadText:{color:M.red},statusDone:{borderColor:M.border,backgroundColor:M.panel2},statusDoneText:{color:M.muted},cancel:{height:34,borderRadius:7,borderWidth:1,borderColor:M.border,alignItems:"center",justifyContent:"center",marginTop:10},cancelText:{color:M.muted,fontSize:7.5,fontWeight:"900",letterSpacing:.7},state:{borderRadius:12,borderWidth:1,borderColor:M.border,backgroundColor:M.panel,padding:20,alignItems:"center",marginTop:4},stateText:{color:M.muted,fontSize:11,lineHeight:17,textAlign:"center",marginTop:8},emptyTitle:{color:M.gold,fontSize:9,fontWeight:"900",letterSpacing:1},error:{borderRadius:9,borderWidth:1,borderColor:"#63372E",backgroundColor:M.redBg,padding:10,marginTop:10},errorText:{color:M.red,fontSize:10.5}});