import React,{useEffect,useMemo,useState}from"react";
import{ActivityIndicator,Alert,Pressable,SafeAreaView,ScrollView,StatusBar,StyleSheet,Text,View}from"react-native";
import AsyncStorage from"@react-native-async-storage/async-storage";
import{M,Marble,cardShadow}from"./MockupTheme";
import{ClientHeader,ClientSection}from"./ClientLuxuryUI";

const API=(process.env.EXPO_PUBLIC_API_URL||"").replace(/\/$/,""),KEY="quincyfadez.paymentClientKey";
const read=r=>r.json().catch(()=>({}));
const parts=v=>{const d=new Date(v);return{week:d.toLocaleDateString("en-GB",{weekday:"short",timeZone:"Europe/London"}).toUpperCase(),day:d.toLocaleDateString("en-GB",{day:"2-digit",timeZone:"Europe/London"}),month:d.toLocaleDateString("en-GB",{month:"short",timeZone:"Europe/London"}).toUpperCase(),time:d.toLocaleTimeString("en-GB",{hour:"numeric",minute:"2-digit",hour12:true,timeZone:"Europe/London"}).replace(":00","")}};
const state=v=>String(v||"confirmed").replaceAll("_"," ").toUpperCase();

function Status({value}){const pending=value==="pending",bad=["cancelled","expired","no_show"].includes(value),done=value==="completed";return <View style={[s.status,pending&&s.statusPending,bad&&s.statusBad,done&&s.statusDone]}><Text style={[s.statusText,pending&&{color:M.amber},bad&&{color:M.red},done&&{color:M.muted}]}>{state(value)}</Text></View>}
function Booking({x,onCancel,busy}){const p=parts(x.start_at);return <View style={s.booking}><View style={s.dateBox}><Text style={s.dateWeek}>{p.week}</Text><Text style={s.dateDay}>{p.day}</Text><Text style={s.dateMonth}>{p.month}</Text></View><View style={s.body}><View style={s.top}><View style={{flex:1}}><Text style={s.time}>{p.time}</Text><Text style={s.service}>{x.service}</Text><Text style={s.meta}>{x.duration_minutes||0} min · £{x.price}</Text></View><Status value={x.status}/></View>{["pending","confirmed"].includes(x.status)?<Pressable disabled={busy} onPress={()=>onCancel(x.id)} style={s.cancel}><Text style={s.cancelText}>{busy?"CANCELLING…":"CANCEL BOOKING"}</Text></Pressable>:null}</View></View>}

export default function MockupClientBookingsV2({onBack,onBook}){
 const[bookings,setBookings]=useState([]),[key,setKey]=useState(""),[loading,setLoading]=useState(true),[error,setError]=useState(""),[tab,setTab]=useState("upcoming"),[busy,setBusy]=useState("");
 const request=async(path,opt={})=>{const r=await fetch(`${API}${path}`,{...opt,headers:{"Content-Type":"application/json",...(opt.headers||{})}}),d=await read(r);if(!r.ok)throw new Error(typeof d.detail==="string"?d.detail:"Bookings could not be loaded.");return d};
 const refresh=async k=>{if(!k){setLoading(false);return}setLoading(true);setError("");try{setBookings((await request(`/api/booking/appointments/${encodeURIComponent(k)}`)).bookings||[])}catch(e){setError(e.message)}finally{setLoading(false)}};
 useEffect(()=>{AsyncStorage.getItem(KEY).then(k=>{setKey(k||"");return refresh(k||"")}).catch(()=>{setError("Your booking account could not be opened.");setLoading(false)})},[]);
 const cancel=async id=>{if(!key||busy)return;Alert.alert("Cancel booking?","This will release your appointment slot.",[{text:"Keep",style:"cancel"},{text:"Cancel Booking",style:"destructive",onPress:async()=>{setBusy(id);try{await request(`/api/booking/appointments/${id}/cancel`,{method:"POST",body:JSON.stringify({client_key:key})});await refresh(key)}catch(e){setError(e.message)}finally{setBusy("")}}}])};
 const now=Date.now(),up=useMemo(()=>bookings.filter(x=>["pending","confirmed"].includes(x.status)&&new Date(x.start_at).getTime()>=now).sort((a,b)=>String(a.start_at).localeCompare(String(b.start_at))),[bookings]),past=useMemo(()=>bookings.filter(x=>!["pending","confirmed"].includes(x.status)||new Date(x.start_at).getTime()<now).sort((a,b)=>String(b.start_at).localeCompare(String(a.start_at))),[bookings]);
 const shown=tab==="upcoming"?up:past;
 return <Marble><SafeAreaView style={s.safe}><StatusBar barStyle="light-content"/><ScrollView contentContainerStyle={s.content} showsVerticalScrollIndicator={false}>
   <ClientHeader title="My Bookings" subtitle="View and manage your upcoming and previous QuincyFadez visits." onBack={onBack}/>
   <View style={s.tabs}><Pressable onPress={()=>setTab("upcoming")} style={[s.tab,tab==="upcoming"&&s.tabOn]}><Text style={[s.tabText,tab==="upcoming"&&s.tabTextOn]}>UPCOMING</Text></Pressable><Pressable onPress={()=>setTab("past")} style={[s.tab,tab==="past"&&s.tabOn]}><Text style={[s.tabText,tab==="past"&&s.tabTextOn]}>PAST</Text></Pressable></View>
   <ClientSection title={tab==="upcoming"?"UPCOMING APPOINTMENTS":"PAST APPOINTMENTS"}/>
   {loading?<View style={s.state}><ActivityIndicator color={M.gold}/><Text style={s.stateText}>Loading your appointments…</Text></View>:shown.length?shown.map(x=><Booking key={x.id} x={x} onCancel={cancel} busy={busy===x.id}/>):<View style={s.state}><Text style={s.emptyIcon}>{tab==="upcoming"?"▦":"◷"}</Text><Text style={s.emptyTitle}>{tab==="upcoming"?"No Upcoming Appointments":"No Past Appointments"}</Text><Text style={s.stateText}>{tab==="upcoming"?"Book your next cut and it will appear here.":"Completed and previous visits will appear here."}</Text>{tab==="upcoming"?<Pressable onPress={onBook} style={s.book}><Text style={s.bookText}>BOOK AN APPOINTMENT</Text><Text style={s.bookArrow}>›</Text></Pressable>:null}</View>}
   {error?<View style={s.error}><Text style={s.errorText}>{error}</Text></View>:null}
 </ScrollView></SafeAreaView></Marble>
}

const s=StyleSheet.create({safe:{flex:1},content:{paddingHorizontal:18,paddingTop:7,paddingBottom:112},tabs:{height:50,flexDirection:"row",borderRadius:12,borderWidth:1,borderColor:M.border,backgroundColor:"rgba(16,16,15,.92)",padding:4},tab:{flex:1,borderRadius:9,alignItems:"center",justifyContent:"center"},tabOn:{backgroundColor:M.gold},tabText:{color:M.muted,fontSize:9,fontWeight:"900",letterSpacing:.8},tabTextOn:{color:"#090704"},booking:{borderRadius:15,borderWidth:1,borderColor:"rgba(214,189,122,.22)",backgroundColor:"rgba(16,16,15,.93)",flexDirection:"row",overflow:"hidden",marginBottom:10,...cardShadow},dateBox:{width:78,backgroundColor:"rgba(27,22,14,.78)",borderRightWidth:1,borderRightColor:M.border,alignItems:"center",justifyContent:"center",paddingVertical:16},dateWeek:{color:M.gold,fontSize:9,fontWeight:"900"},dateDay:{color:M.text,fontSize:28,fontWeight:"800",marginVertical:2},dateMonth:{color:M.muted,fontSize:9,fontWeight:"800"},body:{flex:1,padding:13},top:{flexDirection:"row",gap:8},time:{color:M.text,fontSize:17,fontWeight:"700"},service:{color:M.text2,fontSize:12.5,fontWeight:"700",marginTop:4},meta:{color:M.muted,fontSize:10,marginTop:4},status:{borderRadius:7,borderWidth:1,borderColor:"#225A35",backgroundColor:M.greenBg,paddingHorizontal:7,paddingVertical:5,alignSelf:"flex-start"},statusText:{color:M.green,fontSize:7,fontWeight:"900"},statusPending:{borderColor:"#73541D",backgroundColor:M.amberBg},statusBad:{borderColor:"#67362E",backgroundColor:M.redBg},statusDone:{borderColor:M.border,backgroundColor:M.panel2},cancel:{height:38,borderRadius:8,borderWidth:1,borderColor:M.border,alignItems:"center",justifyContent:"center",marginTop:11},cancelText:{color:M.muted,fontSize:8,fontWeight:"900",letterSpacing:.7},state:{borderRadius:15,borderWidth:1,borderColor:M.border,backgroundColor:"rgba(16,16,15,.93)",padding:22,alignItems:"center",...cardShadow},emptyIcon:{color:M.gold,fontSize:35},emptyTitle:{color:M.text,fontSize:18,fontWeight:"700",marginTop:10},stateText:{color:M.muted,fontSize:11.5,lineHeight:17,textAlign:"center",marginTop:8},book:{width:"100%",height:52,borderRadius:10,backgroundColor:M.gold,marginTop:16,paddingHorizontal:15,flexDirection:"row",alignItems:"center",justifyContent:"space-between"},bookText:{color:"#090704",fontSize:10,fontWeight:"900"},bookArrow:{color:"#090704",fontSize:23},error:{borderRadius:9,borderWidth:1,borderColor:"#63372E",backgroundColor:M.redBg,padding:10,marginTop:11},errorText:{color:M.red,fontSize:10.5}});