import React,{useEffect,useState} from "react";
import {SafeAreaView,ScrollView,StatusBar,StyleSheet,Text,TextInput,View} from "react-native";
import AsyncStorage from "@react-native-async-storage/async-storage";
import {M,Marble,PrimaryButton,Surface} from "./QFTheme";
import {ClientHeader} from "./ClientLuxuryUI";
import QFIcon from "./QFIcons";

const API=(process.env.EXPO_PUBLIC_API_URL||"").replace(/\/$/,"");
const PROFILE="quincyfadez.bookingProfile",SESSION="quincyfadez.clientSession";
const read=r=>r.json().catch(()=>({}));
function Field({label,help,...props}){return <View style={s.field}><Text style={s.label}>{label}</Text><TextInput placeholderTextColor={M.muted2} style={s.input}{...props}/>{help?<Text style={s.help}>{help}</Text>:null}</View>}

export default function PersonalInformationScreen({onBack}){
  const[name,setName]=useState(""),[email,setEmail]=useState(""),[phone,setPhone]=useState(""),[saving,setSaving]=useState(false),[saved,setSaved]=useState(false),[error,setError]=useState("");
  const apply=p=>{setName(p?.name||"");setEmail(p?.email||"");setPhone(p?.phone||"")};
  useEffect(()=>{let alive=true;(async()=>{try{const[localRaw,sessionRaw]=await Promise.all([AsyncStorage.getItem(PROFILE),AsyncStorage.getItem(SESSION)]);if(localRaw)try{if(alive)apply(JSON.parse(localRaw))}catch(_){}const session=sessionRaw?JSON.parse(sessionRaw):null;if(API&&session?.token){const r=await fetch(`${API}/api/client/me`,{headers:{Authorization:`Bearer ${session.token}`}}),d=await read(r);if(r.ok&&d.profile){if(alive)apply(d.profile);await AsyncStorage.setItem(PROFILE,JSON.stringify({name:d.profile.name||"",email:d.profile.email||"",phone:d.profile.phone||""}));await AsyncStorage.setItem(SESSION,JSON.stringify({...session,profile:{...(session.profile||{}),...d.profile}}))}}}catch(_){}return()=>{alive=false}})()},[]);
  const save=async()=>{if(saving)return;setSaved(false);setError("");const clean={name:name.trim(),email:email.trim().toLowerCase(),phone:phone.trim()};if(clean.name.length<2)return setError("Enter your full name.");if(!clean.email.includes("@"))return setError("Enter a valid email address.");if(clean.phone.length<7)return setError("Enter a valid mobile number.");setSaving(true);try{const raw=await AsyncStorage.getItem(SESSION),session=raw?JSON.parse(raw):null;if(!session?.token)throw new Error("Your login session has expired. Please log in again.");if(!API)throw new Error("The account service is unavailable in this build.");const r=await fetch(`${API}/api/client/me`,{method:"PUT",headers:{"Content-Type":"application/json",Authorization:`Bearer ${session.token}`},body:JSON.stringify(clean)}),d=await read(r);if(!r.ok||!d.profile)throw new Error(typeof d.detail==="string"?d.detail:"Your details could not be updated.");const profile={name:d.profile.name||clean.name,email:d.profile.email||clean.email,phone:d.profile.phone||clean.phone};apply(profile);await AsyncStorage.setItem(PROFILE,JSON.stringify(profile));await AsyncStorage.setItem(SESSION,JSON.stringify({...session,profile:{...(session.profile||{}),...d.profile}}));setSaved(true)}catch(e){setError(e.message||"Your details could not be updated.")}finally{setSaving(false)}};
  return <Marble><SafeAreaView style={s.safe}><StatusBar barStyle="light-content"/><ScrollView keyboardShouldPersistTaps="handled" contentContainerStyle={s.content} showsVerticalScrollIndicator={false}>
    <ClientHeader title="Personal information" subtitle="Keep the contact details attached to your bookings up to date." onBack={onBack}/>
    {saved?<View style={s.saved}><QFIcon name="check" size={18} color={M.green}/><Text style={s.savedText}>Account details updated</Text></View>:null}
    {error?<View style={s.error}><Text style={s.errorText}>{error}</Text></View>:null}
    <Surface style={s.card}><Field label="Full name" value={name} onChangeText={v=>{setSaved(false);setError("");setName(v)}} placeholder="Your full name" autoCapitalize="words"/><Field label="Email address" value={email} onChangeText={v=>{setSaved(false);setError("");setEmail(v)}} placeholder="you@example.com" keyboardType="email-address" autoCapitalize="none"/><Field label="Mobile number" value={phone} onChangeText={v=>{setSaved(false);setError("");setPhone(v)}} placeholder="07..." keyboardType="phone-pad" help="Used for booking updates and appointment contact."/></Surface>
    <Surface style={s.note}><View style={s.noteIcon}><QFIcon name="profile" size={24}/></View><View style={{flex:1}}><Text style={s.noteTitle}>Synced to your account</Text><Text style={s.noteText}>Changes update your QuincyFadez account and will pre-fill future bookings on this device.</Text></View></Surface>
    <PrimaryButton title={saving?"Saving…":"SAVE CHANGES"} subtitle="Update your QuincyFadez account" onPress={save} disabled={saving||!name.trim()||!email.trim()||!phone.trim()} style={s.primary} right={<QFIcon name="check" size={21} color="#090704"/>}/>
  </ScrollView></SafeAreaView></Marble>;
}

const s=StyleSheet.create({safe:{flex:1},content:{paddingHorizontal:18,paddingTop:4,paddingBottom:86},saved:{height:48,borderRadius:14,borderWidth:1,borderColor:"rgba(85,216,117,.22)",backgroundColor:M.greenBg,alignItems:"center",justifyContent:"center",marginTop:8,marginBottom:12,flexDirection:"row",gap:8},savedText:{color:M.green,fontSize:12.5,fontWeight:"700"},error:{borderRadius:14,borderWidth:1,borderColor:"rgba(240,125,115,.24)",backgroundColor:M.redBg,padding:14,marginTop:8,marginBottom:12},errorText:{color:M.red,fontSize:12.5,lineHeight:18},card:{padding:18,marginTop:9,backgroundColor:M.panel2,borderColor:M.warmBorderSoft},field:{marginBottom:18},label:{color:M.text2,fontSize:13,fontWeight:"700",marginBottom:8},input:{height:58,borderRadius:14,borderWidth:1,borderColor:M.border,backgroundColor:M.bg2,paddingHorizontal:15,color:M.text,fontSize:15.5},help:{color:M.muted2,fontSize:11.5,lineHeight:16,marginTop:7},note:{padding:18,marginTop:15,flexDirection:"row",gap:13,backgroundColor:M.panel2,borderColor:M.warmBorderSoft},noteIcon:{width:48,height:48,borderRadius:15,backgroundColor:M.panel3,borderWidth:1,borderColor:M.border,alignItems:"center",justifyContent:"center"},noteTitle:{color:M.text,fontSize:15.5,fontWeight:"700"},noteText:{color:M.muted,fontSize:12.5,lineHeight:18,marginTop:6},primary:{marginTop:18}});
