import React,{useCallback,useEffect,useMemo,useState} from "react";
import {ActivityIndicator,Alert,Linking,Pressable,SafeAreaView,ScrollView,Share,StatusBar,StyleSheet,Text,TextInput,View} from "react-native";
import AsyncStorage from "@react-native-async-storage/async-storage";
import {BrandLogo,M,Marble} from "./QFTheme";

const API=(process.env.EXPO_PUBLIC_API_URL||"").replace(/\/$/,"");
const TOKEN="quincyfadez.adminToken";
const BOOKING_URL="https://quincyfadez.com";
const GOLD="#E0AE4F";
const GOLD_SOFT="#F0C96D";
const CARD="#141414";
const CARD_2="#191919";
const LINE="rgba(255,255,255,.12)";
const WARM_LINE="rgba(224,174,79,.24)";
const NAV=[
  ["today","Dashboard","dashboard"],
  ["schedule","Schedule","calendar"],
  ["insights","Insights","insights"],
  ["clients","Clients","clients"],
  ["controls","More","menu"],
];
const read=r=>r.json().catch(()=>({}));
const money=v=>`£${Number(v||0).toFixed(Number(v||0)%1?2:0)}`;
const when=x=>x?.start_at||x?.start_at_utc||"";
const fmtTime=v=>v?new Date(v).toLocaleTimeString("en-GB",{hour:"numeric",minute:"2-digit",hour12:true,timeZone:"Europe/London"}).replace(":00",""):"—";
const fmtDate=v=>v?new Date(v).toLocaleDateString("en-GB",{weekday:"short",day:"numeric",month:"short",timeZone:"Europe/London"}):"—";
const dateKey=v=>String(v||"").slice(0,10);
const sortRows=a=>[...(a||[])].sort((x,y)=>String(when(x)).localeCompare(String(when(y))));
const waNumber=value=>{let n=String(value||"").replace(/\D/g,"");if(n.startsWith("0"))n=`44${n.slice(1)}`;return n};
const greeting=()=>{const h=new Date().getHours();return h<12?"Good morning":h<18?"Good afternoon":"Good evening"};
const initials=name=>String(name||"QF").trim().split(/\s+/).map(x=>x[0]).join("").slice(0,2).toUpperCase();

function Icon({name,size=25,color=GOLD}){
  if(name==="menu")return <View style={{width:size,height:size,justifyContent:"space-around",paddingVertical:4}}>{[0,1,2].map(i=><View key={i} style={{height:2,borderRadius:2,backgroundColor:color,width:i===1?size*.72:size,alignSelf:i===1?"flex-end":"auto"}}/>)}</View>;
  if(name==="insights")return <View style={{width:size,height:size,flexDirection:"row",alignItems:"flex-end",justifyContent:"space-between",paddingHorizontal:2}}>{[.36,.62,.86,.5].map((h,i)=><View key={i} style={{width:Math.max(3,size*.13),height:size*h,borderRadius:3,borderWidth:1.6,borderColor:color}}/>)}</View>;
  if(name==="dashboard")return <View style={{width:size,height:size,borderWidth:1.6,borderColor:color,borderRadius:4,padding:4,flexDirection:"row",alignItems:"flex-end",justifyContent:"space-between"}}>{[.45,.75,.58].map((h,i)=><View key={i} style={{width:3,height:(size-10)*h,borderRadius:2,backgroundColor:color}}/>)}</View>;
  if(name==="calendar")return <View style={{width:size,height:size,borderWidth:1.6,borderColor:color,borderRadius:4,marginTop:2}}><View style={{position:"absolute",left:4,right:4,top:6,height:1.5,backgroundColor:color}}/><View style={{position:"absolute",left:5,top:-4,width:2,height:7,borderRadius:2,backgroundColor:color}}/><View style={{position:"absolute",right:5,top:-4,width:2,height:7,borderRadius:2,backgroundColor:color}}/><View style={{position:"absolute",left:5,top:11,width:3,height:3,borderRadius:2,backgroundColor:color}}/><View style={{position:"absolute",left:11,top:11,width:3,height:3,borderRadius:2,backgroundColor:color}}/></View>;
  if(name==="clients")return <View style={{width:size,height:size}}><View style={{position:"absolute",left:4,top:1,width:size*.34,height:size*.34,borderRadius:size,borderWidth:1.6,borderColor:color}}/><View style={{position:"absolute",right:1,top:4,width:size*.27,height:size*.27,borderRadius:size,borderWidth:1.5,borderColor:color}}/><View style={{position:"absolute",left:0,bottom:0,width:size*.58,height:size*.43,borderTopLeftRadius:size,borderTopRightRadius:size,borderWidth:1.6,borderBottomWidth:0,borderColor:color}}/><View style={{position:"absolute",right:0,bottom:1,width:size*.42,height:size*.35,borderTopLeftRadius:size,borderTopRightRadius:size,borderWidth:1.5,borderBottomWidth:0,borderColor:color}}/></View>;
  if(name==="clock")return <View style={{width:size,height:size,borderRadius:size,borderWidth:1.6,borderColor:color}}><View style={{position:"absolute",left:size/2-1,top:4,width:1.6,height:size*.32,backgroundColor:color}}/><View style={{position:"absolute",left:size/2-1,top:size/2-1,width:size*.25,height:1.6,backgroundColor:color,transform:[{rotate:"28deg"}],transformOrigin:"left"}}/></View>;
  if(name==="search")return <View style={{width:size,height:size}}><View style={{position:"absolute",left:1,top:1,width:size*.62,height:size*.62,borderRadius:size,borderWidth:1.6,borderColor:color}}/><View style={{position:"absolute",right:1,bottom:3,width:size*.4,height:1.7,borderRadius:2,backgroundColor:color,transform:[{rotate:"45deg"}]}}/></View>;
  const glyph={refresh:"↻",money:"£",repeat:"↻",noshow:"⊗",scissors:"✂︎",beard:"♙",sparkle:"✦",message:"◌",share:"↗",chevron:"›",check:"✓",x:"×",settings:"⚙︎",bell:"◉",wait:"⌛︎"}[name]||"•";
  return <Text style={{color,fontSize:size,fontWeight:"400",lineHeight:size+2}}>{glyph}</Text>;
}

function ShellCard({children,style}){return <View style={[s.card,style]}>{children}</View>}
function BottomNav({tab,setTab}){return <SafeAreaView style={s.navSafe}><View style={s.nav}>{NAV.map(([key,label,icon])=>{const active=key===tab;return <Pressable key={key} onPress={()=>setTab(key)} style={s.navItem}><Icon name={icon} size={24} color={active?GOLD_SOFT:"#A8A8A8"}/><Text style={[s.navLabel,active&&s.navLabelOn]}>{label}</Text></Pressable>})}</View></SafeAreaView>}
function Header({title,sub,onMenu,onRefresh}){return <View style={s.header}><Pressable onPress={onRefresh} style={s.headerSide}><Icon name="refresh" size={25} color="#E8E8E8"/></Pressable><View style={s.headerCenter}><Text style={s.headerTitle}>{title}</Text>{sub?<Text style={s.headerSub}>{sub}</Text>:null}</View><Pressable onPress={onMenu} style={s.headerSide}><Icon name="menu" size={25}/></Pressable></View>}
function Section({title,action,onAction}){return <View style={s.sectionHead}><Text style={s.sectionTitle}>{title}</Text>{action?<Pressable onPress={onAction}><Text style={s.sectionAction}>{action}</Text></Pressable>:null}</View>}
function ErrorBox({text}){return text?<View style={s.error}><Text style={s.errorText}>{text}</Text></View>:null}
function Empty({title,text}){return <ShellCard style={s.empty}><Text style={s.emptyTitle}>{title}</Text><Text style={s.emptyText}>{text}</Text></ShellCard>}
function Delta({value,label="vs last week",invert=false}){if(value===null||value===undefined)return <Text style={s.deltaNeutral}>No comparison yet</Text>;const n=Number(value||0),good=invert?n<=0:n>=0;return <Text style={[s.delta,good?s.deltaGood:s.deltaBad]}>{n>0?"+":""}{n}% <Text style={s.deltaNeutral}>{label}</Text></Text>}
function MetricCard({label,value,icon,note,delta,invert=false}){return <ShellCard style={s.metricCard}><View style={s.metricTop}><Text style={s.metricLabel}>{label}</Text><Icon name={icon} size={31}/></View><Text numberOfLines={1} adjustsFontSizeToFit style={s.metricValue}>{value}</Text>{delta!==undefined?<Delta value={delta} invert={invert}/>:<Text style={s.metricNote}>{note}</Text>}</ShellCard>}
function Status({value}){const v=String(value||"confirmed"),bad=["cancelled","expired","no_show"].includes(v),warn=v==="pending",done=v==="completed";return <View style={s.status}><View style={[s.statusDot,{backgroundColor:bad?M.red:warn?GOLD:done?GOLD_SOFT:M.green}]}/><Text style={[s.statusText,bad&&{color:M.red},warn&&{color:GOLD_SOFT}]}>{v.replaceAll("_"," ").toUpperCase()}</Text></View>}
function Appointment({item,onStatus,busy,compact=false}){const t=when(item),pending=item.status==="pending",confirmed=item.status==="confirmed",number=waNumber(item.customer_phone);return <ShellCard style={s.appointment}><View style={s.appTop}><View style={s.timeBadge}><Text style={s.timeText}>{fmtTime(t)}</Text><Text style={s.timeSmall}>{item.duration_minutes||"—"} MIN</Text></View><View style={{flex:1,minWidth:0}}><Text numberOfLines={1} style={s.clientName}>{item.customer_name||"Client"}</Text><Text numberOfLines={1} style={s.serviceText}>{item.service||"Appointment"} · {money(item.price)}</Text>{!compact?<Text style={s.dateText}>{fmtDate(t)}</Text>:null}</View><Status value={item.status}/></View>{!compact&&(pending||confirmed||number)?<View style={s.appActions}>{pending?<><Pressable disabled={busy} onPress={()=>onStatus(item,"confirmed")} style={s.goldAction}><Text style={s.goldActionText}>Approve</Text></Pressable><Pressable disabled={busy} onPress={()=>onStatus(item,"cancelled")} style={s.darkAction}><Text style={[s.darkActionText,{color:M.red}]}>Decline</Text></Pressable></>:confirmed?<><Pressable disabled={busy} onPress={()=>onStatus(item,"completed")} style={s.darkAction}><Text style={s.darkActionText}>Complete</Text></Pressable><Pressable disabled={busy} onPress={()=>onStatus(item,"no_show")} style={s.darkAction}><Text style={s.darkActionText}>No-show</Text></Pressable></>:null}{number?<Pressable onPress={()=>Linking.openURL(`https://wa.me/${number}`).catch(()=>{})} style={s.iconAction}><Icon name="message" size={22}/></Pressable>:null}</View>:null}</ShellCard>}
function ServiceIcon({name}){const lower=String(name||"").toLowerCase();return <Icon name={lower.includes("beard")?"beard":lower.includes("shape")?"sparkle":"scissors"} size={25}/>}
function Toggle({value,onPress,disabled}){return <Pressable disabled={disabled} onPress={onPress} style={[s.toggle,value&&s.toggleOn,disabled&&{opacity:.45}]}><View style={[s.knob,value&&s.knobOn]}/></Pressable>}
function ControlRow({icon,title,sub,right,onPress,last=false}){const body=<View style={[s.controlRow,!last&&s.controlLine]}><View style={s.controlIcon}><Icon name={icon} size={22}/></View><View style={{flex:1}}><Text style={s.controlTitle}>{title}</Text>{sub?<Text style={s.controlSub}>{sub}</Text>:null}</View>{right||<Icon name="chevron" size={26}/>}</View>;return onPress?<Pressable onPress={onPress}>{body}</Pressable>:body}
function ClientCard({item}){const number=waNumber(item.phone);return <ShellCard style={s.clientCard}><View style={s.avatar}><Text style={s.avatarText}>{initials(item.name)}</Text></View><View style={{flex:1,minWidth:0}}><View style={s.clientTitleRow}><Text numberOfLines={1} style={s.clientCardName}>{item.name||"Client"}</Text>{item.regular?<Text style={s.regular}>REGULAR</Text>:null}</View><Text style={s.clientMeta}>{item.completed_count||0} visits · {money(item.total_spend||0)} spend</Text><Text numberOfLines={1} style={s.clientMeta}>{item.phone||item.email||"No contact details"}</Text></View>{number?<Pressable onPress={()=>Linking.openURL(`https://wa.me/${number}`).catch(()=>{})} style={s.clientMessage}><Icon name="message" size={22}/></Pressable>:null}</ShellCard>}
function Bar({value,max}){const width=max?Math.max(8,Math.round((Number(value||0)/max)*100)):8;return <View style={s.barTrack}><View style={[s.barFill,{width:`${width}%`}]}/></View>}

export default function QFAdminScreen({onExit}){
  const[token,setToken]=useState(""),[checking,setChecking]=useState(true),[tab,setTab]=useState("today"),[loading,setLoading]=useState(false),[saving,setSaving]=useState(""),[error,setError]=useState(""),[overview,setOverview]=useState(null),[requests,setRequests]=useState([]),[bookings,setBookings]=useState([]),[selectedDate,setSelectedDate]=useState(""),[week,setWeek]=useState(null),[clients,setClients]=useState([]),[search,setSearch]=useState(""),[settings,setSettings]=useState(null),[services,setServices]=useState([]),[busy,setBusy]=useState("");
  useEffect(()=>{AsyncStorage.getItem(TOKEN).then(v=>{setToken(v||"");setChecking(false)}).catch(()=>setChecking(false))},[]);
  const request=useCallback(async(path,opt={})=>{if(!API||!token)throw new Error("Owner connection is unavailable.");const r=await fetch(`${API}${path}`,{...opt,headers:{"Content-Type":"application/json",Authorization:`Bearer ${token}`,...(opt.headers||{})}}),d=await read(r);if(r.status===401){await AsyncStorage.removeItem(TOKEN);setToken("");onExit?.();throw new Error("Your owner session expired.")}if(!r.ok)throw new Error(typeof d.detail==="string"?d.detail:"That action could not be completed.");return d},[token,onExit]);
  const load=useCallback(async()=>{if(!token)return;setLoading(true);setError("");try{if(tab==="today"){const[o,r]=await Promise.all([request("/api/admin/overview"),request("/api/admin/booking-requests")]);o.appointments=sortRows(o.appointments||[]);setOverview(o);setRequests(sortRows(r.bookings||[]))}else if(tab==="schedule"){const d=await request("/api/admin/bookings?days=31"),rows=sortRows(d.bookings||[]);setBookings(rows);setSelectedDate(v=>v||dateKey(when(rows[0]))||new Date().toISOString().slice(0,10))}else if(tab==="insights")setWeek(await request("/api/admin/insights-v2?period=week"));else if(tab==="clients")setClients((await request("/api/admin/clients")).clients||[]);else{const d=await request("/api/admin/settings");setSettings(d.settings||{});setServices(d.services||[])}}catch(e){setError(e.message)}finally{setLoading(false)}},[token,tab,request]);
  useEffect(()=>{load()},[load]);
  const saveSettings=async patch=>{if(saving)return;const key=Object.keys(patch)[0]||"settings";setSaving(key);setError("");try{const d=await request("/api/admin/settings",{method:"PUT",body:JSON.stringify(patch)});setSettings(d.settings||settings)}catch(e){setError(e.message)}finally{setSaving("")}};
  const setStatus=async(item,status)=>{if(busy)return;const run=async()=>{setBusy(item.id);setError("");try{await request(`/api/admin/bookings/${item.id}/status`,{method:"PATCH",body:JSON.stringify({status})});await load()}catch(e){setError(e.message)}finally{setBusy("")}};if(["cancelled","no_show"].includes(status))return Alert.alert(status==="cancelled"?"Decline booking?":"Mark as no-show?",status==="cancelled"?"This releases the appointment slot.":"This marks the client as a no-show.",[{text:"Go back",style:"cancel"},{text:"Confirm",style:"destructive",onPress:run}]);await run()};
  const logout=async()=>{try{await request("/api/admin/logout",{method:"POST"})}catch(_){}await AsyncStorage.removeItem(TOKEN);onExit?.()};
  const dates=useMemo(()=>[...new Set(bookings.map(x=>dateKey(when(x))).filter(Boolean))].slice(0,14),[bookings]);
  const shown=useMemo(()=>bookings.filter(x=>dateKey(when(x))===selectedDate),[bookings,selectedDate]);
  const filtered=useMemo(()=>{const q=search.trim().toLowerCase();return q?clients.filter(c=>[c.name,c.phone,c.email].some(v=>String(v||"").toLowerCase().includes(q))):clients},[clients,search]);
  const title=tab==="today"?"Dashboard":tab==="schedule"?"Schedule":tab==="insights"?"Insights":tab==="clients"?"Clients":"More";
  const subtitle=tab==="today"?"Business performance at a glance.":tab==="schedule"?"Appointments and booking requests.":tab==="insights"?"Business performance at a glance.":tab==="clients"?"Your client book and visit history.":"Booking controls and business settings.";
  if(checking)return <Marble><View style={s.center}><BrandLogo size={68}/><ActivityIndicator color={GOLD} style={{marginTop:20}}/></View></Marble>;
  if(!token)return null;

  let content=null;
  if(tab==="today")content=<>
    <View style={s.ownerIntro}><View><Text style={s.ownerKicker}>OWNER DASHBOARD</Text><Text style={s.ownerGreeting}>{greeting()}, Quincy</Text></View><BrandLogo size={50}/></View>
    <View style={s.metricsGrid}><MetricCard label="TODAY'S REVENUE" value={money(overview?.today_revenue)} icon="money" note="Completed today"/><MetricCard label="BOOKINGS TODAY" value={overview?.today_bookings??0} icon="calendar" note="Appointments"/><MetricCard label="NEW CLIENTS" value={overview?.new_clients??0} icon="clients" note="First visits today"/><MetricCard label="CAPACITY" value={overview?.utilisation_percent==null?"—":`${overview.utilisation_percent}%`} icon="insights" note="Booked capacity"/></View>
    {overview?.next_booking?<><Section title="UP NEXT"/><ShellCard style={s.featureCard}><View style={s.featureTop}><View style={{flex:1}}><Text style={s.featureKicker}>NEXT CLIENT · {fmtTime(when(overview.next_booking))}</Text><Text style={s.featureName}>{overview.next_booking.customer_name||"Client"}</Text><Text style={s.featureSub}>{overview.next_booking.service} · {money(overview.next_booking.price)}</Text></View><Icon name="scissors" size={36}/></View><View style={s.featureActions}>{waNumber(overview.next_booking.customer_phone)?<Pressable onPress={()=>Linking.openURL(`https://wa.me/${waNumber(overview.next_booking.customer_phone)}`).catch(()=>{})} style={s.darkWide}><Text style={s.darkWideText}>Message</Text></Pressable>:null}{overview.next_booking.customer_phone?<Pressable onPress={()=>Linking.openURL(`tel:${overview.next_booking.customer_phone}`).catch(()=>{})} style={s.darkWide}><Text style={s.darkWideText}>Call</Text></Pressable>:null}</View></ShellCard></>:null}
    {requests.length?<><Section title="BOOKING REQUESTS" action="View schedule" onAction={()=>setTab("schedule")}/><View style={s.stack}>{requests.slice(0,3).map(x=><Appointment key={x.id} item={x} onStatus={setStatus} busy={busy===x.id}/>)}</View></>:null}
    <Section title="TODAY'S SCHEDULE" action="View all" onAction={()=>setTab("schedule")}/>{overview?.appointments?.length?<View style={s.stack}>{overview.appointments.slice(0,6).map(x=><Appointment key={x.id} item={x} onStatus={setStatus} busy={busy===x.id} compact/>)}</View>:<Empty title="Your day is clear" text="Confirmed appointments will appear here in time order."/>}
    <ShellCard style={s.shareCard}><View style={{flex:1}}><Text style={s.shareTitle}>Share your booking link</Text><Text style={s.shareSub}>Send live QuincyFadez availability straight to a client.</Text></View><Pressable onPress={()=>Share.share({message:`Book QuincyFadez: ${BOOKING_URL}`})} style={s.shareButton}><Icon name="share" size={26}/></Pressable></ShellCard>
  </>;
  else if(tab==="schedule")content=<>
    {loading&&!bookings.length?<View style={s.loader}><ActivityIndicator color={GOLD}/></View>:<><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.dateStrip}>{dates.map(k=>{const d=new Date(`${k}T12:00:00`),active=k===selectedDate;return <Pressable key={k} onPress={()=>setSelectedDate(k)} style={[s.dateChip,active&&s.dateChipOn]}><Text style={[s.dateDow,active&&s.dateOn]}>{d.toLocaleDateString("en-GB",{weekday:"short"})}</Text><Text style={[s.dateNum,active&&s.dateOn]}>{d.getDate()}</Text><Text style={[s.dateMon,active&&s.dateOn]}>{d.toLocaleDateString("en-GB",{month:"short"})}</Text></Pressable>})}</ScrollView><Section title={selectedDate?new Date(`${selectedDate}T12:00:00`).toLocaleDateString("en-GB",{weekday:"long",day:"numeric",month:"long"}).toUpperCase():"APPOINTMENTS"}/>{shown.length?<View style={s.stack}>{shown.map(x=><Appointment key={x.id} item={x} onStatus={setStatus} busy={busy===x.id}/>)}</View>:<Empty title="No appointments" text="There are no bookings on this date."/>}</>}
  </>;
  else if(tab==="insights"){
    const c=week?.changes||{},servicesList=week?.service_breakdown||[],peaks=week?.peak_hours||[],maxPeak=Math.max(1,...peaks.map(x=>Number(x.bookings||0)));
    content=<>
      <View style={s.metricsGrid}><MetricCard label="THIS WEEK'S REVENUE" value={money(week?.revenue)} icon="money" delta={c.revenue_percent}/><MetricCard label="BOOKINGS THIS WEEK" value={week?.bookings??0} icon="calendar" delta={c.bookings_percent}/><MetricCard label="REPEAT CLIENTS" value={`${Number(week?.repeat_clients_percent||0).toFixed(0)}%`} icon="repeat" delta={c.repeat_clients_percent_points}/><MetricCard label="NO-SHOWS" value={week?.no_shows??0} icon="noshow" note={c.no_shows_delta==null?"This week":c.no_shows_delta===0?"Same as last week":c.no_shows_delta<0?"Down from last week":"Up from last week"}/></View>
      <Section title="TOP SERVICES"/>
      <ShellCard style={s.listCard}>{servicesList.length?servicesList.slice(0,4).map((item,i)=><View key={`${item.name}-${i}`} style={[s.serviceRankRow,i<Math.min(servicesList.length,4)-1&&s.rowDivider]}><View style={s.rankCircle}><Text style={s.rankText}>{i+1}</Text></View><View style={s.serviceRankIcon}><ServiceIcon name={item.name}/></View><View style={{flex:1}}><Text style={s.rankName}>{item.name}</Text><Text style={s.rankSub}>{item.bookings} bookings</Text></View><Text style={s.rankRevenue}>{money(item.revenue)}</Text><Icon name="chevron" size={24}/></View>):<View style={s.inlineEmpty}><Text style={s.emptyText}>Completed bookings will build your service rankings.</Text></View>}</ShellCard>
      <Section title="PEAK HOURS"/>
      <ShellCard style={s.listCard}>{peaks.length?peaks.map((item,i)=><View key={`${item.label}-${i}`} style={[s.peakRow,i<peaks.length-1&&s.rowDivider]}><Icon name="clock" size={25}/><Text style={s.peakLabel}>{item.label}</Text><View style={{flex:1}}><Bar value={item.bookings} max={maxPeak}/></View><Text style={s.peakValue}>{item.bookings} bookings</Text></View>):<View style={s.inlineEmpty}><Text style={s.emptyText}>Peak booking times will appear here.</Text></View>}</ShellCard>
      <Section title="CLIENT INSIGHTS"/>
      <View style={s.metricsGrid}><MetricCard label="NEW CLIENTS THIS WEEK" value={week?.new_clients??0} icon="clients" delta={c.new_clients_percent}/><MetricCard label="AVERAGE SPEND" value={money(week?.average_booking_value)} icon="insights" delta={c.average_booking_value_percent}/></View>
    </>;
  }
  else if(tab==="clients")content=<>
    <View style={s.searchBox}><Icon name="search" size={20} color="#AFAFAF"/><TextInput value={search} onChangeText={setSearch} placeholder="Search clients" placeholderTextColor="#777" style={s.searchInput}/><Text style={s.searchCount}>{filtered.length}</Text></View>
    <Section title="CLIENT DIRECTORY"/><View style={s.stack}>{filtered.length?filtered.map((x,i)=><ClientCard key={x.id||x.client_key||`${x.name}-${i}`} item={x}/>):<Empty title="No clients found" text="Try a different name, phone number or email address."/>}</View>
  </>;
  else content=<>
    <Section title="BOOKING CONTROLS"/>
    <ShellCard style={s.controlsCard}><ControlRow icon="check" title="Booking approval" sub="Approve requests before they become confirmed." right={<Toggle value={!!settings?.booking_approval_required} disabled={saving==="booking_approval_required"} onPress={()=>saveSettings({booking_approval_required:!settings?.booking_approval_required})}/>}/><ControlRow icon="wait" title="Waiting list" sub="Let clients request cancelled appointment slots." right={<Toggle value={!!settings?.waiting_list_enabled} disabled={saving==="waiting_list_enabled"} onPress={()=>saveSettings({waiting_list_enabled:!settings?.waiting_list_enabled})}/>}/><ControlRow icon="bell" title="Client notifications" sub="Allow automated booking notifications." right={<Toggle value={settings?.notifications_enabled!==false} disabled={saving==="notifications_enabled"} onPress={()=>saveSettings({notifications_enabled:settings?.notifications_enabled===false})}/>}/><ControlRow icon="clock" title="Minimum notice" sub={`${Math.round(Number(settings?.minimum_notice_minutes||0)/60)} hours before a new booking.`} onPress={()=>{const current=Number(settings?.minimum_notice_minutes||0);const options=[0,60,120,240,720,1440];const next=options[(options.indexOf(current)+1)%options.length]??0;saveSettings({minimum_notice_minutes:next})}}/><ControlRow icon="calendar" title="Slot frequency" sub={`Every ${settings?.slot_interval_minutes||30} minutes.`} onPress={()=>{const current=Number(settings?.slot_interval_minutes||30);const options=[15,20,30,45,60];const next=options[(options.indexOf(current)+1)%options.length]||30;saveSettings({slot_interval_minutes:next})}}/><ControlRow icon="clock" title="Cancellation notice" sub={`${settings?.cancellation_notice_hours||0} hours before appointment.`} onPress={()=>{const current=Number(settings?.cancellation_notice_hours||0);const options=[0,2,4,8,12,24,48];const next=options[(options.indexOf(current)+1)%options.length]??0;saveSettings({cancellation_notice_hours:next})}} last/></ShellCard>
    <Section title="SERVICES"/>
    <ShellCard style={s.listCard}>{services.length?services.map((item,i)=><View key={item.name||i} style={[s.serviceControlRow,i<services.length-1&&s.rowDivider]}><View style={s.serviceRankIcon}><ServiceIcon name={item.name}/></View><View style={{flex:1}}><Text style={s.controlTitle}>{item.name}</Text><Text style={s.controlSub}>{item.duration_minutes||item.duration||"—"} min · {money(item.price)}</Text></View></View>):<View style={s.inlineEmpty}><Text style={s.emptyText}>Your live service list will appear here.</Text></View>}</ShellCard>
    <Section title="OWNER"/>
    <ShellCard style={s.controlsCard}><ControlRow icon="share" title="Share booking link" sub="Send the QuincyFadez booking page." onPress={()=>Share.share({message:`Book QuincyFadez: ${BOOKING_URL}`})}/><ControlRow icon="refresh" title="Refresh dashboard" sub="Reload live owner data." onPress={load}/><ControlRow icon="x" title="Sign out" sub="End this owner session on this device." onPress={logout} last/></ShellCard>
  </>;

  return <Marble><StatusBar barStyle="light-content" backgroundColor="#050505"/><SafeAreaView style={s.safe}><Header title={title} sub={subtitle} onRefresh={load} onMenu={()=>setTab("controls")}/><ScrollView contentContainerStyle={s.content} showsVerticalScrollIndicator={false}><ErrorBox text={error}/>{loading&&!overview&&tab==="today"?<View style={s.loader}><ActivityIndicator color={GOLD}/></View>:content}</ScrollView><BottomNav tab={tab} setTab={setTab}/></SafeAreaView></Marble>;
}

const s=StyleSheet.create({
  safe:{flex:1,backgroundColor:"#050505"},
  center:{flex:1,alignItems:"center",justifyContent:"center",backgroundColor:"#050505"},
  header:{minHeight:92,paddingHorizontal:18,paddingTop:8,paddingBottom:12,flexDirection:"row",alignItems:"center",borderBottomWidth:1,borderBottomColor:"rgba(255,255,255,.07)",backgroundColor:"#050505"},
  headerSide:{width:48,height:48,alignItems:"center",justifyContent:"center"},
  headerCenter:{flex:1,alignItems:"center",paddingHorizontal:6},
  headerTitle:{color:"#F5F5F3",fontSize:27,fontWeight:"600",letterSpacing:-.5},
  headerSub:{color:"#A8A8A8",fontSize:13.5,lineHeight:18,marginTop:7,textAlign:"center"},
  content:{paddingHorizontal:16,paddingTop:18,paddingBottom:124},
  card:{backgroundColor:CARD,borderRadius:18,borderWidth:1,borderColor:LINE,shadowColor:"#000",shadowOpacity:.38,shadowRadius:13,shadowOffset:{width:0,height:7},elevation:5},
  ownerIntro:{flexDirection:"row",alignItems:"center",justifyContent:"space-between",marginBottom:17,paddingHorizontal:2},
  ownerKicker:{color:GOLD_SOFT,fontSize:11,fontWeight:"800",letterSpacing:1.2},
  ownerGreeting:{color:"#F6F5F1",fontSize:26,fontWeight:"650",marginTop:6,letterSpacing:-.45},
  metricsGrid:{flexDirection:"row",flexWrap:"wrap",gap:10},
  metricCard:{width:"48.55%",minHeight:157,padding:16,justifyContent:"space-between",borderColor:WARM_LINE,backgroundColor:"#151515"},
  metricTop:{flexDirection:"row",alignItems:"flex-start",justifyContent:"space-between",gap:8},
  metricLabel:{color:"#D7D7D7",fontSize:11.5,fontWeight:"650",lineHeight:15,flex:1},
  metricValue:{color:"#F7F7F5",fontSize:33,fontWeight:"500",letterSpacing:-.9,marginTop:8},
  metricNote:{color:"#A9A9A9",fontSize:12.5,lineHeight:17,marginTop:8},
  delta:{fontSize:12.5,fontWeight:"700",marginTop:8},deltaGood:{color:"#67D783"},deltaBad:{color:"#F08E86"},deltaNeutral:{color:"#A7A7A7",fontWeight:"500"},
  sectionHead:{flexDirection:"row",alignItems:"center",justifyContent:"space-between",marginTop:25,marginBottom:10,paddingHorizontal:2},
  sectionTitle:{color:"#F0EFEB",fontSize:16,fontWeight:"650",letterSpacing:.2},
  sectionAction:{color:GOLD_SOFT,fontSize:13.5,fontWeight:"650"},
  featureCard:{padding:17,borderColor:WARM_LINE},featureTop:{flexDirection:"row",alignItems:"flex-start",gap:15},featureKicker:{color:GOLD_SOFT,fontSize:10.5,fontWeight:"800",letterSpacing:.75},featureName:{color:"#F7F7F5",fontSize:26,fontWeight:"600",marginTop:8},featureSub:{color:"#B5B5B5",fontSize:14,marginTop:6},featureActions:{flexDirection:"row",gap:9,marginTop:17,paddingTop:15,borderTopWidth:1,borderTopColor:LINE},darkWide:{flex:1,height:47,borderRadius:13,borderWidth:1,borderColor:LINE,backgroundColor:CARD_2,alignItems:"center",justifyContent:"center"},darkWideText:{color:"#F0F0ED",fontSize:13.5,fontWeight:"650"},
  stack:{gap:10},
  appointment:{padding:14,borderColor:"rgba(224,174,79,.17)"},appTop:{flexDirection:"row",alignItems:"center",gap:12},timeBadge:{width:68,minHeight:58,borderRadius:13,borderWidth:1,borderColor:WARM_LINE,backgroundColor:"#101010",alignItems:"center",justifyContent:"center",paddingHorizontal:5},timeText:{color:GOLD_SOFT,fontSize:14,fontWeight:"750"},timeSmall:{color:"#8F8F8F",fontSize:8.5,fontWeight:"800",marginTop:5,letterSpacing:.4},clientName:{color:"#F3F3F0",fontSize:16,fontWeight:"650"},serviceText:{color:"#B7B7B7",fontSize:12.5,marginTop:4},dateText:{color:"#848484",fontSize:11.5,marginTop:4},status:{alignItems:"flex-end",gap:6,maxWidth:76},statusDot:{width:7,height:7,borderRadius:4},statusText:{color:"#C8C8C8",fontSize:8.5,fontWeight:"800",letterSpacing:.4,textAlign:"right"},appActions:{flexDirection:"row",gap:8,marginTop:13,paddingTop:12,borderTopWidth:1,borderTopColor:LINE},goldAction:{flex:1,height:42,borderRadius:12,backgroundColor:GOLD,borderWidth:1,borderColor:GOLD_SOFT,alignItems:"center",justifyContent:"center"},goldActionText:{color:"#171208",fontSize:12.5,fontWeight:"850"},darkAction:{flex:1,height:42,borderRadius:12,borderWidth:1,borderColor:LINE,backgroundColor:"#1A1A1A",alignItems:"center",justifyContent:"center"},darkActionText:{color:"#E4E4E1",fontSize:12.5,fontWeight:"700"},iconAction:{width:42,height:42,borderRadius:12,borderWidth:1,borderColor:LINE,backgroundColor:"#1A1A1A",alignItems:"center",justifyContent:"center"},
  shareCard:{marginTop:22,padding:16,flexDirection:"row",alignItems:"center",gap:13,borderColor:WARM_LINE},shareTitle:{color:"#F2F2EF",fontSize:15.5,fontWeight:"650"},shareSub:{color:"#9C9C9C",fontSize:12,lineHeight:17,marginTop:4},shareButton:{width:50,height:50,borderRadius:14,borderWidth:1,borderColor:WARM_LINE,backgroundColor:"#191919",alignItems:"center",justifyContent:"center"},
  dateStrip:{gap:9,paddingRight:16,paddingBottom:6},dateChip:{width:68,height:89,borderRadius:17,borderWidth:1,borderColor:LINE,backgroundColor:CARD,alignItems:"center",justifyContent:"center"},dateChipOn:{borderColor:GOLD,backgroundColor:"#1B1710"},dateDow:{color:"#9A9A9A",fontSize:10.5,fontWeight:"700"},dateNum:{color:"#EAEAE7",fontSize:23,fontWeight:"600",marginVertical:4},dateMon:{color:"#8C8C8C",fontSize:10.5},dateOn:{color:GOLD_SOFT},
  listCard:{overflow:"hidden",borderColor:WARM_LINE},rowDivider:{borderBottomWidth:1,borderBottomColor:LINE},serviceRankRow:{minHeight:81,paddingHorizontal:15,paddingVertical:12,flexDirection:"row",alignItems:"center",gap:12},rankCircle:{width:38,height:38,borderRadius:19,borderWidth:1.5,borderColor:GOLD,alignItems:"center",justifyContent:"center"},rankText:{color:GOLD_SOFT,fontSize:16,fontWeight:"650"},serviceRankIcon:{width:38,height:38,alignItems:"center",justifyContent:"center"},rankName:{color:"#F2F2EF",fontSize:16,fontWeight:"600"},rankSub:{color:"#9E9E9E",fontSize:11.5,marginTop:4},rankRevenue:{color:"#F0F0ED",fontSize:17,fontWeight:"550",marginRight:2},
  peakRow:{minHeight:62,paddingHorizontal:15,flexDirection:"row",alignItems:"center",gap:12},peakLabel:{color:"#E5E5E2",fontSize:13.5,width:90},peakValue:{color:"#E5E5E2",fontSize:12.5,width:76,textAlign:"right"},barTrack:{height:10,borderRadius:5,backgroundColor:"#252525",overflow:"hidden"},barFill:{height:"100%",borderRadius:5,backgroundColor:GOLD},
  searchBox:{height:54,borderRadius:16,borderWidth:1,borderColor:LINE,backgroundColor:CARD,flexDirection:"row",alignItems:"center",paddingHorizontal:15,gap:11},searchInput:{flex:1,color:"#F1F1EE",fontSize:15},searchCount:{color:GOLD_SOFT,fontSize:12,fontWeight:"700"},clientCard:{padding:14,flexDirection:"row",alignItems:"center",gap:12},avatar:{width:50,height:50,borderRadius:25,borderWidth:1,borderColor:WARM_LINE,backgroundColor:"#1B1710",alignItems:"center",justifyContent:"center"},avatarText:{color:GOLD_SOFT,fontSize:15,fontWeight:"800"},clientTitleRow:{flexDirection:"row",alignItems:"center",gap:7},clientCardName:{color:"#F1F1EF",fontSize:16,fontWeight:"650",maxWidth:"76%"},regular:{color:"#171208",backgroundColor:GOLD_SOFT,borderRadius:8,overflow:"hidden",paddingHorizontal:7,paddingVertical:3,fontSize:8,fontWeight:"850"},clientMeta:{color:"#9D9D9D",fontSize:11.5,marginTop:4},clientMessage:{width:43,height:43,borderRadius:13,borderWidth:1,borderColor:LINE,backgroundColor:"#191919",alignItems:"center",justifyContent:"center"},
  controlsCard:{overflow:"hidden",borderColor:WARM_LINE},controlRow:{minHeight:78,paddingHorizontal:14,paddingVertical:11,flexDirection:"row",alignItems:"center",gap:12},controlLine:{borderBottomWidth:1,borderBottomColor:LINE},controlIcon:{width:42,height:42,alignItems:"center",justifyContent:"center"},controlTitle:{color:"#EFEFEC",fontSize:14.5,fontWeight:"650"},controlSub:{color:"#9B9B9B",fontSize:11.5,lineHeight:16,marginTop:4,paddingRight:8},toggle:{width:50,height:29,borderRadius:15,backgroundColor:"#2A2A2A",borderWidth:1,borderColor:LINE,padding:3,justifyContent:"center"},toggleOn:{backgroundColor:GOLD,borderColor:GOLD_SOFT},knob:{width:21,height:21,borderRadius:11,backgroundColor:"#A5A5A5"},knobOn:{alignSelf:"flex-end",backgroundColor:"#171208"},serviceControlRow:{minHeight:68,paddingHorizontal:14,paddingVertical:10,flexDirection:"row",alignItems:"center",gap:10},
  inlineEmpty:{padding:20,alignItems:"center"},empty:{padding:20,alignItems:"center"},emptyTitle:{color:"#EFEFEC",fontSize:16,fontWeight:"650"},emptyText:{color:"#979797",fontSize:12.5,lineHeight:18,marginTop:6,textAlign:"center"},error:{borderRadius:13,borderWidth:1,borderColor:"rgba(240,142,134,.24)",backgroundColor:"#241414",padding:12,marginBottom:14},errorText:{color:"#F1A7A1",fontSize:12.5,lineHeight:17},loader:{height:170,alignItems:"center",justifyContent:"center"},
  navSafe:{position:"absolute",left:0,right:0,bottom:0,backgroundColor:"#080808",borderTopWidth:1,borderTopColor:"rgba(255,255,255,.12)"},nav:{height:78,flexDirection:"row",alignItems:"center",paddingHorizontal:7},navItem:{flex:1,height:70,alignItems:"center",justifyContent:"center",gap:6},navLabel:{color:"#A5A5A5",fontSize:10.5,fontWeight:"550"},navLabelOn:{color:GOLD_SOFT,fontWeight:"700"}
});