import React from "react";
import {StyleSheet,Text,View} from "react-native";
import {M} from "./QFTheme";

const stroke=(color,width=1.7)=>({borderColor:color,borderWidth:width});

export default function QFIcon({name,size=24,color=M.accent}){
  const c=color,s=size;
  if(name==="menu")return <View style={{width:s,height:s,justifyContent:"space-around",paddingVertical:s*.18}}>{[0,1,2].map(i=><View key={i} style={{height:1.8,borderRadius:2,backgroundColor:c,width:i===1?s*.72:s,alignSelf:i===1?"flex-end":"auto"}}/>)}</View>;
  if(name==="home"||name==="dashboard")return <View style={{width:s,height:s}}><View style={{position:"absolute",left:s*.18,right:s*.18,bottom:s*.08,height:s*.52,borderRadius:3,borderTopWidth:0,...stroke(c)}}/><View style={{position:"absolute",left:s*.18,top:s*.12,width:s*.64,height:s*.64,borderLeftWidth:1.7,borderTopWidth:1.7,borderColor:c,transform:[{rotate:"45deg"}],borderRadius:2}}/></View>;
  if(name==="calendar")return <View style={[{width:s,height:s,borderRadius:4,marginTop:1},stroke(c)]}><View style={{position:"absolute",left:s*.18,right:s*.18,top:s*.31,height:1.6,backgroundColor:c}}/><View style={{position:"absolute",left:s*.22,top:-s*.14,width:2,height:s*.3,borderRadius:2,backgroundColor:c}}/><View style={{position:"absolute",right:s*.22,top:-s*.14,width:2,height:s*.3,borderRadius:2,backgroundColor:c}}/><View style={{position:"absolute",left:s*.23,top:s*.52,width:s*.12,height:s*.12,borderRadius:2,backgroundColor:c}}/><View style={{position:"absolute",left:s*.44,top:s*.52,width:s*.12,height:s*.12,borderRadius:2,backgroundColor:c}}/><View style={{position:"absolute",left:s*.65,top:s*.52,width:s*.12,height:s*.12,borderRadius:2,backgroundColor:c}}/></View>;
  if(name==="scissors")return <View style={{width:s,height:s}}><View style={[styles.circle,{width:s*.34,height:s*.34,borderRadius:s,borderColor:c,left:0,bottom:0}]}/><View style={[styles.circle,{width:s*.34,height:s*.34,borderRadius:s,borderColor:c,right:0,bottom:0}]}/><View style={{position:"absolute",left:s*.28,top:s*.16,width:s*.62,height:1.8,borderRadius:2,backgroundColor:c,transform:[{rotate:"-35deg"}]}}/><View style={{position:"absolute",right:s*.28,top:s*.16,width:s*.62,height:1.8,borderRadius:2,backgroundColor:c,transform:[{rotate:"35deg"}]}}/></View>;
  if(name==="star")return <Text style={{color:c,fontSize:s*1.1,lineHeight:s*1.12,fontWeight:"300"}}>☆</Text>;
  if(name==="user"||name==="profile")return <View style={{width:s,height:s}}><View style={[styles.circle,{width:s*.38,height:s*.38,borderRadius:s,borderColor:c,left:s*.31,top:0}]}/><View style={{position:"absolute",left:s*.12,right:s*.12,bottom:0,height:s*.43,borderTopLeftRadius:s,borderTopRightRadius:s,borderWidth:1.7,borderBottomWidth:0,borderColor:c}}/></View>;
  if(name==="clients")return <View style={{width:s,height:s}}><View style={[styles.circle,{width:s*.32,height:s*.32,borderRadius:s,borderColor:c,left:s*.12,top:0}]}/><View style={[styles.circle,{width:s*.26,height:s*.26,borderRadius:s,borderColor:c,right:s*.03,top:s*.1}]}/><View style={{position:"absolute",left:0,bottom:0,width:s*.58,height:s*.43,borderTopLeftRadius:s,borderTopRightRadius:s,borderWidth:1.7,borderBottomWidth:0,borderColor:c}}/><View style={{position:"absolute",right:0,bottom:0,width:s*.42,height:s*.34,borderTopLeftRadius:s,borderTopRightRadius:s,borderWidth:1.5,borderBottomWidth:0,borderColor:c}}/></View>;
  if(name==="repeat")return <View style={{width:s,height:s}}><Text style={{color:c,fontSize:s*.98,lineHeight:s,fontWeight:"300"}}>↻</Text></View>;
  if(name==="hourglass")return <View style={{width:s,height:s,alignItems:"center"}}><View style={{width:s*.65,height:1.7,backgroundColor:c}}/><View style={{width:s*.65,height:s*.72,borderLeftWidth:1.7,borderRightWidth:1.7,borderColor:c,transform:[{skewX:"-18deg"}],justifyContent:"center"}}><View style={{alignSelf:"center",width:s*.2,height:s*.2,borderRadius:s,backgroundColor:c,opacity:.8}}/></View><View style={{width:s*.65,height:1.7,backgroundColor:c}}/></View>;
  if(name==="location")return <View style={{width:s,height:s,alignItems:"center"}}><View style={{width:s*.66,height:s*.78,borderTopLeftRadius:s,borderTopRightRadius:s,borderBottomLeftRadius:s*.8,borderBottomRightRadius:s*.8,borderWidth:1.7,borderColor:c,transform:[{rotate:"45deg"}],marginTop:s*.02}}/><View style={{position:"absolute",top:s*.2,width:s*.16,height:s*.16,borderRadius:s,backgroundColor:c}}/></View>;
  if(name==="message")return <View style={{width:s,height:s}}><View style={[{position:"absolute",left:s*.05,right:s*.05,top:s*.08,height:s*.68,borderRadius:s*.18},stroke(c)]}/><View style={{position:"absolute",left:s*.2,bottom:s*.06,width:s*.28,height:s*.28,borderLeftWidth:1.7,borderBottomWidth:1.7,borderColor:c,transform:[{rotate:"-35deg"}]}}/></View>;
  if(name==="bell")return <View style={{width:s,height:s,alignItems:"center"}}><View style={{width:s*.62,height:s*.66,borderTopLeftRadius:s,borderTopRightRadius:s,borderBottomLeftRadius:s*.18,borderBottomRightRadius:s*.18,borderWidth:1.7,borderColor:c,marginTop:s*.08}}/><View style={{width:s*.16,height:s*.08,borderRadius:s,backgroundColor:c,marginTop:2}}/></View>;
  if(name==="settings")return <View style={{width:s,height:s,alignItems:"center",justifyContent:"center"}}><View style={[styles.circle,{width:s*.72,height:s*.72,borderRadius:s,borderColor:c}]}/><View style={[styles.circle,{width:s*.24,height:s*.24,borderRadius:s,borderColor:c}]}/>{[0,45,90,135].map(a=><View key={a} style={{position:"absolute",width:s*.94,height:1.6,backgroundColor:c,transform:[{rotate:`${a}deg`}],opacity:.9}}/>)}</View>;
  if(name==="lock")return <View style={{width:s,height:s,alignItems:"center",justifyContent:"flex-end"}}><View style={{width:s*.72,height:s*.56,borderRadius:s*.12,borderWidth:1.7,borderColor:c}}/><View style={{position:"absolute",top:s*.02,width:s*.46,height:s*.48,borderTopLeftRadius:s,borderTopRightRadius:s,borderWidth:1.7,borderBottomWidth:0,borderColor:c}}/><View style={{position:"absolute",bottom:s*.18,width:3,height:s*.14,borderRadius:2,backgroundColor:c}}/></View>;
  if(name==="shield")return <View style={{width:s,height:s,alignItems:"center"}}><View style={{width:s*.72,height:s*.86,borderTopLeftRadius:s*.12,borderTopRightRadius:s*.12,borderBottomLeftRadius:s*.42,borderBottomRightRadius:s*.42,borderWidth:1.7,borderColor:c}}/></View>;
  if(name==="logout")return <View style={{width:s,height:s}}><View style={{position:"absolute",left:0,top:s*.08,width:s*.56,height:s*.84,borderWidth:1.7,borderRightWidth:0,borderColor:c,borderRadius:3}}/><View style={{position:"absolute",right:0,top:s*.48,width:s*.62,height:1.8,backgroundColor:c}}/><Text style={{position:"absolute",right:-1,top:s*.12,color:c,fontSize:s*.62,fontWeight:"300"}}>›</Text></View>;
  if(name==="clock")return <View style={[{width:s,height:s,borderRadius:s},stroke(c)]}><View style={{position:"absolute",left:s*.48,top:s*.18,width:1.7,height:s*.34,backgroundColor:c}}/><View style={{position:"absolute",left:s*.48,top:s*.49,width:s*.27,height:1.7,backgroundColor:c,transform:[{rotate:"28deg"}]}}/></View>;
  if(name==="check")return <Text style={{color:c,fontSize:s,lineHeight:s,fontWeight:"700"}}>✓</Text>;
  if(name==="card")return <View style={[{width:s,height:s*.72,borderRadius:4,marginTop:s*.12},stroke(c)]}><View style={{position:"absolute",left:0,right:0,top:s*.2,height:s*.13,backgroundColor:c}}/></View>;
  return <View style={[styles.fallback,{width:s,height:s,borderColor:c}]}><View style={{width:s*.28,height:s*.28,borderRadius:s,backgroundColor:c}}/></View>;
}

const styles=StyleSheet.create({
  circle:{position:"absolute",borderWidth:1.7},
  fallback:{borderWidth:1.7,borderRadius:6,alignItems:"center",justifyContent:"center"},
});
