import React,{useEffect,useState} from "react";
import {ActivityIndicator,Image,Linking,Pressable,SafeAreaView,ScrollView,StatusBar,StyleSheet,Text,View} from "react-native";
import {M,Marble,PrimaryButton,Surface} from "./QFTheme";
import {ClientHeader} from "./ClientLuxuryUI";
import QFIcon from "./QFIcons";

const API="https://quincyfadez.com/api/google-reviews",LEAVE="https://g.page/r/CbQwl91s8_vqEBM/review",VIEW="https://www.google.com/maps/search/?api=1&query=QuincyFadez%20Oxford";
const stars=n=>"★".repeat(Math.round(Number(n||0))).padEnd(5,"☆");
const open=u=>u&&Linking.openURL(u).catch(()=>{});

export default function QFReviewsScreen({onBack}){
  const[data,setData]=useState(null),[loading,setLoading]=useState(true),[error,setError]=useState(false);
  const load=async()=>{setLoading(true);setError(false);try{const r=await fetch(API,{cache:"no-store"});if(!r.ok)throw new Error();setData(await r.json())}catch{setError(true)}finally{setLoading(false)}};
  useEffect(()=>{load()},[]);
  const list=data?.reviews||[];
  return <Marble><SafeAreaView style={s.safe}><StatusBar barStyle="light-content"/><ScrollView contentContainerStyle={s.content} showsVerticalScrollIndicator={false}>
    <ClientHeader title="Reviews" subtitle="Live Google feedback from QuincyFadez clients." onBack={onBack}/>
    {loading?<Surface style={s.state}><ActivityIndicator color={M.accent}/><Text style={s.stateText}>Loading Google reviews…</Text></Surface>:error?<Surface style={s.state}><View style={s.icon}><QFIcon name="star" size={31}/></View><Text style={s.stateTitle}>Reviews are temporarily unavailable</Text><Text style={s.stateText}>The live Google feed could not be reached just now.</Text><Pressable onPress={load} style={s.retry}><Text style={s.retryText}>Try again</Text></Pressable></Surface>:<>
      <Surface style={s.score}><View style={{flex:1}}><Text style={s.kicker}>GOOGLE RATING</Text><View style={s.scoreLine}><Text style={s.scoreNumber}>{data?.rating?.toFixed?.(1)||data?.rating||"—"}</Text><QFIcon name="star" size={34}/></View><Text style={s.scoreStars}>{stars(data?.rating)}</Text><Text style={s.count}>{data?.reviewCount||0} verified Google reviews</Text></View><View style={s.scoreBadge}><Text style={s.scoreBadgeText}>G</Text></View></Surface>
      <View style={s.section}><Text style={s.sectionTitle}>RECENT FEEDBACK</Text><Pressable onPress={()=>open(VIEW)}><Text style={s.sectionLink}>View all</Text></Pressable></View>
      {list.length?list.map(r=><Surface key={r.id} style={s.reviewCard}><View style={s.authorRow}>{r.author?.photoUrl?<Image source={{uri:r.author.photoUrl}} style={s.avatar}/>:<View style={s.avatarFallback}><Text style={s.avatarText}>{String(r.author?.name||"G")[0]}</Text></View>}<View style={{flex:1}}><Text style={s.author}>{r.author?.name||"Google reviewer"}</Text><Text style={s.meta}>{r.relativeTime||"Google review"}</Text></View><Text style={s.stars}>{stars(r.rating)}</Text></View>{r.text?<Text style={s.review}>{r.text}</Text>:null}{r.sourceUrl?<Pressable onPress={()=>open(r.sourceUrl)} style={s.googleLink}><Text style={s.googleLinkText}>View on Google ›</Text></Pressable>:null}</Surface>):<Surface style={s.state}><Text style={s.stateTitle}>Live rating connected</Text><Text style={s.stateText}>Written review comments will appear here when Google provides them.</Text></Surface>}
    </>}
    <PrimaryButton title="LEAVE A GOOGLE REVIEW" subtitle="Share your QuincyFadez experience" onPress={()=>open(LEAVE)} style={s.primary} right={<QFIcon name="star" size={22} color="#090704"/>}/><Pressable onPress={()=>open(VIEW)} style={s.secondary}><Text style={s.secondaryText}>View all reviews on Google</Text><Text style={s.secondaryArrow}>›</Text></Pressable>
  </ScrollView></SafeAreaView></Marble>;
}

const s=StyleSheet.create({
  safe:{flex:1},content:{paddingHorizontal:18,paddingTop:4,paddingBottom:120},state:{minHeight:200,padding:26,alignItems:"center",justifyContent:"center",backgroundColor:M.panel2,borderColor:M.warmBorderSoft},stateText:{color:M.muted,fontSize:13.5,lineHeight:20,textAlign:"center",marginTop:9,maxWidth:310},stateTitle:{color:M.text,fontSize:20,fontWeight:"700",textAlign:"center",marginTop:14},icon:{width:58,height:58,borderRadius:17,backgroundColor:M.panel3,borderWidth:1,borderColor:M.border,alignItems:"center",justifyContent:"center"},retry:{height:48,borderRadius:14,borderWidth:1,borderColor:M.border,backgroundColor:M.panel3,paddingHorizontal:20,alignItems:"center",justifyContent:"center",marginTop:15},retryText:{color:M.text2,fontSize:12.5,fontWeight:"700"},score:{padding:20,flexDirection:"row",alignItems:"center",marginTop:8,backgroundColor:M.panel2,borderColor:M.warmBorderSoft},kicker:{color:M.text2,fontSize:11.5,fontWeight:"700",letterSpacing:.8},scoreLine:{flexDirection:"row",alignItems:"center",gap:11,marginTop:8},scoreNumber:{color:M.text,fontSize:45,fontWeight:"700",letterSpacing:-1.3},scoreStars:{color:M.accent,fontSize:14,letterSpacing:1.5,marginTop:4},count:{color:M.muted,fontSize:12.5,marginTop:8},scoreBadge:{width:62,height:62,borderRadius:18,backgroundColor:M.panel3,borderWidth:1,borderColor:M.border,alignItems:"center",justifyContent:"center"},scoreBadgeText:{color:M.accent,fontSize:24,fontWeight:"800"},section:{flexDirection:"row",alignItems:"center",justifyContent:"space-between",marginTop:30,marginBottom:12},sectionTitle:{color:M.text,fontSize:16.5,fontWeight:"800"},sectionLink:{color:M.accent,fontSize:14,fontWeight:"700"},reviewCard:{padding:18,marginBottom:12,backgroundColor:M.panel2,borderColor:M.warmBorderSoft},authorRow:{flexDirection:"row",alignItems:"center",gap:12},avatar:{width:46,height:46,borderRadius:15},avatarFallback:{width:46,height:46,borderRadius:15,backgroundColor:M.panel3,borderWidth:1,borderColor:M.border,alignItems:"center",justifyContent:"center"},avatarText:{color:M.accent,fontSize:16,fontWeight:"800"},author:{color:M.text,fontSize:15.5,fontWeight:"700"},meta:{color:M.muted,fontSize:11.5,marginTop:4},stars:{color:M.accent,fontSize:11.5,letterSpacing:.4},review:{color:M.text2,fontSize:14,lineHeight:21,marginTop:15},googleLink:{alignSelf:"flex-start",marginTop:14},googleLinkText:{color:M.accent,fontSize:12.5,fontWeight:"700"},primary:{marginTop:20},secondary:{height:54,borderRadius:15,borderWidth:1,borderColor:M.border,backgroundColor:M.panel2,alignItems:"center",justifyContent:"space-between",flexDirection:"row",paddingHorizontal:17,marginTop:10},secondaryText:{color:M.text2,fontSize:12.5,fontWeight:"700"},secondaryArrow:{color:M.accent,fontSize:23}
});
