import React,{useEffect,useState} from "react";
import {ActivityIndicator,Image,Linking,Pressable,SafeAreaView,ScrollView,StatusBar,StyleSheet,Text,View} from "react-native";
import {M,Marble,PrimaryButton,Surface} from "./QFTheme";
import {ClientHeader} from "./ClientLuxuryUI";

const API="https://quincyfadez.com/api/google-reviews",LEAVE="https://g.page/r/CbQwl91s8_vqEBM/review",VIEW="https://www.google.com/maps/search/?api=1&query=QuincyFadez%20Oxford";
const stars=n=>"★".repeat(Math.round(Number(n||0))).padEnd(5,"☆");
const open=u=>u&&Linking.openURL(u).catch(()=>{});

export default function QFReviewsScreen({onBack}){
  const[data,setData]=useState(null),[loading,setLoading]=useState(true),[error,setError]=useState(false);
  const load=async()=>{setLoading(true);setError(false);try{const r=await fetch(API,{cache:"no-store"});if(!r.ok)throw new Error();setData(await r.json())}catch{setError(true)}finally{setLoading(false)}};
  useEffect(()=>{load()},[]);
  const list=data?.reviews||[];
  return <Marble><SafeAreaView style={s.safe}><StatusBar barStyle="light-content"/><ScrollView contentContainerStyle={s.content} showsVerticalScrollIndicator={false}>
    <ClientHeader title="Reviews" subtitle="Live Google feedback from QuincyFadez clients." onBack={onBack}/>
    {loading?<Surface style={s.state}><ActivityIndicator color={M.accent}/><Text style={s.stateText}>Loading Google reviews…</Text></Surface>:error?<Surface style={s.state}><View style={s.icon}><Text style={s.iconText}>☆</Text></View><Text style={s.stateTitle}>Reviews are temporarily unavailable</Text><Text style={s.stateText}>The live Google feed could not be reached just now.</Text><Pressable onPress={load} style={s.retry}><Text style={s.retryText}>Try again</Text></Pressable></Surface>:<>
      <Surface style={s.score}><View style={{flex:1}}><Text style={s.kicker}>GOOGLE RATING</Text><View style={s.scoreLine}><Text style={s.scoreNumber}>{data?.rating?.toFixed?.(1)||data?.rating||"—"}</Text><Text style={s.scoreStar}>★</Text></View><Text style={s.scoreStars}>{stars(data?.rating)}</Text><Text style={s.count}>{data?.reviewCount||0} verified Google reviews</Text></View><View style={s.scoreBadge}><Text style={s.scoreBadgeText}>G</Text></View></Surface>
      <View style={s.section}><Text style={s.sectionTitle}>RECENT FEEDBACK</Text><Pressable onPress={()=>open(VIEW)}><Text style={s.sectionLink}>View all</Text></Pressable></View>
      {list.length?list.map(r=><Surface key={r.id} style={s.reviewCard}><View style={s.authorRow}>{r.author?.photoUrl?<Image source={{uri:r.author.photoUrl}} style={s.avatar}/>:<View style={s.avatarFallback}><Text style={s.avatarText}>{String(r.author?.name||"G")[0]}</Text></View>}<View style={{flex:1}}><Text style={s.author}>{r.author?.name||"Google reviewer"}</Text><Text style={s.meta}>{r.relativeTime||"Google review"}</Text></View><Text style={s.stars}>{stars(r.rating)}</Text></View>{r.text?<Text style={s.review}>{r.text}</Text>:null}{r.sourceUrl?<Pressable onPress={()=>open(r.sourceUrl)} style={s.googleLink}><Text style={s.googleLinkText}>View on Google ↗</Text></Pressable>:null}</Surface>):<Surface style={s.state}><Text style={s.stateTitle}>Live rating connected</Text><Text style={s.stateText}>Written review comments will appear here when Google provides them.</Text></Surface>}
    </>}
    <PrimaryButton title="Leave a Google review" subtitle="Share your QuincyFadez experience" onPress={()=>open(LEAVE)} style={s.primary}/><Pressable onPress={()=>open(VIEW)} style={s.secondary}><Text style={s.secondaryText}>View all reviews on Google</Text></Pressable>
  </ScrollView></SafeAreaView></Marble>;
}

const s=StyleSheet.create({
  safe:{flex:1},content:{paddingHorizontal:18,paddingTop:4,paddingBottom:124},state:{minHeight:180,padding:22,alignItems:"center",justifyContent:"center"},stateText:{color:M.muted,fontSize:10.5,lineHeight:16,textAlign:"center",marginTop:7,maxWidth:290},stateTitle:{color:M.text,fontSize:16,fontWeight:"700",textAlign:"center",marginTop:11},icon:{width:48,height:48,borderRadius:16,backgroundColor:"rgba(169,184,255,.10)",borderWidth:1,borderColor:"rgba(169,184,255,.16)",alignItems:"center",justifyContent:"center"},iconText:{color:M.accentSoft,fontSize:21},retry:{height:42,borderRadius:13,borderWidth:1,borderColor:"rgba(255,255,255,.09)",backgroundColor:"rgba(21,28,40,.72)",paddingHorizontal:17,alignItems:"center",justifyContent:"center",marginTop:13},retryText:{color:M.text2,fontSize:9.5,fontWeight:"700"},score:{padding:18,flexDirection:"row",alignItems:"center",marginTop:7},kicker:{color:M.muted,fontSize:8.5,fontWeight:"900",letterSpacing:1.15},scoreLine:{flexDirection:"row",alignItems:"center",gap:8,marginTop:5},scoreNumber:{color:M.text,fontSize:39,fontWeight:"800",letterSpacing:-1.4},scoreStar:{color:M.accentSoft,fontSize:24},scoreStars:{color:M.accentSoft,fontSize:11,letterSpacing:1.5,marginTop:2},count:{color:M.muted,fontSize:9.5,marginTop:6},scoreBadge:{width:54,height:54,borderRadius:18,backgroundColor:"rgba(169,184,255,.10)",borderWidth:1,borderColor:"rgba(169,184,255,.16)",alignItems:"center",justifyContent:"center"},scoreBadgeText:{color:M.accentSoft,fontSize:20,fontWeight:"900"},section:{flexDirection:"row",alignItems:"center",justifyContent:"space-between",marginTop:25,marginBottom:10},sectionTitle:{color:M.muted,fontSize:8.5,fontWeight:"900",letterSpacing:1.2},sectionLink:{color:M.accentSoft,fontSize:9.5,fontWeight:"700"},reviewCard:{padding:15,marginBottom:10},authorRow:{flexDirection:"row",alignItems:"center",gap:10},avatar:{width:40,height:40,borderRadius:14},avatarFallback:{width:40,height:40,borderRadius:14,backgroundColor:"rgba(169,184,255,.10)",borderWidth:1,borderColor:"rgba(169,184,255,.15)",alignItems:"center",justifyContent:"center"},avatarText:{color:M.accentSoft,fontWeight:"900"},author:{color:M.text,fontSize:12.5,fontWeight:"700"},meta:{color:M.muted,fontSize:8.8,marginTop:3},stars:{color:M.accentSoft,fontSize:9.2,letterSpacing:.4},review:{color:M.text2,fontSize:11,lineHeight:17,marginTop:13},googleLink:{alignSelf:"flex-start",marginTop:12},googleLinkText:{color:M.accentSoft,fontSize:8.5,fontWeight:"800"},primary:{marginTop:18},secondary:{height:50,borderRadius:15,borderWidth:1,borderColor:"rgba(255,255,255,.08)",backgroundColor:"rgba(21,28,40,.64)",alignItems:"center",justifyContent:"center",marginTop:9},secondaryText:{color:M.text2,fontSize:9.5,fontWeight:"700"}
});
