import React,{useEffect,useMemo,useState}from"react";
import{ActivityIndicator,Pressable,SafeAreaView,ScrollView,StatusBar,StyleSheet,Text,TextInput,View}from"react-native";
import AsyncStorage from"@react-native-async-storage/async-storage";
import{M,Marble,cardShadow}from"./MockupTheme";
import{ClientHeader,ClientSection}from"./ClientLuxuryUI";

const API_URL=(process.env.EXPO_PUBLIC_API_URL||"").replace(/\/$/,""),SESSION_STORAGE="quincyfadez.clientSession";
const statusLabel=v=>v==="notified"?"SLOT ALERT SENT":v==="booked"?"BOOKED":v==="cancelled"?"LEFT LIST":v==="expired"?"EXPIRED":"WAITING";
const readJson=r=>r.json().catch(()=>({}));

export default function WaitingListScreen({onBack}){
 const[session,setSession]=useState(null),[services,setServices]=useState([]),[entries,setEntries]=useState([]),[enabled,setEnabled]=useState(false),[service,setService]=useState(""),[preferredDate,setPreferredDate]=useState(""),[earliestTime,setEarliestTime]=useState(""),[latestTime,setLatestTime]=useState(""),[busy,setBusy]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState(""),[success,setSuccess]=useState("");
 const activeEntries=useMemo(()=>entries.filter(e=>["waiting","notified"].includes(e.status)),[entries]);
 const authedRequest=async(path,options={})=>{if(!session?.token)throw new Error("Log in to manage your waiting list.");const r=await fetch(`${API_URL}${path}`,{...options,headers:{"Content-Type":"application/json",Authorization:`Bearer ${session.token}`,...(options.headers||{})}}),d=await readJson(r);if(!r.ok)throw new Error(typeof d.detail==="string"?d.detail:"Waiting list could not be updated.");return d};
 const load=async saved=>{if(!API_URL||!saved?.token){setBusy(false);return}setBusy(true);setError("");try{const[sr,wr]=await Promise.all([fetch(`${API_URL}/api/booking/services`),fetch(`${API_URL}/api/waiting-list`,{headers:{Authorization:`Bearer ${saved.token}`}})]),sd=await readJson(sr),wd=await readJson(wr);if(!wr.ok)throw new Error(typeof wd.detail==="string"?wd.detail:"Waiting list could not be loaded.");const items=sd.services||[];setServices(items);setService(v=>v||items?.[0]?.name||"");setEntries(wd.entries||[]);setEnabled(Boolean(wd.enabled))}catch(e){setError(e.message||"Waiting list could not be loaded.")}finally{setBusy(false)}};
 useEffect(()=>{AsyncStorage.getItem(SESSION_STORAGE).then(saved=>{if(!saved)return null;const parsed=JSON.parse(saved);setSession(parsed);return load(parsed)}).catch(()=>setError("Your client session could not be opened.")).finally(()=>setBusy(false))},[]);
 const join=async()=>{if(!service||saving)return;setSaving(true);setError("");setSuccess("");try{const d=await authedRequest("/api/waiting-list",{method:"POST",body:JSON.stringify({service,preferred_date:preferredDate.trim()||null,earliest_time:earliestTime.trim()||null,latest_time:latestTime.trim()||null})});setSuccess(d.duplicate?"You’re already on the list for that preference.":"You’re on the waiting list. We’ll alert you when a suitable slot opens.");await load(session)}catch(e){setError(e.message||"Could not join the waiting list.")}finally{setSaving(false)}};
 const leave=async id=>{if(!id||saving)return;setSaving(true);setError("");try{await authedRequest(`/api/waiting-list/${id}`,{method:"DELETE"});await load(session)}catch(e){setError(e.message||"Could not leave the waiting list.")}finally{setSaving(false)}};
 return <Marble><SafeAreaView style={s.safe}><StatusBar barStyle="light-content"/><ScrollView contentContainerStyle={s.content} showsVerticalScrollIndicator={false}>
  <ClientHeader title="Waiting List" subtitle="Can’t see the right appointment? Join the list and we’ll alert you when a suitable slot opens." onBack={onBack}/>
  {busy?<View style={s.state}><ActivityIndicator color={M.gold}/><Text style={s.stateText}>Checking the waiting list…</Text></View>:null}
  {error?<View style={s.error}><Text style={s.errorText}>{error}</Text></View>:null}
  {success?<View style={s.success}><Text style={s.successText}>{success}</Text></View>:null}
  {!busy&&!session?.token?<View style={s.state}><Text style={s.stateIcon}>♙</Text><Text style={s.stateTitle}>Log In Required</Text><Text style={s.stateText}>Open your QuincyFadez client account first so waiting-list alerts stay linked to you.</Text></View>:null}
  {!busy&&session?.token&&!enabled?<View style={s.state}><Text style={s.stateIcon}>◷</Text><Text style={s.stateTitle}>Waiting List Closed</Text><Text style={s.stateText}>The waiting list is not open right now. You can still check normal appointment availability.</Text></View>:null}
  {!busy&&session?.token&&enabled?<><ClientSection title="JOIN THE WAITING LIST"/><View style={s.card}><Text style={s.label}>SERVICE</Text><View style={s.serviceGrid}>{services.map(item=><Pressable key={item.name} onPress={()=>setService(item.name)} style={[s.servicePill,service===item.name&&s.serviceOn]}><Text style={[s.serviceText,service===item.name&&s.serviceTextOn]}>{item.name}</Text></Pressable>)}</View><Text style={s.label}>PREFERENCE · OPTIONAL</Text><Text style={s.help}>Leave these blank if any suitable opening works.</Text><TextInput value={preferredDate} onChangeText={setPreferredDate} placeholder="Preferred date · YYYY-MM-DD" placeholderTextColor={M.muted2} style={s.input} autoCapitalize="none"/><View style={s.timeRow}><TextInput value={earliestTime} onChangeText={setEarliestTime} placeholder="Earliest · 10:00" placeholderTextColor={M.muted2} style={[s.input,s.timeInput]} maxLength={5}/><TextInput value={latestTime} onChangeText={setLatestTime} placeholder="Latest · 15:00" placeholderTextColor={M.muted2} style={[s.input,s.timeInput]} maxLength={5}/></View><Pressable disabled={!service||saving} onPress={join} style={[s.primary,(!service||saving)&&s.disabled]}>{saving?<ActivityIndicator color="#090704"/>:<><Text style={s.primaryText}>JOIN WAITING LIST</Text><Text style={s.primaryArrow}>›</Text></>}</Pressable></View></>:null}
  <ClientSection title="YOUR LIST"/><View style={s.card}><View style={s.currentHead}><View><Text style={s.currentTitle}>Current Requests</Text><Text style={s.currentSub}>Active waiting-list preferences</Text></View><View style={s.count}><Text style={s.countText}>{activeEntries.length}</Text></View></View>{activeEntries.length?activeEntries.map(entry=><View key={entry.id} style={s.entry}><View style={{flex:1}}><Text style={s.entryService}>{entry.service}</Text><Text style={s.entryMeta}>{entry.preferred_date||"Any date"}{entry.earliest_time||entry.latest_time?` · ${entry.earliest_time||"Any"}–${entry.latest_time||"Any"}`:" · Any time"}</Text><Text style={s.entryStatus}>{statusLabel(entry.status)}</Text></View><Pressable disabled={saving} onPress={()=>leave(entry.id)} style={s.leave}><Text style={s.leaveText}>LEAVE</Text></Pressable></View>):<Text style={s.noEntries}>You don’t have any active waiting-list requests.</Text>}</View>
 </ScrollView></SafeAreaView></Marble>
}

const s=StyleSheet.create({safe:{flex:1},content:{paddingHorizontal:18,paddingTop:7,paddingBottom:60},state:{borderRadius:15,borderWidth:1,borderColor:M.border,backgroundColor:"rgba(16,16,15,.93)",padding:22,alignItems:"center",...cardShadow},stateIcon:{color:M.gold,fontSize:33},stateTitle:{color:M.text,fontSize:18,fontWeight:"700",marginTop:9},stateText:{color:M.muted,fontSize:11.5,lineHeight:17,textAlign:"center",marginTop:7},error:{borderRadius:10,borderWidth:1,borderColor:"#63372E",backgroundColor:M.redBg,padding:11,marginBottom:10},errorText:{color:M.red,fontSize:10.5},success:{borderRadius:10,borderWidth:1,borderColor:"#315E42",backgroundColor:M.greenBg,padding:11,marginBottom:10},successText:{color:M.green,fontSize:10.5,lineHeight:15},card:{borderRadius:15,borderWidth:1,borderColor:"rgba(214,189,122,.22)",backgroundColor:"rgba(16,16,15,.93)",padding:15,...cardShadow},label:{color:M.gold,fontSize:8.5,fontWeight:"900",letterSpacing:.9},serviceGrid:{flexDirection:"row",flexWrap:"wrap",gap:8,marginTop:10,marginBottom:18},servicePill:{borderRadius:10,borderWidth:1,borderColor:M.border,backgroundColor:M.panel2,paddingHorizontal:11,paddingVertical:10},serviceOn:{backgroundColor:M.gold,borderColor:M.goldSoft},serviceText:{color:M.text2,fontSize:9,fontWeight:"700"},serviceTextOn:{color:"#090704",fontWeight:"900"},help:{color:M.muted,fontSize:9.5,lineHeight:14,marginTop:6},input:{height:50,borderRadius:10,borderWidth:1,borderColor:"rgba(255,255,255,.12)",backgroundColor:M.bg2,color:M.text,paddingHorizontal:12,fontSize:11,marginTop:9},timeRow:{flexDirection:"row",gap:8},timeInput:{flex:1},primary:{height:54,borderRadius:10,backgroundColor:M.gold,borderWidth:1,borderColor:M.goldSoft,marginTop:14,paddingHorizontal:15,flexDirection:"row",alignItems:"center",justifyContent:"space-between"},primaryText:{color:"#090704",fontSize:9.5,fontWeight:"900"},primaryArrow:{color:"#090704",fontSize:24},disabled:{opacity:.45},currentHead:{flexDirection:"row",alignItems:"center",justifyContent:"space-between"},currentTitle:{color:M.text,fontSize:16,fontWeight:"700"},currentSub:{color:M.muted,fontSize:9.5,marginTop:4},count:{width:34,height:34,borderRadius:17,borderWidth:1,borderColor:M.goldDark,backgroundColor:M.panel3,alignItems:"center",justifyContent:"center"},countText:{color:M.goldSoft,fontSize:12,fontWeight:"900"},entry:{marginTop:11,borderRadius:12,borderWidth:1,borderColor:M.borderSoft,backgroundColor:M.bg2,padding:12,flexDirection:"row",alignItems:"center",gap:10},entryService:{color:M.text,fontSize:12.5,fontWeight:"700"},entryMeta:{color:M.muted,fontSize:9,marginTop:4},entryStatus:{color:M.gold,fontSize:7.5,fontWeight:"900",letterSpacing:.7,marginTop:6},leave:{borderRadius:8,borderWidth:1,borderColor:"#5F312B",paddingHorizontal:10,paddingVertical:8},leaveText:{color:M.red,fontSize:7.5,fontWeight:"900"},noEntries:{color:M.muted,fontSize:10.5,lineHeight:16,textAlign:"center",paddingVertical:24}});